/**
 * Phase 1 data porter.
 *
 * Reads the verified 2026 dataset from legacy/data/config.json and emits the
 * typed data files under src/data/. Every figure is copied byte-for-byte from
 * legacy — this script never computes, rounds, or invents a value. Re-run it if
 * the legacy dataset is ever re-verified; do not hand-edit the generated files.
 *
 *   node scripts/gen-data.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cfg = JSON.parse(readFileSync(join(root, 'legacy/data/config.json'), 'utf8'));
const outDir = join(root, 'src/data');
mkdirSync(outDir, { recursive: true });

// Version tag derived from the legacy dataset's own correction history.
const VERIFIED = '2026-v3.3';
const lastVerified = cfg._meta?.lastVerified ?? 'unknown';

const j = (v) => JSON.stringify(v, null, 2);
const banner = (extra = '') =>
  `/**\n * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.\n * Verified 2026 dataset. Figures copied verbatim from the legacy source.${extra ? '\n * ' + extra : ''}\n */\n`;

// ---- federal.ts : all federal / shared tax constants (everything but states & platforms) ----
const federalTs =
  banner('Re-run the porter after any re-verification of the legacy data.') +
  `import type { FederalData } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n` +
  `export const LAST_VERIFIED = ${j(lastVerified)} as const;\n\n` +
  `export const federal = ${j(cfg.federal)} satisfies FederalData;\n\n` +
  `export const selfEmploymentDeductions = ${j(cfg.selfEmploymentDeductions)};\n\n` +
  `export const retirement = ${j(cfg.retirement)};\n\n` +
  `export const acaSubsidy = ${j(cfg.acaSubsidy)};\n\n` +
  `export const incomeSources = ${j(cfg.incomeSources)};\n\n` +
  `export const entityTypes = ${j(cfg.entityTypes)};\n\n` +
  `export const filingStatuses = ${j(cfg.filingStatuses)};\n\n` +
  `export const quarterlyDates2026 = ${j(cfg.quarterlyDates2026)};\n`;
writeFileSync(join(outDir, 'federal.ts'), federalTs);

// ---- states.ts ----
const statesTs =
  banner() +
  `import type { StateData } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n\n` +
  `export const states: Record<string, StateData> = ${j(cfg.states)};\n\n` +
  `export const stateMetadata = ${j(cfg.stateMetadata)};\n\n` +
  `/** Alphabetical [code, StateData] pairs — convenient for getStaticPaths. */\n` +
  `export const stateList = Object.entries(states).sort((a, b) => a[1].name.localeCompare(b[1].name));\n`;
writeFileSync(join(outDir, 'states.ts'), statesTs);

// ---- platforms.ts ----
// slug/name are DERIVED (presentation only), not tax figures. A few acronym fixups.
const NAME_FIXUPS = {
  onlyfans: 'OnlyFans', youtube: 'YouTube', tiktok: 'TikTok', ebay: 'eBay',
  amazon_fba: 'Amazon FBA', amazon_flex: 'Amazon Flex', vrbo: 'Vrbo',
  ugc_creator: 'UGC Creator', rv_rental: 'RV Rental', stockx_goat: 'StockX / GOAT',
  printful_printify: 'Printful / Printify', spark_walmart: 'Spark (Walmart)',
  stan_store: 'Stan Store', handyman_1099: 'Handyman', babysitter_nanny_1099: 'Babysitter / Nanny',
  real_estate_agent_rental: 'Real Estate Agent', short_vs_long_term_rental: 'Short vs Long-Term Rental',
};
const titleCase = (key) =>
  NAME_FIXUPS[key] ??
  key.replace(/_1099$/, '').split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

const summaries = [];
for (const [category, entries] of Object.entries(cfg.platforms)) {
  for (const [key, entry] of Object.entries(entries)) {
    summaries.push({
      slug: key.replace(/_/g, '-'),
      name: titleCase(key),
      category,
      key,
      incomeType: entry.incomeType ?? 'Self-reported (report even without a 1099)',
      keyDeductions: entry.keyDeductions ?? [],
    });
  }
}

const platformsTs =
  banner('slug and name are DERIVED for display; all tax-relevant fields are verbatim.') +
  `import type { PlatformCategories, PlatformSummary } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n\n` +
  `export const platforms: PlatformCategories = ${j(cfg.platforms)};\n\n` +
  `/** Flattened, page-ready list. NOTE: worked-example incomes are NOT in the legacy\n` +
  ` *  dataset and must be supplied (owner) before Tier-3 platform pages are built. */\n` +
  `export const platformList: PlatformSummary[] = ${j(summaries)};\n`;
writeFileSync(join(outDir, 'platforms.ts'), platformsTs);

console.log('Wrote src/data/{federal,states,platforms}.ts');
console.log(`  states: ${Object.keys(cfg.states).length}, platforms: ${summaries.length}, verified: ${VERIFIED}`);
