/**
 * Phase 1 data porter.
 *
 * Reads the verified 2026 dataset from legacy/data/config.json and emits the
 * typed data files under src/data/. Every figure is copied byte-for-byte from
 * legacy — this script never computes, rounds, or invents a value. Re-run it if
 * the legacy dataset is ever re-verified; do not hand-edit the generated files.
 *
 *   node scripts/gen-data.mjs
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cfg = JSON.parse(readFileSync(join(root, 'legacy/data/config.json'), 'utf8'));
const outDir = join(root, 'src/data');
mkdirSync(outDir, { recursive: true });

// Version tag derived from the legacy dataset's own correction history.
const VERIFIED = '2026-v3.3';
const lastVerified = cfg._meta?.lastVerified ?? 'unknown';

const j = (v) => JSON.stringify(v, null, 2);
const banner = (extra = '') =>
  `/**\n * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.\n * Verified 2026 dataset. Figures copied verbatim from the legacy source.${extra ? '\n * ' + extra : ''}\n */\n`;

// ---- federal.ts : all federal / shared tax constants (everything but states & platforms) ----
const federalTs =
  banner('Re-run the porter after any re-verification of the legacy data.') +
  `import type { FederalData } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n` +
  `export const LAST_VERIFIED = ${j(lastVerified)} as const;\n\n` +
  `export const federal = ${j(cfg.federal)} satisfies FederalData;\n\n` +
  `export const selfEmploymentDeductions = ${j(cfg.selfEmploymentDeductions)};\n\n` +
  `export const retirement = ${j(cfg.retirement)};\n\n` +
  `export const acaSubsidy = ${j(cfg.acaSubsidy)};\n\n` +
  `export const incomeSources = ${j(cfg.incomeSources)};\n\n` +
  `export const equityCompensation = ${j(cfg.equityCompensation)};\n\n` +
  `export const entityTypes = ${j(cfg.entityTypes)};\n\n` +
  `export const filingStatuses = ${j(cfg.filingStatuses)};\n\n` +
  `export const quarterlyDates2026 = ${j(cfg.quarterlyDates2026)};\n`;
writeFileSync(join(outDir, 'federal.ts'), federalTs);

// ---- states.ts ----
/**
 * Four states (MD, NE, SC, WV) reached us with a `type` and a `topRate` but no
 * bracket array, so the engine computed $0 of state income tax for them on every
 * page. legacy/ is read-only and states.ts is generated, so the researched
 * brackets live in their own reviewed overlay and are merged in here — that
 * keeps generation reproducible and keeps the sourcing next to the figures.
 */
const overridesPath = join(root, 'src/data/overrides/state-brackets-2026.json');
const overrides = JSON.parse(readFileSync(overridesPath, 'utf8'));
const patchedStates = structuredClone(cfg.states);
const patched = [];
for (const [code, patch] of Object.entries(overrides)) {
  if (code === '_meta') continue;
  if (!patchedStates[code]) throw new Error(`override for unknown state ${code}`);
  for (const [field, value] of Object.entries(patch)) {
    if (field.startsWith('_')) continue; // provenance notes, not data
    patchedStates[code][field] = value;
  }
  patchedStates[code].bracketSource = `overrides/state-brackets-2026.json (${overrides._meta.verified})`;
  patched.push(code);
}
console.log(`  bracket overrides applied: ${patched.join(', ')}`);

const statesTs =
  banner(`Bracket overrides from src/data/overrides/state-brackets-2026.json applied to: ${patched.join(', ')}.`) +
  `import type { StateData } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n\n` +
  `export const states: Record<string, StateData> = ${j(patchedStates)};\n\n` +
  `export const stateMetadata = ${j(cfg.stateMetadata)};\n\n` +
  `/** Alphabetical [code, StateData] pairs — convenient for getStaticPaths. */\n` +
  `export const stateList = Object.entries(states).sort((a, b) => a[1].name.localeCompare(b[1].name));\n`;
writeFileSync(join(outDir, 'states.ts'), statesTs);

// ---- platforms.ts ----
// slug/name are DERIVED (presentation only), not tax figures. A few acronym fixups.
const NAME_FIXUPS = {
  onlyfans: 'OnlyFans', youtube: 'YouTube', tiktok: 'TikTok', ebay: 'eBay',
  amazon_fba: 'Amazon FBA', amazon_flex: 'Amazon Flex', vrbo: 'Vrbo',
  ugc_creator: 'UGC Creator', rv_rental: 'RV Rental', stockx_goat: 'StockX / GOAT',
  printful_printify: 'Printful / Printify', spark_walmart: 'Spark (Walmart)',
  stan_store: 'Stan Store', handyman_1099: 'Handyman', babysitter_nanny_1099: 'Babysitter / Nanny',
  real_estate_agent_rental: 'Real Estate Agent', short_vs_long_term_rental: 'Short vs Long-Term Rental',
};
const titleCase = (key) =>
  NAME_FIXUPS[key] ??
  key.replace(/_1099$/, '').split('_').map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');

const summaries = [];
for (const [category, entries] of Object.entries(cfg.platforms)) {
  for (const [key, entry] of Object.entries(entries)) {
    summaries.push({
      slug: key.replace(/_/g, '-'),
      name: titleCase(key),
      category,
      key,
      incomeType: entry.incomeType ?? 'Self-reported (report even without a 1099)',
      keyDeductions: entry.keyDeductions ?? [],
    });
  }
}

const platformsTs =
  banner('slug and name are DERIVED for display; all tax-relevant fields are verbatim.') +
  `import type { PlatformCategories, PlatformSummary } from './types';\n\n` +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n\n` +
  `export const platforms: PlatformCategories = ${j(cfg.platforms)};\n\n` +
  `/** Flattened, page-ready list. NOTE: worked-example incomes are NOT in the legacy\n` +
  ` *  dataset and must be supplied (owner) before Tier-3 platform pages are built. */\n` +
  `export const platformList: PlatformSummary[] = ${j(summaries)};\n`;
writeFileSync(join(outDir, 'platforms.ts'), platformsTs);

// ---- professionals.ts : the legacy profiles, plus the authored trades overlay ----
/**
 * legacy/data/config.json carries 23 professions and none of the building or
 * mechanical trades — no electrician, no plumber, no HVAC. Those live in their
 * own overlay so this stays reproducible and so the boundary is explicit: the
 * overlay adds deduction CATEGORIES and practice notes, never a figure.
 */
const tradesPath = join(root, 'src/data/overrides/professions-trades.json');
const trades = JSON.parse(readFileSync(tradesPath, 'utf8'));
const allProfessions = structuredClone(cfg.professionals);
for (const [key, entry] of Object.entries(trades)) {
  if (key.startsWith('_')) continue;
  if (allProfessions[key]) throw new Error(`trade overlay would overwrite legacy profession ${key}`);
  allProfessions[key] = entry;
}
console.log(`  trade professions added: ${Object.keys(trades).length - 1}`);

const professionalsTs =
  banner('Legacy deduction slugs, notes and unique rules copied verbatim, MERGED with the authored trades in overrides/professions-trades.json. Labels are applied in lib/professions.ts.') +
  `export const VERIFIED = ${j(VERIFIED)} as const;\n\n` +
  `export const professionals = ${j(allProfessions)};\n\n` +
  `export default professionals;\n`;
writeFileSync(join(outDir, 'professionals.ts'), professionalsTs);

console.log('Wrote src/data/{federal,states,platforms,professionals}.ts');
console.log(`  states: ${Object.keys(cfg.states).length}, platforms: ${summaries.length}, professions: ${Object.keys(allProfessions).length}, verified: ${VERIFIED}`);
