/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * Re-run the porter after any re-verification of the legacy data.
 */
import type { FederalData } from './types';

export const VERIFIED = "2026-v3.3" as const;
export const LAST_VERIFIED = "2026-06-10" as const;

export const federal = {
  "brackets": {
    "single": [
      {
        "min": 0,
        "max": 12400,
        "rate": 0.1
      },
      {
        "min": 12400,
        "max": 50400,
        "rate": 0.12
      },
      {
        "min": 50400,
        "max": 105700,
        "rate": 0.22
      },
      {
        "min": 105700,
        "max": 201775,
        "rate": 0.24
      },
      {
        "min": 201775,
        "max": 256225,
        "rate": 0.32
      },
      {
        "min": 256225,
        "max": 640600,
        "rate": 0.35
      },
      {
        "min": 640600,
        "max": null,
        "rate": 0.37
      }
    ],
    "mfj": [
      {
        "min": 0,
        "max": 24800,
        "rate": 0.1
      },
      {
        "min": 24800,
        "max": 100800,
        "rate": 0.12
      },
      {
        "min": 100800,
        "max": 211400,
        "rate": 0.22
      },
      {
        "min": 211400,
        "max": 403550,
        "rate": 0.24
      },
      {
        "min": 403550,
        "max": 512450,
        "rate": 0.32
      },
      {
        "min": 512450,
        "max": 768700,
        "rate": 0.35
      },
      {
        "min": 768700,
        "max": null,
        "rate": 0.37
      }
    ],
    "mfs": [
      {
        "min": 0,
        "max": 12400,
        "rate": 0.1
      },
      {
        "min": 12400,
        "max": 50400,
        "rate": 0.12
      },
      {
        "min": 50400,
        "max": 105700,
        "rate": 0.22
      },
      {
        "min": 105700,
        "max": 201775,
        "rate": 0.24
      },
      {
        "min": 201775,
        "max": 256225,
        "rate": 0.32
      },
      {
        "min": 256225,
        "max": 384350,
        "rate": 0.35
      },
      {
        "min": 384350,
        "max": null,
        "rate": 0.37
      }
    ],
    "hoh": [
      {
        "min": 0,
        "max": 17700,
        "rate": 0.1
      },
      {
        "min": 17700,
        "max": 67450,
        "rate": 0.12
      },
      {
        "min": 67450,
        "max": 105700,
        "rate": 0.22
      },
      {
        "min": 105700,
        "max": 201750,
        "rate": 0.24
      },
      {
        "min": 201750,
        "max": 256200,
        "rate": 0.32
      },
      {
        "min": 256200,
        "max": 640600,
        "rate": 0.35
      },
      {
        "min": 640600,
        "max": null,
        "rate": 0.37
      }
    ],
    "qsw": [
      {
        "min": 0,
        "max": 24800,
        "rate": 0.1
      },
      {
        "min": 24800,
        "max": 100800,
        "rate": 0.12
      },
      {
        "min": 100800,
        "max": 211400,
        "rate": 0.22
      },
      {
        "min": 211400,
        "max": 403550,
        "rate": 0.24
      },
      {
        "min": 403550,
        "max": 512450,
        "rate": 0.32
      },
      {
        "min": 512450,
        "max": 768700,
        "rate": 0.35
      },
      {
        "min": 768700,
        "max": null,
        "rate": 0.37
      }
    ]
  },
  "standardDeduction": {
    "source": "IRS Rev. Proc. 2025-28 (2026 inflation adjustments). Verified June 2026.",
    "single": 16100,
    "mfj": 32200,
    "mfs": 16100,
    "hoh": 24150,
    "qsw": 32200,
    "additionalAge65Single": 2050,
    "additionalAge65MFJ": 1650,
    "seniorDeductionOBBBA": {
      "amount": 6000,
      "amountMFJ": 12000,
      "phaseoutStartSingle": 75000,
      "phaseoutStartMFJ": 150000,
      "phaseoutRate": 0.06,
      "expiresAfterYear": 2028,
      "note": "New OBBBA 2025 deduction for age 65+. Separate from additional standard deduction."
    }
  },
  "capitalGains": {
    "longTerm": {
      "single": [
        {
          "min": 0,
          "max": 49450,
          "rate": 0
        },
        {
          "min": 49450,
          "max": 545500,
          "rate": 0.15
        },
        {
          "min": 545500,
          "max": null,
          "rate": 0.2
        }
      ],
      "mfj": [
        {
          "min": 0,
          "max": 98900,
          "rate": 0
        },
        {
          "min": 98900,
          "max": 613700,
          "rate": 0.15
        },
        {
          "min": 613700,
          "max": null,
          "rate": 0.2
        }
      ],
      "mfs": [
        {
          "min": 0,
          "max": 49450,
          "rate": 0
        },
        {
          "min": 49450,
          "max": 306850,
          "rate": 0.15
        },
        {
          "min": 306850,
          "max": null,
          "rate": 0.2
        }
      ],
      "hoh": [
        {
          "min": 0,
          "max": 66200,
          "rate": 0
        },
        {
          "min": 66200,
          "max": 579600,
          "rate": 0.15
        },
        {
          "min": 579600,
          "max": null,
          "rate": 0.2
        }
      ]
    },
    "shortTerm": "taxedAsOrdinaryIncome",
    "niit": {
      "rate": 0.038,
      "thresholdSingle": 200000,
      "thresholdMFJ": 250000,
      "note": "Not indexed for inflation. Unchanged since 2013.",
      "thresholdHOH": 200000,
      "thresholdMFS": 125000
    },
    "collectibles": 0.28,
    "unrecaptured1250": 0.25,
    "annualLossLimit": 3000,
    "annualLossLimitMFS": 1500
  },
  "alternativeMinimumTax": {
    "exemptionSingle": 90100,
    "exemptionMFJ": 140200,
    "phaseoutStartSingle": 500000,
    "phaseoutStartMFJ": 1000000,
    "rate1": 0.26,
    "rate2": 0.28,
    "rate2ThresholdSingle": 244500,
    "rate2ThresholdMFJ": 244500
  },
  "selfEmployment": {
    "seTaxRate": 0.153,
    "socialSecurityRate": 0.124,
    "medicareRate": 0.029,
    "socialSecurityWageBase": 184500,
    "netEarningsMultiplier": 0.9235,
    "selfDeductionRate": 0.5,
    "additionalMedicare": {
      "rate": 0.009,
      "thresholdSingle": 200000,
      "thresholdMFJ": 250000,
      "thresholdMFS": 125000,
      "note": "Applies to wages and SE income over threshold. Not indexed for inflation."
    },
    "note": "SE tax = seTaxRate x (netEarnings x netEarningsMultiplier). Half of SE tax is deductible from AGI."
  },
  "quarterlyEstimated": {
    "year": 2026,
    "quarters": [
      {
        "quarter": 1,
        "periodLabel": "Jan 1 – Mar 31",
        "dueDate": "2026-04-15",
        "irsForm": "1040-ES"
      },
      {
        "quarter": 2,
        "periodLabel": "Apr 1 – May 31",
        "dueDate": "2026-06-16",
        "irsForm": "1040-ES"
      },
      {
        "quarter": 3,
        "periodLabel": "Jun 1 – Aug 31",
        "dueDate": "2026-09-15",
        "irsForm": "1040-ES"
      },
      {
        "quarter": 4,
        "periodLabel": "Sep 1 – Dec 31",
        "dueDate": "2027-01-15",
        "irsForm": "1040-ES"
      }
    ],
    "safeHarborRules": {
      "rule1": "Pay 90% of current year tax liability",
      "rule2": "Pay 100% of prior year tax liability (110% if prior year AGI > $150,000)",
      "underpaymentPenaltyRate": "Federal short-term rate + 3% (varies quarterly)",
      "minimumToOweEstimated": 1000
    }
  },
  "childTaxCredit": {
    "amountPerChild": 2200,
    "ageLimit": 17,
    "refundableAmount": 1700,
    "phaseoutStartSingle": 200000,
    "phaseoutStartMFJ": 400000,
    "phaseoutRate": 0.05,
    "note": "OBBBA permanently extended CTC. Refundable portion (ACTC) up to $1,700."
  },
  "earnedIncomeCredit": {
    "year": 2026,
    "brackets": [
      {
        "children": 0,
        "maxCredit": 664,
        "incomeLimit": 19540,
        "phaseoutStart": 10860
      },
      {
        "children": 1,
        "maxCredit": 4427,
        "incomeLimit": 51593,
        "phaseoutStart": 23890
      },
      {
        "children": 2,
        "maxCredit": 7316,
        "incomeLimit": 58629,
        "phaseoutStart": 23890
      },
      {
        "children": 3,
        "maxCredit": 8231,
        "incomeLimit": 62974,
        "phaseoutStart": 23890
      }
    ],
    "investmentIncomeLimit": 12200,
    "note": "MFJ phaseout starts approximately $7,270 higher than single/hoh. Single/HOH figures shown; calcEIC does not currently adjust for filing status."
  },
  "childDependentCareCredit": {
    "maxExpenseOneChild": 3000,
    "maxExpenseTwoPlus": 6000,
    "creditRateMin": 0.2,
    "creditRateMax": 0.35,
    "phaseoutStartIncome": 15000,
    "note": "Non-refundable. Rate phases down from 35% to 20% as income rises above $15,000."
  },
  "saltDeduction": {
    "cap": 40400,
    "capMFJ": 40400,
    "phaseoutStartMAGI": 505000,
    "revertTo": 10000,
    "revertYear": 2030,
    "note": "OBBBA raised SALT cap from $10,000 to $40,400 (2026-2029). Phases out for high earners."
  },
  "mortgageInterestDeduction": {
    "loanLimitNewLoans": 750000,
    "loanLimitPreTCJA": 1000000,
    "note": "Only for loans originated after Dec 15, 2017. Older loans still use $1M limit."
  },
  "giftAndEstate": {
    "annualGiftExclusion": 19000,
    "lifetimeEstateTaxExemption": 15000000,
    "topEstateTaxRate": 0.4
  },
  "foreignEarnedIncomeExclusion": {
    "amount": 132900,
    "note": "For US citizens/residents working abroad who meet bona fide residence or physical presence test."
  }
} satisfies FederalData;

export const selfEmploymentDeductions = {
  "mileage": {
    "businessRatePerMile": 0.725,
    "medicalRatePerMile": 0.205,
    "charitableRatePerMile": 0.14,
    "movingRatePerMile": 0.205,
    "source": "IRS Notice 2026-10 (from 1 Jan 2026); Announcement 2026-11 (from 1 Jul 2026)",
    "note": "TWO business rates in 2026: 72.5 cents from January 1 (Notice 2026-10), raised to 76 cents for expenses paid or incurred on or after July 1 (Announcement 2026-11). A full calendar year must be split at that date. Cannot use the standard rate at all on a vehicle previously depreciated under MACRS, Section 179 or bonus depreciation.",
    "businessRatePerMileFromJul1": 0.76,
    "medicalRatePerMileFromJul1": 0.235
  },
  "homeOffice": {
    "simplified": {
      "ratePerSqFt": 5,
      "maxSqFt": 300,
      "maxDeduction": 1500,
      "note": "No depreciation recapture on home sale. Simpler recordkeeping."
    },
    "actual": {
      "method": "Divide home office sq ft by total home sq ft. Apply percentage to: mortgage interest or rent, utilities, insurance, repairs, depreciation.",
      "depreciationPeriod": 39,
      "note": "Depreciation recapture (25%) applies when home is sold. Higher deduction for most situations."
    },
    "rule": "Space must be used regularly and exclusively for business. Home office must be principal place of business."
  },
  "section179": {
    "limit": 2560000,
    "phaseoutStart": 4090000,
    "bonusDepreciationRate": 1,
    "suvLimit": 32000,
    "businessUsePctRequired": 0.5,
    "note": "OBBBA made 100% bonus depreciation permanent for qualified property placed in service after Jan 19, 2025."
  },
  "vehicleActualMethod": {
    "approach": "Track actual gas, insurance, repairs, registration, depreciation x business-use percentage",
    "macrsDepreciationCar": {
      "year1": 12400,
      "year2": 19800,
      "year3": 11900,
      "year4Plus": 7160,
      "note": "Annual luxury auto limits. Apply business-use % to these caps."
    }
  },
  "augustaRule": {
    "code": "IRC Section 280A(g)",
    "maxDays": 14,
    "taxTreatment": "Rental income from personal residence is excluded from gross income (not reported). Business deducts rent as ordinary business expense.",
    "eligibleEntities": [
      "S Corporation",
      "C Corporation",
      "Partnership/Multi-member LLC"
    ],
    "notEligible": [
      "Sole proprietor",
      "Single-member LLC taxed as disregarded entity"
    ],
    "requirements": [
      "Must be fair market rate (document with Peerspace, hotel, coworking comparables)",
      "Must have written rental agreement between you and the entity",
      "Must have documented business purpose (board meeting, retreat, planning session)",
      "Must have meeting agenda",
      "Cannot also deduct home office for same space on same days",
      "Cannot be primary place of business"
    ],
    "maxTaxFreeSavings": "Days x FMR daily rate (up to 14 days). Tax-free to owner. Deductible to entity."
  },
  "selfEmployedHealthInsurance": {
    "deductionPct": 1,
    "covers": [
      "Medical",
      "Dental",
      "Vision",
      "Long-term care (limits apply)"
    ],
    "limit": "Cannot exceed net SE profit",
    "notAvailableIf": "Eligible for employer-subsidized plan through spouse's employer",
    "sCorpNote": "S Corp owner-employees include health insurance in W-2 Box 1 wages, then deduct as SE health insurance on 1040."
  },
  "mealsDeduction": {
    "rate": 0.5,
    "requirements": [
      "Business purpose",
      "Document: who, what, where, business discussed"
    ],
    "note": "100% deductible for food at a restaurant provided to employee on employer premises (company cafeteria). 50% for client meals and business meals away."
  },
  "businessTravel": {
    "airfareDeductible": 1,
    "hotelDeductible": 1,
    "mealsDeductible": 0.5,
    "groundTransportDeductible": 1,
    "perDiemAlternative": true,
    "truckDriverPerDiem": {
      "rate": 80,
      "deductiblePct": 0.8,
      "note": "$80/day for OTR truck drivers (DOT regulated). 80% deductible. $64/day net deduction."
    },
    "spouseTravelRule": "Spouse travel deductible ONLY if spouse is employee of business and travel has bona fide business purpose."
  },
  "phoneAndInternet": {
    "method": "Business-use percentage of total cost",
    "typicalBusinessPct": {
      "gig_driver": 0.8,
      "content_creator": 0.9,
      "remote_professional": 0.7,
      "mixed_use": 0.5
    }
  },
  "qualifiedBusinessIncomeDeduction": {
    "code": "IRC Section 199A",
    "rate": 0.2,
    "permanentUnderOBBBA": true,
    "phaseoutSingle": 201750,
    "phaseoutMFJ": 403500,
    "phaseoutRangeSingle": 75000,
    "phaseoutRangeMFJ": 150000,
    "sstbNote": "Specified Service Trades or Businesses (health, law, consulting, athletics, financial services, performing arts) — QBI fully phases out for SSTBs above phaseout range.",
    "wageLimit": "At higher incomes, QBI limited to greater of: 50% of W-2 wages paid, or 25% of W-2 wages + 2.5% of qualified property",
    "note": "QBI deduction applies to sole props, partnerships, S corps, trusts. Does NOT apply to C corps or employee wages."
  },
  "familyEmployment": {
    "hireChildren": {
      "ficaExemptUnder18": true,
      "ficaExemptAppliesTo": "Sole proprietor and husband/wife partnership only",
      "standardDeduction2026": 16100,
      "effectiveTaxFreeWagesPerChild": 16100,
      "maxReasonableWages": "Must be real work at fair market rate",
      "bestPractices": [
        "Job description",
        "Timesheets",
        "Separate bank account for child",
        "Regular pay schedule"
      ],
      "ficaAppliesAge18plus": true
    },
    "hireSpouse": {
      "ficaApplies": true,
      "benefits": [
        "Spouse eligible for employer retirement plan",
        "Wages deductible business expense",
        "Spouse builds own Social Security credits"
      ],
      "sole_prop_note": "Sole prop employing spouse: FUTA does NOT apply to spouse wages. State unemployment varies."
    }
  },
  "otherCommonDeductions": [
    {
      "name": "Professional development",
      "deductible": 1,
      "note": "Must maintain/improve current business skills. Not qualifying for new career."
    },
    {
      "name": "Professional fees (CPA, attorney, consultant)",
      "deductible": 1,
      "note": ""
    },
    {
      "name": "Software and subscriptions",
      "deductible": 1,
      "note": "R&D software can be fully expensed in year of cost under OBBBA."
    },
    {
      "name": "Advertising and marketing",
      "deductible": 1,
      "note": ""
    },
    {
      "name": "Bank and merchant processing fees",
      "deductible": 1,
      "note": ""
    },
    {
      "name": "Business insurance",
      "deductible": 1,
      "note": ""
    },
    {
      "name": "Rent for office or workspace",
      "deductible": 1,
      "note": ""
    },
    {
      "name": "Startup costs",
      "deductible": 5000,
      "note": "$5,000 deductible in year 1. Remainder amortized over 180 months."
    },
    {
      "name": "Qualified retirement plan contributions",
      "deductible": 1,
      "note": "Solo 401k, SEP-IRA, SIMPLE. See retirement section."
    },
    {
      "name": "Uniforms/protective clothing",
      "deductible": 1,
      "note": "Must not be suitable for everyday wear. Work boots, hard hats, lab coats OK. Business casual not deductible."
    },
    {
      "name": "Tools and equipment (under Section 179)",
      "deductible": 1,
      "note": "Up to $2,560,000. Must be >50% business use."
    },
    {
      "name": "Charitable contributions",
      "deductible": 0,
      "note": "NOT deductible on Schedule C. Deductible only as itemized deduction on Schedule A."
    }
  ],
  "_deductionSchema": "All deduction arrays use: { name:string, deductible:number (1.0=100%, 0.5=50%, 0=not deductible, dollar_amount=capped), note:string }. Access as item.deductible ?? 1.0 and item.note ?? '' to handle legacy entries safely."
};

export const retirement = {
  "solo401k": {
    "employeeLimit": 24500,
    "employerLimit": "25% of net self-employment income (approx 20% before SE tax deduction)",
    "combinedMaxUnder50": 72000,
    "catchUp50to59": 8000,
    "catchUp60to63": 11250,
    "combinedMax50to59": 80000,
    "combinedMax60to63": 83250,
    "compensationLimit": 360000,
    "rothCatchUpMandatoryThreshold": 150000,
    "note": "Employee deferral deadline: Dec 31. Employer contribution deadline: tax filing deadline + extensions."
  },
  "sep_ira": {
    "limit": 72000,
    "limitPct": 0.25,
    "compensationLimit": 360000,
    "filingDeadline": "Tax return due date including extensions (Oct 15, 2027)",
    "note": "25% of W-2 compensation or 20% of net SE income (after SE tax deduction), whichever is less."
  },
  "simple_ira": {
    "employeeLimit": 17000,
    "catchUp50": 4000,
    "catchUp60to63": 5250,
    "employerMatch": "2% of compensation (non-elective) or 3% matching"
  },
  "traditional_ira": {
    "limit": 7500,
    "catchUp50": 1100,
    "totalLimit50plus": 8600,
    "deductibilityPhaseout": {
      "coveredByWorkplacePlan_single": {
        "start": 79000,
        "end": 89000
      },
      "coveredByWorkplacePlan_mfj": {
        "start": 126000,
        "end": 146000
      },
      "notCoveredSpouseIsCovered_mfj": {
        "start": 242000,
        "end": 252000
      }
    },
    "note": "IRA catch-up increased to $1,100 in 2026 — first increase since 2006 (SECURE 2.0 inflation indexing)"
  },
  "roth_ira": {
    "limit": 7500,
    "catchUp50": 1100,
    "incomePhaseout": {
      "single": {
        "start": 153000,
        "end": 168000
      },
      "mfj": {
        "start": 242000,
        "end": 252000
      },
      "mfs": {
        "start": 0,
        "end": 10000
      }
    },
    "backdoorNote": "If over income limit, use backdoor Roth (non-deductible traditional IRA then convert). Pro-rata rule applies."
  },
  "hsa": {
    "selfOnly": 4400,
    "family": 8750,
    "catchUp55": 1000,
    "hdhpMinDeductibleSelf": 1650,
    "hdhpMinDeductibleFamily": 3300,
    "hdhpMaxOopSelf": 8300,
    "hdhpMaxOopFamily": 16600,
    "note": "Triple tax advantage: deductible contribution, tax-free growth, tax-free withdrawals for medical. HSA funds can invest like IRA after minimum cash balance met.",
    "_correctionNote": "Corrected June 2026: previous values ($4,300/$8,550) were 2025 figures. 2026 limits per IRS Notice 2025-67 are $4,400 (self-only) and $8,750 (family). Source: White Coat Investor, IRS Notice 2025-67, ALPA benefits summary."
  },
  "definedBenefit": {
    "maxBenefit": 275000,
    "maxContributionEstimate": "Varies by age and actuarial factors. Can exceed $200,000/yr for older high earners.",
    "note": "Requires actuary. Best for high earners age 50+ with stable high income."
  },
  "saversCredit": {
    "mfj_max": 80500,
    "hoh_max": 60375,
    "single_max": 40250,
    "maxCredit": 1000,
    "maxCreditMFJ": 2000
  }
};

export const acaSubsidy = {
  "year": 2026,
  "cliffNote": "OBBBA did NOT extend enhanced subsidies past Dec 31, 2025. Hard 400% FPL cliff returned January 1, 2026.",
  "eligibilityRange": "100% to 400% of FPL (MAGI-based)",
  "medicaidExpansionStates": "138% FPL lower bound in states that expanded Medicaid (38 states + DC as of 2026)",
  "fpl2026": {
    "persons1": 15960,
    "persons2": 21540,
    "persons3": 27120,
    "persons4": 33000,
    "persons5": 38880,
    "persons6": 44760,
    "persons7": 50640,
    "persons8": 56520,
    "additionalPerPerson": 5880,
    "note": "Based on 2025 HHS poverty guidelines used for 2026 coverage. Alaska and Hawaii higher."
  },
  "cliffThresholds400pct": {
    "persons1": 63840,
    "persons2": 86160,
    "persons3": 108480,
    "persons4": 132000,
    "persons5": 155520,
    "persons6": 179040,
    "note": "Earning $1 above these amounts = $0 premium tax credit. Plan income carefully."
  },
  "applicablePercentages2026": [
    {
      "fplMin": 1,
      "fplMax": 1.33,
      "pct": 0
    },
    {
      "fplMin": 1.33,
      "fplMax": 1.5,
      "pct": 0.02
    },
    {
      "fplMin": 1.5,
      "fplMax": 2,
      "pct": 0.06
    },
    {
      "fplMin": 2,
      "fplMax": 2.5,
      "pct": 0.08
    },
    {
      "fplMin": 2.5,
      "fplMax": 3,
      "pct": 0.085
    },
    {
      "fplMin": 3,
      "fplMax": 4,
      "pct": 0.085
    },
    {
      "fplMin": 4,
      "fplMax": null,
      "pct": null,
      "eligible": false
    }
  ],
  "magi_definition": "AGI + tax-exempt interest + nontaxable Social Security + foreign earned income exclusion",
  "benchmark": "Second Lowest-Cost Silver Plan (SLCSP) in enrollee's rating area",
  "subsidy_formula": "Monthly subsidy = SLCSP premium - (MAGI x applicable_pct / 12)",
  "clawback": {
    "below400pct": "Partial clawback if income underestimated. Capped based on FPL bracket.",
    "above400pct": "Full repayment of all APTC received. No cap.",
    "form": "Form 8962"
  },
  "incomeReducingStrategies": [
    "Solo 401(k) employee + employer contributions (up to $72,000)",
    "Traditional IRA deductible contribution (up to $7,500)",
    "HSA contribution (up to $4,400 self/$8,750 family)",
    "Self-employed health insurance deduction (circular interaction — use Pub 974 method)",
    "Business deductions on Schedule C reduce net SE income → AGI → MAGI",
    "Avoid Roth conversions in subsidy-eligible years",
    "Delay taxable account capital gains realization",
    "Use DAF for charitable giving if itemizing"
  ],
  "csrNote": "Cost-Sharing Reductions available at 100–250% FPL on Silver plans. Reduce deductibles and out-of-pocket costs."
};

export const incomeSources = {
  "w2Employee": {
    "taxForm": "W-2",
    "seTaxApplies": false,
    "ficaSplit": "Employer pays 50%, employee pays 50% (6.2% SS + 1.45% Medicare each)",
    "quarterlyEstimated": "Generally not required if withholding sufficient"
  },
  "1099NEC": {
    "taxForm": "1099-NEC",
    "threshold2026": 2000,
    "priorThreshold": 600,
    "note": "OBBBA raised threshold from $600 to $2,000 for payments made in calendar year 2026 (reported on 2026 returns filed in 2027). Income still taxable even without 1099-NEC below threshold.",
    "seTaxApplies": true
  },
  "1099K": {
    "taxForm": "1099-K",
    "threshold2026": 20000,
    "transactionThreshold": 200,
    "note": "Threshold restored to pre-2021 level by OBBBA. Income taxable even if 1099-K not issued. Gross receipts shown — must subtract fees, refunds, COGS to get taxable amount.",
    "commonIssuers": [
      "PayPal",
      "Venmo",
      "Cash App",
      "Etsy",
      "eBay",
      "Amazon",
      "Airbnb",
      "Poshmark",
      "Stripe"
    ]
  },
  "1099MISC": {
    "note": "Used for rents, prizes, awards, and certain other payments. Not for services (that's 1099-NEC)."
  },
  "ssdi": {
    "taxability": {
      "formula": "Combined income = AGI (excl SS) + tax-exempt interest + 0.5 x annual SSDI benefit",
      "tiers": {
        "single": [
          {
            "combinedIncomeMax": 25000,
            "taxablePct": 0
          },
          {
            "combinedIncomeMin": 25000,
            "combinedIncomeMax": 34000,
            "taxablePct": 0.5
          },
          {
            "combinedIncomeMin": 34000,
            "taxablePct": 0.85
          }
        ],
        "mfj": [
          {
            "combinedIncomeMax": 32000,
            "taxablePct": 0
          },
          {
            "combinedIncomeMin": 32000,
            "combinedIncomeMax": 44000,
            "taxablePct": 0.5
          },
          {
            "combinedIncomeMin": 44000,
            "taxablePct": 0.85
          }
        ],
        "mfs_living_together": {
          "taxablePct": 0.85,
          "note": "85% taxable at any income. No threshold benefit."
        }
      },
      "maximumTaxablePct": 0.85,
      "ssiNote": "SSI (Supplemental Security Income) is NEVER taxable. Completely different program from SSDI.",
      "statesThatTaxSSBenefits": [
        "CO",
        "CT",
        "KS",
        "MN",
        "MO",
        "MT",
        "NE",
        "NM",
        "RI",
        "UT",
        "VT",
        "WV"
      ]
    },
    "sgaLimit2026": 1690,
    "sgaLimitBlind2026": 2830,
    "note": "SGA = Substantial Gainful Activity. Earning above SGA consistently may trigger SSDI eligibility review.",
    "_sgaCorrectionNote": "Corrected June 2026: previous values ($1,620/$2,700) were 2025 SGA limits. 2026 SGA limits per SSA (2.8% COLA applied): $1,690/mo non-blind, $2,830/mo blind. Source: SSA.gov, Atticus, DisabilityExchange.org, Michael Armstrong Law."
  },
  "shortTermDisability": {
    "typicalBenefit": "60–70% of pre-disability salary",
    "waitingPeriod": "1–2 weeks typically",
    "maxDuration": "3–6 months typically",
    "taxability": {
      "employerPaid100pct": "100% taxable as ordinary income. W-2 issued.",
      "employeePaidAfterTax": "100% tax-free.",
      "employeePaidPreTax": "100% taxable (treated same as employer-paid).",
      "splitEmployerEmployee": "Taxable proportional to employer's share.",
      "individualPolicy": "100% tax-free if premiums paid with after-tax dollars."
    },
    "note": "No SE tax on disability benefits regardless of taxability."
  },
  "longTermDisability": {
    "typicalBenefit": "60% of pre-disability salary (gross) or 60–70% of after-tax salary (individual policies)",
    "monthlyBenefitCap": "Typically $5,000–$15,000/month",
    "taxability": "Same rules as STD. Employer-paid = taxable. Employee after-tax = tax-free.",
    "ssdiBenefitOffset": "Most employer LTD policies offset benefits by SSDI amount received. Net LTD check = gross LTD - SSDI.",
    "taxOnOffsetNote": "IRS taxes full gross LTD benefit (before SSDI offset reduction). You pay taxes on money your insurer kept.",
    "openEnrollmentTip": "Electing to pay LTD premiums with after-tax dollars makes all future benefits tax-free. Costs slightly more now, saves significantly if disability occurs."
  },
  "rentalIncome": {
    "scheduleC_if": "You provide substantial services (hotels, B&Bs, short-term with daily cleaning/meals)",
    "scheduleE_if": "Simple rent — no substantial services",
    "augustaRuleExclusion": "Renting personal home 14 days or fewer — income fully excluded from gross income",
    "vacancyVsOccupancy": "Mixed-use (personal + rental) requires prorating deductions by days used",
    "deductions": [
      "Mortgage interest (rental portion)",
      "Property taxes (rental portion)",
      "Depreciation (27.5 years residential)",
      "Repairs and maintenance",
      "Property management fees",
      "Insurance",
      "Advertising"
    ],
    "passiveLossLimit": 25000,
    "passiveLossPhaseout": {
      "start": 100000,
      "end": 150000
    },
    "realEstateProfessional": "750+ hours/year in real estate and more hours in RE than any other profession — losses become non-passive, deductible against all income."
  },
  "kIncome": {
    "taxForm": "Schedule K-1",
    "types": [
      "Partnership (Form 1065)",
      "S Corporation (Form 1120-S)",
      "Trust/Estate (Form 1041)"
    ],
    "seTaxApplies": "General partners and LLC members: SE tax on their distributive share. Limited partners and S corp shareholders: generally no SE tax on K-1 distributions (wages separate).",
    "note": "K-1 income is not subject to withholding. Quarterly estimated taxes typically required."
  },
  "cryptoIncome": {
    "miningIncome": "Schedule C — ordinary income + SE tax at fair market value on date received",
    "stakingIncome": "Treated as ordinary income when received per IRS Rev. Rul. 2023-14",
    "cryptoSales": "Capital gain/loss. Short-term if held <1 year, long-term if >1 year",
    "nftSales": "Short-term or long-term capital gain. Creator NFT royalties = ordinary income",
    "form": "Form 8949 + Schedule D for sales. Schedule C for mining/staking income."
  }
};

export const equityCompensation = {
  "_schema": "All equity objects share: incomeEvent, taxEvent, form1099B_basisTrap, quarterlyNote",
  "_overview": "Equity compensation creates two taxable events: (1) ordinary income when shares vest or options are exercised, (2) capital gain/loss when shares are sold. Misunderstanding this two-layer structure is the most expensive equity tax mistake.",
  "rsu": {
    "label": "Restricted Stock Units",
    "taxEvent1_vesting": {
      "trigger": "Shares vest",
      "incomeType": "Ordinary income — W-2 wages",
      "amountTaxable": "FMV on vesting date × shares vested",
      "ficaApplies": true,
      "ficaSS_wageBase2026": 184500,
      "additionalMedicareTrigger_single": 200000,
      "additionalMedicareTrigger_mfj": 250000,
      "withholdingRate_supplemental_under1M": 0.22,
      "withholdingRate_supplemental_over1M": 0.37,
      "withholdingRisk": "22% under-withholds for anyone in 32%+ bracket. Gap = (marginal_rate - 0.22) x RSU_income. Fix via increased W-4 withholding or quarterly payments.",
      "form": "W-2 Box 1"
    },
    "taxEvent2_sale": {
      "costBasis": "FMV at vesting (already reported as W-2 income)",
      "shortTerm": "Sold within 1 year of vesting → ordinary income rates",
      "longTerm": "Sold more than 1 year after vesting → LTCG rates 0/15/20%",
      "form1099B_basisTrap": "Broker may report $0 or purchase price instead of FMV at vesting. Adjust on Form 8949 to avoid double taxation.",
      "form": "Form 1099-B → Form 8949 → Schedule D"
    },
    "quarterlyRequired": "If withholding gap > $1,000 after W-4 optimization",
    "seoKeywords": [
      "RSU tax calculator 2026",
      "restricted stock unit tax calculator",
      "RSU withholding gap calculator"
    ]
  },
  "iso": {
    "label": "Incentive Stock Options",
    "taxEvent1_exercise": {
      "regularTaxAtExercise": "None",
      "amtAtExercise": {
        "applies": true,
        "bargainElement": "FMV at exercise minus strike price = AMT preference item",
        "amtExemption2026_single": 90100,
        "amtExemption2026_mfj": 140200,
        "amtPhaseoutStart_single": 500000,
        "amtPhaseoutStart_mfj": 1000000,
        "amtRate_tier1": 0.26,
        "amtRate_tier2": 0.28,
        "amtRate_tier2_threshold": 244500,
        "amtTrap": "Large ISO exercise in single year can trigger AMT even without selling shares. Strategy: exercise in tranches across multiple years to stay below AMT exemption phaseout.",
        "amtCreditCarryforward": "AMT paid generates Form 8801 credit to offset future regular tax"
      },
      "form": "Form 3921 (employer reports). No W-2."
    },
    "taxEvent2_sale": {
      "qualifyingDisposition": {
        "holdingFromExercise": "More than 1 year",
        "holdingFromGrant": "More than 2 years",
        "bothRequired": true,
        "taxTreatment": "Entire gain (sale price minus strike price) as LONG-TERM capital gain",
        "ordinaryIncome": 0,
        "californiaWarning": "California taxes ISO qualifying dispositions at ordinary income state rates — no preferential CA treatment"
      },
      "disqualifyingDisposition": {
        "trigger": "Either holding requirement not met",
        "ordinaryIncome": "Bargain element at exercise — added to W-2",
        "capitalGain": "Sale price minus FMV at exercise — STCG or LTCG depending on holding from exercise to sale",
        "basisTrap": "Verify Form 1099-B basis on Form 8949"
      }
    },
    "annualLimit_isoVsNso": {
      "maxExercisablePerYear_iso": 100000,
      "note": "Aggregate FMV at grant date exceeding $100,000 exercisable in one year — excess treated as NSOs"
    },
    "quarterlyRequired": "If projected AMT liability exceeds withholding by more than $1,000",
    "seoKeywords": [
      "ISO stock option tax calculator 2026",
      "incentive stock option AMT calculator",
      "ISO qualifying disposition LTCG calculator"
    ]
  },
  "nso": {
    "label": "Non-Qualified Stock Options",
    "taxEvent1_exercise": {
      "trigger": "Options exercised",
      "incomeType": "Ordinary income on spread",
      "spread": "FMV at exercise minus strike price",
      "ficaApplies_employee": true,
      "ficaApplies_contractor": "SE tax on spread",
      "withholding_employee": "Employer withholds from payroll",
      "withholding_contractor": "Must pay via quarterly estimated taxes",
      "form_employee": "W-2 Box 1",
      "form_contractor": "1099-NEC",
      "cashNeeded": "Tax owed at exercise even if shares not sold. Cashless same-day sale covers obligation but triggers immediate sale."
    },
    "taxEvent2_sale": {
      "costBasis": "FMV at exercise",
      "shortTerm": "Sold within 1 year of exercise",
      "longTerm": "Sold more than 1 year after exercise",
      "basisTrap": "1099-B often shows wrong basis — adjust on Form 8949"
    },
    "quarterlyRequired": "Contractors always. Employees if withholding insufficient.",
    "seoKeywords": [
      "NSO tax calculator",
      "non-qualified stock option exercise tax",
      "NSO contractor 1099 taxes"
    ]
  },
  "espp": {
    "label": "Employee Stock Purchase Plan (Section 423 Qualified)",
    "annualPurchaseLimit": 25000,
    "maxDiscount": 0.15,
    "ficaExempt_qualified423": true,
    "ficaNote": "Section 423 qualified ESPP shares: NO FICA on either qualifying or disqualifying dispositions. Non-qualified ESPPs ARE subject to FICA at purchase.",
    "holdingRequirements": {
      "qualifyingDisposition": {
        "fromOfferingDate": "More than 2 years",
        "fromPurchaseDate": "More than 1 year",
        "bothRequired": true
      },
      "disqualifyingDisposition": "Fails either requirement"
    },
    "qualifyingDispositionTax": {
      "ordinaryIncome": "LESSER of: (a) 15% x FMV at offering date, or (b) actual gain (sale price minus purchase price)",
      "ltcg": "Remaining gain above ordinary income portion",
      "withholdingNote": "Qualifying disposition ordinary income NOT subject to federal withholding. Must pay via estimated taxes or W-4 adjustment.",
      "basisAdjusted": "Purchase price + ordinary income per share"
    },
    "disqualifyingDispositionTax": {
      "ordinaryIncome": "FMV at purchase date minus purchase price (full spread on purchase date)",
      "capitalGain": "Sale price minus FMV at purchase date",
      "capitalGainType": "STCG if held under 1 year from purchase; LTCG if over 1 year",
      "form": "W-2 (employer adds ordinary income); 1099-B for proceeds"
    },
    "basisTrap": {
      "description": "Broker 1099-B reports purchase price as basis — not adjusted basis. Adjusted basis = purchase price + ordinary income already on W-2. Failing to adjust = paying tax twice.",
      "form8949Code": "Adjust Column E with correct adjusted basis"
    },
    "form3922": "Employer files Form 3922 at transfer. Use to verify offering date FMV, purchase date FMV, and purchase price.",
    "quarterlyRequired": "For qualifying dispositions where ordinary income not withheld",
    "seoKeywords": [
      "ESPP tax calculator 2026",
      "ESPP qualifying disposition tax calculator",
      "ESPP disqualifying disposition calculator",
      "Section 423 ESPP basis calculator"
    ]
  },
  "qsbs": {
    "label": "Qualified Small Business Stock (Section 1202)",
    "overview": "Founders and early investors in qualifying C corps can exclude up to 100% of capital gains. Most powerful wealth-building provision in the tax code for startup equity.",
    "obbbaChanges": {
      "effectiveDate": "Stock issued after July 4, 2025",
      "exclusionLimit_new": 15000000,
      "exclusionLimit_old": 10000000,
      "inflationIndexedFrom": 2027,
      "tieredHolding_newStock": {
        "3_years": 0.5,
        "4_years": 0.75,
        "5_years_plus": 1
      },
      "priorStock_5yearRequired": true
    },
    "exclusionCapCalc": "Greater of ($15M post-July-2025 stock / $10M pre-July-2025 stock) OR (10 x adjusted basis). Use higher.",
    "amtTreatment": "Post-Sept 27, 2010 QSBS: no AMT preference. Full exclusion from AMT, NIIT, and regular capital gains tax.",
    "niitTreatment": "Excluded gain NOT subject to 3.8% NIIT.",
    "qualifyingRequirements": [
      "Original issuance from domestic C corporation",
      "Gross assets under $50M at time of issuance",
      "Qualifying trade or business (excludes professional services, finance, hospitality, farming, mining)",
      "Acquired for cash, property, or services — not purchased from existing shareholders",
      "Held for required period"
    ],
    "stateConformity": {
      "nonConforming_fullTax": [
        "CA",
        "AL",
        "MS",
        "PA"
      ],
      "partialConformity": [
        "HI — 50% exclusion only"
      ],
      "note": "California taxes QSBS gains at full state rate (up to 13.3%) even when 100% excluded federally."
    },
    "qsbsStacking": "Gifting QSBS to family members before sale multiplies the per-person $15M exclusion cap. Each recipient (spouse, children, trusts) gets own cap.",
    "section1045Rollover": "If QSBS sold before holding period: defer gain by reinvesting in new QSBS within 60 days.",
    "quarterlyRequired": "State estimated tax in non-conforming states on excluded gain. Federal: no quarterly on excluded portion.",
    "seoKeywords": [
      "QSBS tax calculator 2026",
      "Section 1202 exclusion calculator",
      "startup equity QSBS calculator",
      "founder stock tax calculator"
    ]
  },
  "phantomStock_SAR": {
    "label": "Phantom Stock and Stock Appreciation Rights",
    "taxTreatment": "Ordinary income when paid or settled — no LTCG treatment",
    "ficaApplies": true,
    "form_employee": "W-2",
    "form_contractor": "1099-NEC",
    "note": "Common in S corps (which cannot have two stock classes) and LLCs. Tax treatment mirrors a cash bonus.",
    "seoKeywords": [
      "phantom stock tax calculator",
      "SAR stock appreciation rights taxes"
    ]
  },
  "form1099B_basisReconciliation": {
    "_purpose": "The #1 equity tax filing error: paying tax twice due to under-reported cost basis on Form 1099-B",
    "affectedTypes": [
      "RSU",
      "NSO exercise",
      "ISO disqualifying disposition",
      "ESPP any disposition"
    ],
    "problem": "Broker 1099-B shows $0 or purchase price as basis — not the adjusted basis that includes income already on W-2",
    "rsuAdjustment": "Correct basis = FMV at vesting date. If 1099-B shows $0, enter FMV at vesting in Form 8949 Column E.",
    "esppQualifyingAdjustment": "Correct basis = purchase price + ordinary income per share already on W-2",
    "esppDisqualifyingAdjustment": "Correct basis = FMV at purchase date",
    "isoDisqualifyingAdjustment": "Correct basis = FMV at exercise date (spread already taxed as W-2)",
    "form8949Codes": "Code B (STCG with 1099-B) or Code E (LTCG with 1099-B), then correct in Column E",
    "irsCP2000Risk": "Failing to adjust basis is the most common cause of IRS CP2000 notices for equity compensation",
    "seoKeywords": [
      "RSU adjusted cost basis calculator",
      "ESPP Form 8949 basis adjustment",
      "stock compensation double tax calculator"
    ]
  },
  "multiStateAllocation": {
    "note": "Employees working in multiple states during vesting period must allocate equity income by state",
    "rsuMethod": "Days worked in each state / total days in vesting period x RSU income = each state's allocation",
    "isoNsoMethod": "Same proration applied to ordinary income at exercise",
    "remoteWorkTrap": "California employee who moved to Texas before vesting may still owe CA tax on CA-period portion",
    "aggressiveSourceingStates": [
      "CA",
      "NY",
      "MA"
    ],
    "seoKeywords": [
      "RSU multi-state tax",
      "equity compensation state allocation",
      "California RSU taxes remote work"
    ]
  }
};

export const entityTypes = {
  "soleProprietorship": {
    "taxForm": "Schedule C (Form 1040)",
    "seTaxApplies": true,
    "passThrough": true,
    "qbiEligible": true,
    "ownerSalaryRequired": false,
    "setup": "None required. Auto-created by doing business.",
    "annualCost": 0,
    "bestFor": "Net profit under $60,000. Testing a business idea. Very low compliance burden.",
    "drawback": "Highest effective tax rate. No liability protection."
  },
  "singleMemberLLC": {
    "taxForm": "Schedule C (default, disregarded entity)",
    "seTaxApplies": true,
    "passThrough": true,
    "qbiEligible": true,
    "canElectSCorp": true,
    "canElectCCorp": true,
    "setup": "File Articles of Organization with state. EIN recommended.",
    "annualCost": "50–300 (state annual report/franchise fee)",
    "bestFor": "Sole proprietor wanting liability protection. Same tax as sole prop until election.",
    "note": "Disregarded for federal tax but treated as separate legal entity for liability."
  },
  "multiMemberLLC": {
    "taxForm": "Form 1065 + Schedule K-1 to each member",
    "seTaxApplies": "On each member's distributive share (general partners)",
    "passThrough": true,
    "qbiEligible": true,
    "setup": "Articles of Organization + Operating Agreement required",
    "annualCost": "200–800",
    "bestFor": "Two or more owners. Flexible profit/loss allocation in operating agreement."
  },
  "llcElectingScorp": {
    "taxForm": "Form 1120-S + Schedule K-1",
    "seTaxApplies": "Only on W-2 salary, not distributions",
    "passThrough": true,
    "qbiEligible": true,
    "ownerSalaryRequired": true,
    "electionForm": "Form 2553 (file by March 15 for current year, or within 75 days of formation)",
    "setup": "Form LLC + file Form 2553",
    "annualCost": "1500–4000 (payroll processing, accountant, state fees)",
    "breakEvenNetProfit": 60000,
    "savingsAt100k": "approx $5,000–$8,000 vs sole prop",
    "savingsAt200k": "approx $12,000–$18,000 vs sole prop",
    "bestFor": "Net profit $60,000–$500,000. Single-owner service businesses.",
    "sCorpSalarySweetSpot": "35–45% of net profit as salary. Lower salary = more QBI + less FICA, but IRS audit risk if too low.",
    "complianceItems": [
      "Payroll (run actual payroll, not owner draws)",
      "W-2 to yourself",
      "Form 1120-S",
      "State S corp tax",
      "Accountable plan for reimbursements",
      "Separate business bank account"
    ]
  },
  "sCorporation": {
    "taxForm": "Form 1120-S + Schedule K-1",
    "seTaxApplies": "Only on W-2 salary",
    "passThrough": true,
    "qbiEligible": true,
    "ownerSalaryRequired": true,
    "note": "Same tax treatment as LLC electing S corp. Different formation path (incorporate first, then elect S corp status).",
    "maxShareholders": 100,
    "eligibleShareholders": "US citizens/residents only. No corporate shareholders."
  },
  "cCorporation": {
    "taxForm": "Form 1120",
    "corporateTaxRate": 0.21,
    "passThrough": false,
    "qbiEligible": false,
    "doubleTaxation": "Corp pays 21% on profits. Dividends paid to shareholders taxed again at 0–20% qualified dividend rate.",
    "bestFor": "VC-backed startups, high retained earnings, benefits-heavy compensation, stock options (ISOs)",
    "ownerCompensationOptions": [
      "W-2 salary (deductible to corp)",
      "Fringe benefits (deductible to corp, tax-free to employee)",
      "Qualified dividends (after corp tax)",
      "Deferred compensation"
    ],
    "advantages": [
      "Fringe benefits (health, disability, life) deductible and tax-free to owner",
      "Retained earnings taxed at only 21%",
      "ISO stock options",
      "Investor/VC standard"
    ],
    "disadvantages": [
      "Double taxation on distributions",
      "21% corporate rate on all profits (even if not needed personally)",
      "More complex compliance"
    ]
  },
  "delawareCCorp": {
    "extends": "cCorporation",
    "incorporationState": "Delaware",
    "corporateTaxRate_delaware": 0,
    "note": "Delaware C corps pay federal 21% corporate tax. No Delaware income tax on out-of-state income.",
    "franchiseTax": {
      "source": "corp.delaware.gov (confirmed)",
      "filing_deadline": "March 1 each year",
      "annual_report_fee_nonexempt": 50,
      "annual_report_fee_exempt": 25,
      "late_penalty": 200,
      "late_interest_monthly": 0.015,
      "authorizedSharesMethod": {
        "minimum": 175,
        "maximum_standard": 200000,
        "maximum_largeCorporateFiler": 250000,
        "schedule": {
          "5000_or_fewer_shares": 175,
          "5001_to_10000_shares": 250,
          "each_additional_10000_shares": 85,
          "note": "e.g. 10,005 shares = $335 ($250 + $85). 100,000 shares = $1,015."
        },
        "defaultMethod": true,
        "note": "Default method — Delaware bills this amount unless you request the Assumed Par Value method. Most startups with millions of authorized shares OVERPAY using this method."
      },
      "assumedParValueMethod": {
        "minimum": 400,
        "ratePerMillionGrossAssets": 400,
        "maximum_standard": 200000,
        "maximum_largeCorporateFiler": 250000,
        "requiredInputs": [
          "total issued shares (including treasury)",
          "total gross assets from Form 1120 Schedule L"
        ],
        "note": "Almost always lower for startups with many authorized shares but modest assets. Must request this method explicitly. $400/million of gross assets, minimum $400.",
        "example": "Company with $2M gross assets and 10M authorized shares: $400 x 2 = $800 tax vs. $85,000+ under Authorized Shares Method."
      },
      "quarterlyEstimatedPayments": {
        "threshold": 5000,
        "schedule": {
          "june1": 0.4,
          "sept1": 0.2,
          "dec1": 0.2,
          "march1_remainder": 0.2
        },
        "note": "Corporations owing $5,000+ must pay estimated taxes quarterly."
      },
      "taxSavingsTip": "Always calculate using BOTH methods and submit the lower amount. The Assumed Par Value Method typically saves startups with many authorized shares $10,000–$80,000+ per year vs. the default Authorized Shares Method.",
      "_correctionNote": "Confirmed June 2026 directly from corp.delaware.gov. Previous entry had $175 minimum only — now includes complete fee schedule, Assumed Par Value minimum ($400), filing fee ($50), late penalty ($200 + 1.5%/mo), Large Corporate Filer cap ($250,000)."
    },
    "registeredAgentCostPerYear": "50–300",
    "courtOfChancery": true,
    "vcFriendly": true,
    "bestFor": "Raising VC funding, IPO path, companies with many employees needing stock options",
    "notBestFor": "Solo bootstrapped founders, small businesses, privacy-conscious founders"
  },
  "wyomingLLC": {
    "stateTaxRate": 0,
    "franchiseTax": 0,
    "annualReportFee": 60,
    "passThrough": true,
    "anonymousOwnership": true,
    "registeredAgentCostPerYear": "25–150",
    "note": "Wyoming does not require member names to be public. Strong charging order protection.",
    "bestFor": "Privacy, low cost, bootstrapped founders wanting C corp or LLC with no franchise tax",
    "foreignQualificationNote": "If operating in another state, must foreign qualify and pay that state's fees and taxes too."
  },
  "wyomingCCorp": {
    "extends": "cCorporation",
    "incorporationState": "Wyoming",
    "corporateTaxRate_wyoming": 0,
    "franchiseTax": 0,
    "annualMaintenanceCost": "60–500",
    "anonymousOwnership": true,
    "vcFriendly": false,
    "note": "Most VCs require Delaware C Corp. Wyoming C Corp is not standard for institutional investors.",
    "bestFor": "Bootstrapped founders wanting C corp structure with max privacy and minimum cost"
  },
  "professionalLLC": {
    "taxForm": "Same as LLC (Schedule C or 1065)",
    "passThrough": true,
    "note": "Required in some states for licensed professionals (doctors, lawyers, CPAs, engineers). Same tax treatment as regular LLC.",
    "states": "Requirements vary by state and profession"
  },
  "husbandWifeQualifiedJointVenture": {
    "taxForm": "Two separate Schedule Cs (one per spouse)",
    "passThrough": true,
    "seTaxApplies": true,
    "qbiEligible": true,
    "note": "Married couples operating a business together can elect QJV status to avoid filing Form 1065 as a partnership. Each spouse files their own Schedule C for their ownership share. Both build individual Social Security credits. No K-1 required.",
    "requirements": [
      "Only spouses — no other partners",
      "Both must materially participate in the business",
      "Must file MFJ (Married Filing Jointly)",
      "Business must NOT be incorporated or organized as a state-registered LLC (see llcRestriction below)",
      "Election is made by filing two separate Schedule Cs — no formal IRS form required"
    ],
    "llcRestriction": {
      "rule": "If the couple has formed a state-registered LLC, QJV status is ONLY available if they reside in a community property state. In all other states, a spousal LLC must file as a partnership (Form 1065) or elect S corp / C corp status.",
      "communityPropertyStates": [
        "AZ",
        "CA",
        "ID",
        "LA",
        "NM",
        "NV",
        "TX",
        "WA",
        "WI"
      ],
      "communityPropertyNote": "In community property states, a husband-wife LLC that is wholly owned by the spouses may be treated as a disregarded entity (two-owner QJV) for federal tax purposes under Rev. Proc. 2002-69. This is a special IRS accommodation for community property law states only.",
      "nonCommunityPropertyWarning": "In the 41 non-community-property states (and DC), a registered husband-wife LLC cannot use QJV treatment. The LLC must file Form 1065 as a multi-member LLC partnership, OR elect to be taxed as an S corp (Form 2553) or C corp. Attempting QJV on a registered LLC in a non-CP state is a filing error.",
      "unregisteredBusinessNote": "If the couple operates as a general partnership WITHOUT forming a state-registered LLC or corporation, QJV election is available in ALL 50 states regardless of community property status."
    },
    "stateOverlayValidation": {
      "trigger": "When user selects husbandWifeQualifiedJointVenture AND has indicated they formed an LLC",
      "checkField": "user.state",
      "communityPropertyStates": [
        "AZ",
        "CA",
        "ID",
        "LA",
        "NM",
        "NV",
        "TX",
        "WA",
        "WI"
      ],
      "ifCommunityPropertyState": {
        "qjvAllowed": true,
        "uiMessage": "Because you are in a community property state, your husband-wife LLC may qualify for QJV treatment under Rev. Proc. 2002-69. Each spouse files a separate Schedule C."
      },
      "ifNonCommunityPropertyState": {
        "qjvAllowed": false,
        "uiMessage": "Warning: You have indicated you formed an LLC. In {state}, which is not a community property state, a husband-wife LLC cannot use Qualified Joint Venture treatment. Your LLC must file as a partnership (Form 1065) or elect S Corp status. Consider consulting a CPA.",
        "redirectSuggestion": "multiMemberLLC or llcElectingScorp"
      },
      "ifNoLLCFormed": {
        "qjvAllowed": true,
        "uiMessage": "Because your business is not a registered LLC or corporation, you can elect QJV treatment in any state. Each spouse reports their share on a separate Schedule C."
      }
    },
    "socialSecurityBenefit": "Each spouse earns individual Social Security credits on their respective Schedule C income. This is a significant long-term retirement planning advantage over a single-owner Schedule C where only one spouse builds credits.",
    "incomeAllocationNote": "Spouses allocate income and deductions based on their actual ownership percentage or participation share. The split does not have to be 50/50 but must reflect actual contribution. Document the agreed allocation in writing.",
    "comparisonToPartnership": {
      "qjvAdvantages": [
        "No Form 1065 required",
        "No K-1 distribution",
        "Simpler filing",
        "Both spouses build SS credits"
      ],
      "partnershipAdvantages": [
        "More flexible profit/loss allocation",
        "Can have special allocations",
        "Required if LLC registered in non-CP state"
      ]
    }
  },
  "generalPartnership": {
    "taxForm": "Form 1065 + K-1",
    "seTaxApplies": true,
    "note": "Each general partner pays SE tax on their distributive share. Unlimited liability — rarely advisable without LLC protection."
  },
  "sCorpCCorp": {
    "taxForm": "Form 1120 then Form 1120-S (if S election after C corp formation)",
    "note": "S Corp election filed after C corp incorporation. Most commonly used via LLC + Form 2553 today."
  },
  "scheduleE": {
    "taxForm": "Schedule E (Form 1040) — Part I",
    "seTaxApplies": false,
    "passiveLossRules": true,
    "note": "Used for rental income where NO substantial services are provided to tenants. Passive activity loss rules limit ability to deduct losses against non-passive income unless real estate professional."
  },
  "scheduleF": {
    "taxForm": "Schedule F (Form 1040)",
    "seTaxApplies": true,
    "note": "Farm income and expenses. Different deduction rules from Schedule C. Unique items: livestock, crop insurance, soil conservation, farm equipment depreciation."
  },
  "clergy": {
    "taxForm": "Schedule SE (unique rules)",
    "housingAllowance": "Tax-free if designated in advance by employing church. Excluded from income but included in SE tax base.",
    "seTaxApplies": true,
    "canOptOut": "Form 4361 — irrevocable opt-out from SE tax on ministerial earnings if opposed on religious grounds",
    "note": "Ministers may be employees for income tax but self-employed for SE tax. Complex dual status."
  },
  "householdEmployer": {
    "taxForm": "Schedule H (Form 1040)",
    "threshold2026": 2800,
    "ficaRate": 0.153,
    "note": "If you pay a nanny, housekeeper, or household worker $2,800+ in 2026, you are a household employer. You owe employer FICA + may need to withhold employee FICA and federal income tax. Nanny Tax."
  },
  "limitedPartnership": {
    "taxForm": "Form 1065 + Schedule K-1",
    "seTaxApplies": "General partners only. Limited partners generally NOT subject to SE tax on their distributive share.",
    "structure": "1+ general partners (unlimited liability, manage business) + 1+ limited partners (liability limited to investment, passive role)",
    "bestFor": "Real estate investment funds, private equity, film production partnerships",
    "keyTaxPoint": "Limited partner K-1 income goes on Schedule E (passive) — no SE tax. General partner income goes on Schedule E but IS subject to SE tax.",
    "note": "Limited partners who actively participate in management risk being reclassified as general partners by IRS."
  },
  "professionalCorporation": {
    "taxForm": "Form 1120 (C corp election) or Form 1120-S (S corp election)",
    "stateRequirement": "Required in many states for licensed professionals: doctors, dentists, attorneys, CPAs, architects, engineers",
    "personalHoldingCompanyTax": "PC taxed as C corp faces potential personal holding company tax (20%) if too much passive income retained",
    "bestFor": "Licensed professionals who need liability protection and want employee benefits structure",
    "corporateTaxNote": "PC can elect S corp status if shareholders are eligible. Most medical/dental PCs use S corp election.",
    "seoKeywords": [
      "professional corporation tax calculator",
      "PC vs PLLC taxes",
      "medical professional corporation taxes"
    ]
  },
  "familyLLC": {
    "taxForm": "Form 1065 (partnership) or Schedule C if disregarded",
    "seTaxApplies": "Managing member typically. Limited member children/family: generally no SE tax on passive distributions.",
    "purpose": "Estate planning tool. Transfer ownership interests to family members at reduced valuations (valuation discounts for lack of control/marketability).",
    "incomeShifting": "Distributions to lower-bracket family members taxed at their lower rate. Kiddie tax (unearned income of children) applies to children under 19 (or full-time students under 24).",
    "kiddie税Note": "Kiddie tax: child's unearned income (including LLC distributions) taxed at parents' rate if under age 19. Calculator must model this.",
    "note": "Must have legitimate business purpose beyond tax avoidance. Charging order protection for creditors.",
    "seoKeywords": [
      "family LLC tax calculator",
      "family limited partnership taxes",
      "income shifting family business taxes"
    ]
  },
  "holdingCompany": {
    "taxForm": "Depends on entity type (LLC = Schedule C/1065; Corp = 1120)",
    "structure": "Parent entity owns one or more subsidiary/operating companies",
    "taxAdvantages": [
      "Liability isolation between subsidiaries",
      "Centralized management",
      "Can facilitate tax-free intercompany transfers"
    ],
    "commonStructures": [
      {
        "name": "Wyoming LLC Holding + Operating LLC",
        "note": "Privacy + liability protection. No franchise tax."
      },
      {
        "name": "Delaware C Corp Holding + Operating LLCs",
        "note": "Standard for VC-backed companies with multiple product lines."
      },
      {
        "name": "Management Company + Operating Company",
        "note": "Mgmt company bills operating company for services. Common tax planning structure."
      }
    ],
    "managementCompanyNote": "Management company (owned by operators) charges operating company a management fee. Operating company deducts fee. Management company income distributed to owners. SE tax applies on management fee income.",
    "seoKeywords": [
      "holding company tax calculator",
      "holding company vs operating company taxes",
      "management company structure taxes"
    ]
  },
  "realEstateHoldingLLC": {
    "taxForm": "Schedule E (single property, SMLLC disregarded) or Form 1065 (partnership)",
    "seTaxApplies": false,
    "purpose": "Hold real estate assets. Separate entity per property recommended for liability isolation.",
    "keyBenefit": "Liability shield: lawsuit from one property cannot reach assets in other LLCs or personal assets if properly maintained.",
    "mortgageNote": "Due-on-sale clause: some lenders accelerate loan if property transferred to LLC. Consult attorney. Portfolio lenders more flexible.",
    "deductions": "Same as landlord Schedule E: depreciation, mortgage interest, taxes, insurance, maintenance",
    "series_llc_alternative": "Some states allow series LLC — one LLC with segregated 'series' for each property. Not recognized in all states.",
    "seoKeywords": [
      "real estate holding LLC taxes",
      "rental property LLC tax calculator",
      "LLC for rental property tax benefits"
    ]
  },
  "seriesLLC": {
    "taxForm": "Varies by state. IRS has not issued definitive guidance on series LLC federal tax treatment.",
    "availability": "Available in: Delaware, Texas, Illinois, Nevada, Utah, Iowa, Kansas, Missouri, Montana, North Dakota, Oklahoma, Tennessee, Virginia, Wisconsin",
    "concept": "One master LLC with 'series' (cells) that are legally separate from each other. Each series can own property, have members, and have separate liability.",
    "irsUncertainty": "IRS has not fully clarified whether each series is a separate tax entity. Draft regulations pending since 2010. Most practitioners treat each series as separate entity for tax purposes.",
    "risk": "Not recognized in all states. Courts in non-series states may not honor inter-series liability protection.",
    "bestFor": "Real estate investors in series-friendly states who want multiple properties with liability isolation but only one annual filing.",
    "seoKeywords": [
      "series LLC tax calculator",
      "series LLC vs multiple LLCs taxes",
      "series LLC real estate"
    ]
  },
  "statutoryEmployee": {
    "taxForm": "W-2 (special boxes checked)",
    "definition": "Worker who is not a common-law employee but is treated as an employee for FICA purposes by statute. Receives W-2 with Box 13 'Statutory Employee' checked.",
    "categories": [
      "Drivers who distribute food/beverages, pick up/deliver laundry, or distribute meat/produce",
      "Full-time life insurance sales agents",
      "Individuals who work at home on materials supplied by employer",
      "Full-time traveling or city salespeople"
    ],
    "taxTreatment": {
      "ficaWithheld": "Yes — on W-2 like regular employees",
      "incomeTaxWithheld": "No — unless agreed to by worker",
      "businessDeductions": "Can deduct business expenses on Schedule C against statutory employee income (Box 1 of W-2)",
      "netResult": "Report income + deductions on Schedule C but SE tax already handled via FICA"
    },
    "seoKeywords": [
      "statutory employee tax calculator",
      "statutory employee vs independent contractor taxes",
      "life insurance agent tax W-2"
    ]
  }
};

export const filingStatuses = {
  "single": {
    "code": "S",
    "label": "Single",
    "standardDeduction": 16100
  },
  "mfj": {
    "code": "MFJ",
    "label": "Married Filing Jointly",
    "standardDeduction": 32200
  },
  "mfs": {
    "code": "MFS",
    "label": "Married Filing Separately",
    "standardDeduction": 16100,
    "note": "Rarely beneficial. Ineligible for QBI, EITC, education credits, ACA subsidy, most deductions."
  },
  "hoh": {
    "code": "HOH",
    "label": "Head of Household",
    "standardDeduction": 24150,
    "note": "Must be unmarried, paid >50% of household costs, and have qualifying person."
  },
  "qsw": {
    "code": "QSW",
    "label": "Qualifying Surviving Spouse",
    "standardDeduction": 32200,
    "note": "Use for 2 years after spouse's death if dependent child."
  }
};

export const quarterlyDates2026 = [
  {
    "q": 1,
    "incomePeriod": "2026-01-01/2026-03-31",
    "dueDate": "2026-04-15"
  },
  {
    "q": 2,
    "incomePeriod": "2026-04-01/2026-05-31",
    "dueDate": "2026-06-16"
  },
  {
    "q": 3,
    "incomePeriod": "2026-06-01/2026-08-31",
    "dueDate": "2026-09-15"
  },
  {
    "q": 4,
    "incomePeriod": "2026-09-01/2026-12-31",
    "dueDate": "2027-01-15"
  }
];
