/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * UI-facing projection of overrides/state-formation-2026.json. Provenance — sources, research notes, owner decisions, confidence — is deliberately stripped: it is the point of the source file and dead weight in a browser.
 */
export const formationFees = {
  "AL": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 200,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "No Secretary of State annual report; requirement repealed."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 200,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "No SOS annual report. Separate Alabama Business Privilege Tax with Dept of Revenue; fully exempt when computed tax is $100 or less for years beginning after 12/31/2023."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "AK": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 250,
      "foreignQualificationFee": 350,
      "annualReport": {
        "amount": 100,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial $100 domestic; $200 foreign. Free initial report after formation."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 250,
      "foreignQualificationFee": 350,
      "annualReport": {
        "amount": 100,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial $100 domestic; $200 foreign."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "AZ": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "Arizona LLCs file no annual report; corporations only."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 60,
      "foreignQualificationFee": 175,
      "annualReport": {
        "amount": 45,
        "frequency": "annual",
        "dueDate": null,
        "note": "For-profit corporation $45 regular, $80 expedited."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "AR": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 45,
      "foreignQualificationFee": 270,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": null,
        "note": "No separate report; flat $150 annual franchise tax report filed with SOS, plus $5 online processing."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 45,
      "foreignQualificationFee": 270,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": null,
        "note": "Stock corporation franchise tax minimum $150, scaling with outstanding capital stock; non-stock $300."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Stock corporation franchise tax scales with outstanding capital stock above a $150 minimum. The stored figure is the minimum.",
      "recheckIdenticalForeignFee": true
    }
  },
  "CA": {
    "grossReceiptsTax": {
      "applies": true,
      "rate": null,
      "threshold": 250000,
      "base": "gross_receipts",
      "note": "LLC fee on total California income, SEPARATE FROM AND IN ADDITION TO the $800: $0 under $250,000; $900 to $499,999; $2,500 to $999,999; $6,000 to $4,999,999; $11,790 at $5,000,000 or more. Tiered, so no single rate."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 70,
      "foreignQualificationFee": 70,
      "annualReport": {
        "amount": 20,
        "frequency": "biennial",
        "dueDate": "within 90 days of registration, then biennially by the end of the anniversary month",
        "note": "Statement of Information LLC-12, $20. FTB collects a $250 penalty for failure to file."
      },
      "annualTax": {
        "amount": 800,
        "note": "$800 annual LLC tax, due the 15th day of the 4th month, payable even with no activity until the LLC is cancelled. THE FIRST-YEAR EXEMPTION IS DEAD FOR 2026 — it covered only tax years 2021 to 2023."
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": "within 90 days of incorporation, then annually",
        "note": "Statement of Information SI-550: $20 filing plus $5 disclosure."
      },
      "annualTax": {
        "amount": 800,
        "note": "$800 minimum franchise tax for every corporation incorporated, registered OR DOING BUSINESS in California. Newly incorporated corporations are exempt in their first taxable year and that exemption IS still live in 2026 — unlike the LLC one."
      }
    }
  },
  "CO": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Periodic Report $25 online; $50 late penalty."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 50,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Periodic Report $25 online; $50 late penalty."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "CT": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 120,
      "foreignQualificationFee": 120,
      "annualReport": {
        "amount": 80,
        "frequency": "annual",
        "dueDate": null,
        "note": "Filed online 1 Jan to March 31; $80 domestic and foreign alike."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 250,
      "foreignQualificationFee": 385,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic stock corporation $150; FOREIGN stock corporation annual report is $435."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "DE": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "authorizedSharesMethod": {
          "upTo5000": 175,
          "upTo10000": 250,
          "additionalPer10000Shares": 85
        },
        "assumedParValueMethod": {
          "ratePerMillion": 400,
          "minimum": 400
        },
        "minimumTax": 175,
        "maximumTaxStandard": 200000,
        "maximumTaxLargeCorporateFiler": 250000,
        "largeCorporateFilerDefinition": "Listed on a national exchange AND consolidated annual gross revenues or assets of $750,000,000 or more.",
        "annualReportLatePenalty": 200,
        "lateInterestPerMonth": 0.015
      },
      "note": "Two methods. Delaware BILLS the authorized-shares method by default; the assumed par value method is usually far cheaper for a company with many authorized shares and modest assets, and must be elected."
    },
    "llc": {
      "formationFee": 110,
      "foreignQualificationFee": 200,
      "annualReport": {
        "amount": 0,
        "frequency": "none",
        "dueDate": null,
        "note": "Delaware does not require LLCs, LPs or GPs to file an annual report."
      },
      "annualTax": {
        "amount": 300,
        "note": "Flat $300 alternative-entity tax due on or before June 1, domestic and foreign alike, no proration. Late: $200 penalty plus 1.5% interest a month."
      }
    },
    "corp": {
      "formationFee": 109,
      "foreignQualificationFee": 245,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": "March 1",
        "note": "$50 non-exempt domestic, $25 exempt. FOREIGN corporations file a DIFFERENT report: $125 due June 30 with a $125 late penalty."
      },
      "annualTax": {
        "amount": null,
        "note": "Franchise tax computed separately, paid with the March 1 report. Minimum $175 authorized-shares method or $400 assumed par value method."
      },
      "feeVaries": true,
      "feeVariesNote": "Delaware incorporation fee is marked \"VARIES BASED ON STOCK\" on the official schedule. The stored $109 is the minimum, and $9 is added per extra page of county recording."
    }
  },
  "DC": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 99,
      "foreignQualificationFee": 220,
      "annualReport": {
        "amount": 300,
        "frequency": "biennial",
        "dueDate": null,
        "note": "BRA-25 biennial report $300 plus $100 late fee. First due April 1 of the year after registration."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 99,
      "foreignQualificationFee": 220,
      "annualReport": {
        "amount": 300,
        "frequency": "biennial",
        "dueDate": null,
        "note": "BRA-25 $300 biennially."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "DC incorporation is $99 for authorized capital to $100,000, then $550, $1,100 and $1,650 by tier. The stored figure is the minimum.",
      "recheckIdenticalForeignFee": true
    }
  },
  "FL": {
    "grossReceiptsTax": {
      "applies": false,
      "rate": null,
      "threshold": null,
      "base": "gross_receipts",
      "note": "No general gross receipts tax. Corporate income tax 5.5% on net income after a $50,000 exemption; S corporations paying federal tax on Form 1120S line 23c are subject to it."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 125,
      "foreignQualificationFee": 125,
      "annualReport": {
        "amount": 138.75,
        "frequency": "annual",
        "dueDate": "January 1 to May 1",
        "note": "$538.75 if received after May 1 — a $400 late fee. Administrative dissolution the fourth Friday of September."
      },
      "annualTax": {
        "amount": null,
        "note": "No entity-level annual tax; an LLC not electing corporate treatment is outside Florida corporate income tax."
      }
    },
    "corp": {
      "formationFee": 70,
      "foreignQualificationFee": 70,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": "January 1 to May 1",
        "note": "$550 if received after May 1."
      },
      "annualTax": {
        "amount": null,
        "note": "No flat annual tax; corporate income tax 5.5% of Florida net income after a $50,000 exemption."
      }
    }
  },
  "GA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 225,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual registration due 1 Jan to April 1; $5 online or $10 paper service charge on top."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 225,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Initial annual registration due within 90 days of incorporation."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "HI": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 50,
      "annualReport": {
        "amount": 15,
        "frequency": "annual",
        "dueDate": null,
        "note": "Flat $15, due in the quarter matching the registration anniversary."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 50,
      "foreignQualificationFee": 50,
      "annualReport": {
        "amount": 15,
        "frequency": "annual",
        "dueDate": null,
        "note": "Flat $15, domestic and foreign profit corporations alike."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "ID": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 0,
        "frequency": "annual",
        "dueDate": null,
        "note": "NO FEE if filed on time, but the report is mandatory — miss it and the entity is administratively dissolved."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 0,
        "frequency": "annual",
        "dueDate": null,
        "note": "No fee if filed on time."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "IL": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "applies": true,
        "rate": 0.0015,
        "minimumInitial": 25,
        "annualExemption": 10000
      },
      "note": "APPLIES. PA 102-0016 reversed the repeal in PA 101-0009. Rate 0.15% ($1.50 per $1,000 of paid-in capital allocated to Illinois); minimum initial $25. THE ANNUAL EXEMPTION IS $10,000 for 2025 and after, so $10,000 in 2026 — settled by the Commission on Government Forecasting and Accountability's Tax Handbook for Legislators 2026, page 33, which sets out the whole schedule: $30 exempt in 2020, $1,000 for 2021-23, $5,000 for 2024, $10,000 from 2025. Caveat carried forward: the handbook states the schedule but cites no Public Act for the increases above $1,000, and its only statutory citation is 805 ILCS 5/15.05 and following. Practical effect remains small — almost every business this tool serves owes $0."
    },
    "llc": {
      "formationFee": 150,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 75,
        "frequency": "annual",
        "dueDate": null,
        "note": "$100 late penalty after 60 days."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 150,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": null,
        "frequency": "annual",
        "dueDate": null,
        "note": "Base fee never established. The SoAR page exposes only a $50 expedited surcharge, not the fee itself, so this stays null."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Illinois incorporation is a MINIMUM total; it rises with paid-in capital. The foreign figure is likewise a minimum, from bca1315.pdf."
    }
  },
  "IN": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 125,
      "annualReport": {
        "amount": 32,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Business Entity Report every other year: $32 online, $50 paper."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 125,
      "annualReport": {
        "amount": 32,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Same biennial report."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "IA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 30,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial, odd years, due April 1: $30 online, $45 paper."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 50,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 60,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Profit corporations file in EVEN years, due April 1: $60."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "KS": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 85,
      "foreignQualificationFee": 115,
      "annualReport": {
        "amount": 90,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial information report $90 online, $110 paper."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 85,
      "foreignQualificationFee": 115,
      "annualReport": {
        "amount": 90,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Same."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "KY": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 40,
      "foreignQualificationFee": 90,
      "annualReport": {
        "amount": 15,
        "frequency": "annual",
        "dueDate": null,
        "note": "Due 1 Jan to June 30, $15."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 40,
      "foreignQualificationFee": 90,
      "annualReport": {
        "amount": 15,
        "frequency": "annual",
        "dueDate": null,
        "note": "Same."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "LA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 30,
        "frequency": "annual",
        "dueDate": null,
        "note": "$30; a domestic LLC Initial Report is filed with the Articles."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 75,
      "foreignQualificationFee": 125,
      "annualReport": {
        "amount": 30,
        "frequency": "annual",
        "dueDate": null,
        "note": "$30."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "ME": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 175,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 85,
        "frequency": "annual",
        "dueDate": null,
        "note": "MLLC-13, due June 1; $85 domestic, $150 foreign-qualified"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 145,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 85,
        "frequency": "annual",
        "dueDate": null,
        "note": "MBCA-13, due June 1; $85 domestic, $150 foreign"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "MD": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 300,
        "frequency": "annual",
        "dueDate": null,
        "note": "Form 1 Annual Report $300, due April 15"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 120,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 300,
        "frequency": "annual",
        "dueDate": null,
        "note": "Form 1 Annual Report $300"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Stored figure assumes aggregate par value at or under $100,000 and no more than 5,000 no-par shares; it is higher above either.",
      "recheckIdenticalForeignFee": true
    }
  },
  "MA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 500,
      "foreignQualificationFee": 500,
      "annualReport": {
        "amount": 500,
        "frequency": "annual",
        "dueDate": null,
        "note": "LLC annual report $500, anniversary of formation; same for foreign LLCs"
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 275,
      "foreignQualificationFee": 400,
      "annualReport": {
        "amount": 125,
        "frequency": "annual",
        "dueDate": null,
        "note": "$125, or $100 filed electronically; $150 if late"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Formation is $275 for up to 275,000 authorized shares, plus $100 for each additional 100,000. The stored figure is the minimum."
    }
  },
  "MI": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 50,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "LLC annual statement $25, due February 15; PLLC $75"
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 60,
      "foreignQualificationFee": 60,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Corp annual report $25, due May 15, escalating late penalties to $50"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Formation is $10 plus a $50 organization fee for the first 60,000 authorized shares, rising with share count. The stored figure is the minimum."
    }
  },
  "MN": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "capitalBased": false
      },
      "note": "No capital-based franchise tax. Minnesota's 'corporate franchise tax' IS an income tax — 9.8% flat — plus a minimum fee computed on property, payroll and sales apportionment. There is no Illinois-style exemption figure to store."
    },
    "llc": {
      "formationFee": 135,
      "foreignQualificationFee": 185,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 135,
      "foreignQualificationFee": 200,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "MS": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "capitalBased": true,
        "phasingOut": true,
        "repealedAfter": 2027,
        "rate": null,
        "exemption": null,
        "minimum": 25
      },
      "note": "APPLIES, phasing out, repealed after tax year 2027. The STRUCTURE and the phase-out are confirmed by the Department of Revenue. The 2026 RATE (reported as $0.50 per $1,000 of capital) and the $100,000 exemption are cited only to commercial tax sites, so both are stored NULL rather than asserted. Minimum franchise tax $25. Confirm the figures against the DOR corporate income tax instructions before relying on them."
    },
    "llc": {
      "formationFee": 50,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 50,
      "foreignQualificationFee": 500,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "MO": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "capitalBased": false,
        "repealed": true
      },
      "note": "REPEALED. The phase-out completed in 2016; there is no capital franchise tax in Missouri in 2026."
    },
    "llc": {
      "formationFee": null,
      "foreignQualificationFee": null,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 58,
      "foreignQualificationFee": 155,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "NOT $50. The $50 incorporation fee is joined by $3 for issuing the certificate and $5 for the Technology Trust Fund, so $58 is the real minimum to file. The $50 covers the first $30,000 of authorized shares under 351.065 RSMo, then rises $5 per additional $10,000 or fraction, with the $3 and $5 on top of whatever that comes to. Foreign qualification at $155 is FLAT — no share formula."
    }
  },
  "MT": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 35,
      "foreignQualificationFee": null,
      "annualReport": {
        "amount": 20,
        "frequency": "annual",
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "legacyLead": true
    },
    "corp": {
      "formationFee": null,
      "foreignQualificationFee": null,
      "annualReport": {
        "amount": null,
        "frequency": null,
        "dueDate": null,
        "note": null
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "NE": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial, odd years by Apr 1; $25 electronic / $30 written. Formation $100 online / $110 in-office plus $2 portal fee."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 26,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial occupation tax report, even years by Mar 1. NOT FLAT: set by paid-up capital schedule, $26 minimum to $23,990 maximum."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Biennial occupation tax report is set by a paid-up capital schedule, from $26 to $23,990. The stored figure is the minimum.",
      "recheckIdenticalForeignFee": true
    }
  },
  "NV": {
    "grossReceiptsTax": {
      "applies": true,
      "rate": null,
      "threshold": 4000000,
      "base": "gross_receipts",
      "note": "Commerce Tax on Nevada gross revenue above $4,000,000 per fiscal year. Businesses at or below the threshold are exempt from filing. The RATE VARIES BY NAICS CATEGORY, so no single rate is stored and the engine must compute null above the threshold."
    },
    "franchiseTax": {
      "structured": {
        "corpFormationFeeSchedule": {
          "basis": "value of total authorized shares",
          "min": 75,
          "maximum": 35000
        },
        "corpAnnualListSchedule": {
          "min": 150,
          "maximum": 11125
        },
        "noCorporateOrPersonalIncomeTax": true
      },
      "note": null
    },
    "llc": {
      "formationFee": 75,
      "foreignQualificationFee": 75,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": "last day of the anniversary month",
        "note": "Annual List of Managers/Managing Members, flat $150 domestic and foreign. An Initial List of the same $150 is ALSO due when articles are filed."
      },
      "annualTax": {
        "amount": 200,
        "note": "State Business License, $200 a year for non-corporations, paid to the Secretary of State with each list (NRS 76.100, 76.130)."
      },
      "oneTimeAtRegistration": {
        "amount": 150,
        "note": "Initial List of Managers/Managing Members, due when the articles are filed. Same amount as the annual list, so year one carries it twice.",
        "source": "NRS 86.263 (leg.state.nv.us)"
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 75,
      "foreignQualificationFee": 75,
      "annualReport": {
        "amount": 150,
        "frequency": "annual",
        "dueDate": "last day of the anniversary month",
        "note": "Annual List of Officers and Directors. $150 only if total authorized stock value is $75,000 or less, then rising to a maximum of $11,125. Initial List is flat $150."
      },
      "annualTax": {
        "amount": 500,
        "note": "State Business License, $500 a year for corporations (NRS 76.100, 76.130)."
      },
      "feeVaries": true,
      "feeVariesNote": "Nevada corporation formation and annual list fees both scale with the value of total authorized shares — formation from $75 to a $35,000 maximum, annual list from $150 to $11,125. Both stored figures are minimums.",
      "oneTimeAtRegistration": {
        "amount": 150,
        "note": "Initial List of Officers and Directors, a flat $150 regardless of share count, due when the articles are filed.",
        "source": "NRS 78.150 (leg.state.nv.us)"
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "NH": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 100,
        "frequency": "annual",
        "dueDate": null,
        "note": "Due April 1; $50 late fee; $2 electronic handling charge."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 100,
        "frequency": "annual",
        "dueDate": null,
        "note": "Due April 1; $50 late fee."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "NJ": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 75,
        "frequency": "annual",
        "dueDate": null,
        "note": "$75 for all for-profit entities, due end of anniversary month."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 75,
        "frequency": "annual",
        "dueDate": null,
        "note": "$75. Separate NJ Corporation Business Tax minimum, tiered by NJ gross receipts, NOT confirmed here."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "NM": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": "NOT ESTABLISHED. The claim that New Mexico has no capital-based franchise tax is probably right, but it is stored as unverified because the citation failed: every source offered for it pointed at MINNESOTA or at a commercial site's MISSISSIPPI page. Nothing supported the New Mexico claim. A plausible conclusion with the wrong citation is still unsourced."
    },
    "llc": {
      "formationFee": null,
      "foreignQualificationFee": null,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "New Mexico LLCs have NO annual or biennial report requirement; that obligation applies to corporations only."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": null,
      "foreignQualificationFee": null,
      "annualReport": {
        "amount": 25,
        "frequency": "biennial",
        "dueDate": null,
        "note": "$25 per first, biennial and supplemental report; $200 penalty if late."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "New Mexico corporation filing fees are share-based under NMSA 53-2-1 rather than flat. No figure is stored because none has been confirmed on a Secretary of State source."
    }
  },
  "NY": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 200,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 9,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial Statement $9, anniversary month."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 125,
      "foreignQualificationFee": 225,
      "annualReport": {
        "amount": 9,
        "frequency": "biennial",
        "dueDate": null,
        "note": "Biennial Statement $9. Separate annual NYS franchise tax filing."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "NC": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 125,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 200,
        "frequency": "annual",
        "dueDate": null,
        "note": "LLC annual report $200; $3 card or $2 ACH fee added online."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 125,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Corp annual report $25 paper, $18 online wizard."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "ND": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 135,
      "foreignQualificationFee": 135,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual report $50 domestic and foreign LLCs."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 145,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual report $25, same domestic and foreign."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "OH": {
    "grossReceiptsTax": {
      "applies": true,
      "rate": 0.0026,
      "threshold": 6000000,
      "base": "gross_receipts",
      "note": "Commercial Activity Tax. From tax year 2025: $6,000,000 exclusion, 0.26% above it. Registration required within 30 days of exceeding $6 million."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 99,
      "foreignQualificationFee": 99,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "Ohio requires NO annual or biennial report for LLCs. The statutory schedule lists periodic reports only for LLPs and professional associations."
      },
      "annualTax": {
        "amount": null,
        "note": "None."
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 125,
      "foreignQualificationFee": 99,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "No annual report for domestic or foreign for-profit corporations."
      },
      "annualTax": {
        "amount": null,
        "note": "None."
      },
      "feeVaries": true,
      "feeVariesNote": "Ohio incorporation is $0.10 per authorized share under ORC 111.16 with a floor, so it rises above the stored figure once authorized shares pass roughly 1,250. The stored figure is a minimum.",
      "recheckIdenticalForeignFee": true
    }
  },
  "OK": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 300,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual Certificate $25, anniversary date."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 50,
      "foreignQualificationFee": 300,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "No SOS annual certificate confirmed for corporations; franchise tax eliminated from tax year 2024."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Incorporation is 1/10 of 1% of total authorized capital, minimum $50. Foreign qualification is 1/10 of 1% of capital invested in Oklahoma, minimum $300. Both stored figures are minimums.",
      "recheckIdenticalForeignFee": true
    }
  },
  "OR": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 275,
      "annualReport": {
        "amount": 100,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic LLC renewal $100/yr; foreign LLC renewal $275/yr"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 275,
      "annualReport": {
        "amount": 100,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic business corp renewal $100/yr; foreign corp renewal $275/yr"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "PA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 125,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 7,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual Report replaced decennial report starting 2025; LLC deadline Sept 30"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 125,
      "foreignQualificationFee": 250,
      "annualReport": {
        "amount": 7,
        "frequency": "annual",
        "dueDate": null,
        "note": "Corporation deadline June 30; $0 for nonprofits"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "RI": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 150,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Plus $400 minimum annual tax to RI Division of Taxation regardless of profit"
      },
      "annualTax": {
        "amount": 400,
        "note": "Minimum annual tax, not prorated, owed regardless of profit"
      }
    },
    "corp": {
      "formationFee": 230,
      "foreignQualificationFee": 310,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Plus $400 minimum annual corporate tax"
      },
      "annualTax": {
        "amount": 400,
        "note": "Minimum annual corporate tax, not prorated"
      }
    }
  },
  "SC": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 110,
      "foreignQualificationFee": 110,
      "annualReport": {
        "amount": null,
        "frequency": "none",
        "dueDate": null,
        "note": "LLCs not taxed as corporations file no annual report and owe no license fee"
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 135,
      "foreignQualificationFee": 135,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Schedule D of SC corporate return; license fee 0.1% capital stock + $15, $25 minimum"
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Annual license fee is 0.1% of capital stock plus $15, with a $25 minimum. The stored figure is the minimum."
    }
  },
  "SD": {
    "grossReceiptsTax": {
      "applies": false,
      "rate": null,
      "threshold": null,
      "base": "gross_receipts",
      "note": "No corporate or personal income tax. The bank franchise tax reaches financial institutions only."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 150,
      "foreignQualificationFee": 750,
      "annualReport": {
        "amount": 55,
        "frequency": "annual",
        "dueDate": "first day of the anniversary month",
        "note": "$55 electronic, $70 paper. $50 late fee once delinquent, two months after the due date."
      },
      "annualTax": {
        "amount": null,
        "note": "None."
      }
    },
    "corp": {
      "formationFee": 150,
      "foreignQualificationFee": 750,
      "annualReport": {
        "amount": 55,
        "frequency": "annual",
        "dueDate": "first day of the anniversary month",
        "note": "$55 electronic, $70 paper."
      },
      "annualTax": {
        "amount": null,
        "note": "None."
      }
    }
  },
  "TN": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 300,
      "foreignQualificationFee": 300,
      "annualReport": {
        "amount": 300,
        "frequency": "annual",
        "dueDate": null,
        "note": "VARIES: $50 per member, $300 minimum, $3,000 maximum."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "LLC formation and foreign qualification are $50 per member, minimum $300, maximum $3,000. The stored figure is the minimum."
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 600,
      "annualReport": {
        "amount": 20,
        "frequency": "annual",
        "dueDate": null,
        "note": "Flat $20; extra $20 if the agent is changed on the report."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "TX": {
    "grossReceiptsTax": {
      "applies": true,
      "rate": 0.0075,
      "threshold": 2650000,
      "base": "margin",
      "note": "Report year 2026: no-tax-due threshold $2,650,000. Standard 0.75%, retail/wholesale 0.375%, EZ computation 0.331% under $20M revenue. A report is required even below the threshold."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 300,
      "foreignQualificationFee": 750,
      "annualReport": {
        "amount": 0,
        "frequency": "annual",
        "dueDate": "May 15",
        "note": "No SOS annual report. Comptroller requires an annual Public Information Report with the franchise report; no filing fee."
      },
      "annualTax": {
        "amount": null,
        "note": "Franchise (margin) tax, no flat minimum. $0 due at or below $2,650,000 annualized revenue for report year 2026, but the report must still be filed."
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 300,
      "foreignQualificationFee": 750,
      "annualReport": {
        "amount": 0,
        "frequency": "annual",
        "dueDate": "May 15",
        "note": "No SOS annual report; Public Information Report to the Comptroller, no fee."
      },
      "annualTax": {
        "amount": null,
        "note": "Same margin tax as LLCs."
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "UT": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 59,
      "foreignQualificationFee": 59,
      "annualReport": {
        "amount": 18,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual renewal $18 including a $5 portal surcharge; $10 late fee."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 59,
      "foreignQualificationFee": 59,
      "annualReport": {
        "amount": 18,
        "frequency": "annual",
        "dueDate": null,
        "note": "Annual renewal, same figures."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "VT": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 155,
      "foreignQualificationFee": 155,
      "annualReport": {
        "amount": 45,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic LLC $45; FOREIGN LLC annual report is $170."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 155,
      "foreignQualificationFee": 155,
      "annualReport": {
        "amount": 60,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic corporation $60; FOREIGN corporation annual report is $250."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "VA": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 50,
        "frequency": "annual",
        "dueDate": null,
        "note": "Flat $50 annual registration fee; no report content. $25 late penalty."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 75,
      "foreignQualificationFee": 75,
      "annualReport": {
        "amount": 100,
        "frequency": "annual",
        "dueDate": null,
        "note": "VARIES by authorized shares: $100 for 1-5,000, rising $30 per additional 5,000. Nonstock $25."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "feeVaries": true,
      "feeVariesNote": "Stock corporation charter fee is $25 plus $50 per 25,000 authorized shares, minimum $75, maximum $2,525. The annual registration fee also scales. Stored figures are minimums."
    }
  },
  "WA": {
    "grossReceiptsTax": {
      "applies": true,
      "rate": null,
      "threshold": null,
      "base": "gross_receipts",
      "note": "Business & Occupation tax on GROSS receipts with NO deduction for costs. Rates vary across more than 50 classifications, so no single rate is stored and the engine must compute null."
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 180,
      "foreignQualificationFee": 180,
      "annualReport": {
        "amount": 70,
        "frequency": "annual",
        "dueDate": null,
        "note": "Initial report within 120 days: free with formation, otherwise $10. Annual report $70, $95 delinquent."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 180,
      "foreignQualificationFee": 180,
      "annualReport": {
        "amount": 70,
        "frequency": "annual",
        "dueDate": null,
        "note": "Same as LLC."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "WV": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Due 1 Jan to June 30; $50 late fee for profit entities."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Same window and late fee."
      },
      "annualTax": {
        "amount": null,
        "note": null
      }
    }
  },
  "WI": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": null,
      "note": null
    },
    "llc": {
      "formationFee": 170,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 25,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic LLC $25; FOREIGN LLC $80. $15 paper surcharge since March 2024."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 100,
      "annualReport": {
        "amount": 40,
        "frequency": "annual",
        "dueDate": null,
        "note": "Domestic stock corporation $40; foreign corporation $80."
      },
      "annualTax": {
        "amount": null,
        "note": null
      },
      "recheckIdenticalForeignFee": true
    }
  },
  "WY": {
    "grossReceiptsTax": {
      "applies": null,
      "rate": null,
      "threshold": null,
      "base": null,
      "note": null
    },
    "franchiseTax": {
      "structured": {
        "annualReportLicenseTax": {
          "floor": 60,
          "ratePerDollarOfWyomingAssets": 0.0002,
          "breakevenAssets": 300000,
          "formula": "greater of $60 or $0.0002 x assets located and employed in Wyoming"
        }
      },
      "note": null
    },
    "llc": {
      "formationFee": 100,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 60,
        "frequency": "annual",
        "dueDate": "first day of the anniversary month",
        "note": "License tax: greater of $60 or $0.0002 per dollar of assets located and employed in Wyoming. May be filed up to 120 days early."
      },
      "annualTax": {
        "amount": null,
        "note": "No separate annual tax. Wyoming has no corporate or personal income tax."
      },
      "recheckIdenticalForeignFee": true
    },
    "corp": {
      "formationFee": 100,
      "foreignQualificationFee": 150,
      "annualReport": {
        "amount": 60,
        "frequency": "annual",
        "dueDate": "first day of the anniversary month",
        "note": "Same license tax formula. Figure is for profit corporations; nonprofits pay a flat $25."
      },
      "annualTax": {
        "amount": null,
        "note": "No separate annual tax."
      },
      "recheckIdenticalForeignFee": true
    }
  }
};

export default formationFees;
