/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * slug and name are DERIVED for display; all tax-relevant fields are verbatim.
 */
import type { PlatformCategories, PlatformSummary } from './types';

export const VERIFIED = "2026-v3.3" as const;

export const platforms: PlatformCategories = {
  "gig_rideshare": {
    "uber": {
      "incomeType": "1099-NEC",
      "platformFee": "varies (Uber keeps % of fare)",
      "keyDeductions": [
        "mileage",
        "phone",
        "dashcam",
        "car_washes",
        "tolls",
        "parking",
        "insurance_pct"
      ]
    },
    "lyft": {
      "incomeType": "1099-NEC",
      "platformFee": "varies",
      "keyDeductions": [
        "mileage",
        "phone",
        "tolls",
        "parking",
        "car_washes"
      ]
    }
  },
  "gig_delivery": {
    "doordash": {
      "incomeType": "1099-NEC",
      "platformFee": 0,
      "keyDeductions": [
        "mileage",
        "phone",
        "insulated_bag",
        "parking",
        "tolls"
      ]
    },
    "instacart": {
      "incomeType": "1099-NEC",
      "note": "Full-service shopper = SE. In-store shopper = W-2.",
      "keyDeductions": [
        "mileage",
        "insulated_bag",
        "phone",
        "parking"
      ]
    },
    "grubhub": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "mileage",
        "phone",
        "insulated_bag",
        "parking"
      ]
    },
    "amazon_flex": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "mileage",
        "phone",
        "dolly",
        "vehicle_equipment"
      ]
    },
    "spark_walmart": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "mileage",
        "phone",
        "insulated_bag"
      ]
    },
    "shipt": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "mileage",
        "insulated_bag",
        "phone"
      ]
    }
  },
  "gig_services": {
    "taskrabbit": {
      "incomeType": "1099-NEC",
      "platformFee": 0.15,
      "keyDeductions": [
        "tools",
        "mileage",
        "phone",
        "protective_clothing",
        "liability_insurance"
      ]
    },
    "rover": {
      "incomeType": "1099-NEC",
      "platformFee": 0.2,
      "keyDeductions": [
        "pet_supplies",
        "mileage",
        "phone",
        "first_aid_cert"
      ]
    },
    "thumbtack": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "lead_fees",
        "mileage",
        "tools",
        "phone",
        "liability_insurance"
      ],
      "note": "Lead fees are 100% deductible business expense."
    },
    "handyman_1099": {
      "keyDeductions": [
        "tools_section179",
        "vehicle_actual",
        "materials",
        "mileage",
        "liability_insurance",
        "licensing"
      ]
    },
    "cleaning": {
      "keyDeductions": [
        "supplies",
        "equipment",
        "mileage",
        "uniform",
        "liability_insurance"
      ]
    },
    "lawn_care": {
      "keyDeductions": [
        "mower_section179",
        "truck",
        "fuel",
        "trailer",
        "maintenance"
      ]
    },
    "babysitter_nanny_1099": {
      "incomeType": "1099-NEC",
      "note": "Critical distinction: nanny working regular hours in employer's home = household employee (W-2, Schedule H). Independent babysitter working for multiple families = 1099 contractor. Calculator must route based on work arrangement.",
      "householdEmployerThreshold2026": 2800,
      "ficaNote": "If nanny earns $2,800+ from single employer in 2026, employer owes FICA. File Schedule H with Form 1040.",
      "keyDeductions_if1099": [
        "mileage_between_families",
        "first_aid_cpr_certification",
        "childcare_supplies",
        "liability_insurance",
        "phone"
      ],
      "keyDeductions_ifEmployer": [
        "see_householdEmployer_entity"
      ],
      "seoKeywords": [
        "babysitter tax calculator",
        "nanny 1099 taxes",
        "babysitter self employed taxes",
        "nanny tax calculator"
      ]
    }
  },
  "creators": {
    "onlyfans": {
      "incomeType": "1099-NEC",
      "platformFee": 0.2,
      "keyDeductions": [
        "camera_lighting_section179",
        "phone",
        "internet",
        "props_costumes",
        "platform_fee_auto"
      ]
    },
    "tiktok": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "phone",
        "ring_light",
        "props",
        "editing_software",
        "platform_fee"
      ]
    },
    "youtube": {
      "incomeType": "1099-MISC",
      "keyDeductions": [
        "camera",
        "microphone",
        "editing_software",
        "home_studio",
        "travel_for_content"
      ]
    },
    "twitch": {
      "incomeType": "1099-NEC",
      "keyDeductions": [
        "pc_console_section179",
        "internet",
        "microphone",
        "webcam",
        "streaming_software"
      ]
    },
    "substack": {
      "platformFee": 0.1,
      "keyDeductions": [
        "laptop",
        "home_office",
        "internet",
        "research_subscriptions"
      ]
    },
    "patreon": {
      "platformFee": 0.08,
      "keyDeductions": [
        "creation_costs",
        "platform_fee",
        "fulfillment"
      ]
    },
    "instagram": {
      "note": "Gifted products taxable at FMV",
      "keyDeductions": [
        "camera",
        "phone",
        "props",
        "editing_apps",
        "travel",
        "agency_fees"
      ]
    },
    "podcast": {
      "keyDeductions": [
        "microphone",
        "recording_software_section179",
        "hosting_fees",
        "home_studio",
        "travel"
      ]
    },
    "affiliate": {
      "keyDeductions": [
        "hosting",
        "domains",
        "email_platform",
        "ad_spend",
        "content_creation"
      ]
    },
    "ugc_creator": {
      "incomeType": "1099-NEC",
      "description": "Creates content for brands to use on brand's channels. Does not post on own audience.",
      "platformFee": 0,
      "note": "Rising category. Paid per deliverable, not per follower. Brand pays direct or via UGC marketplace (Billo, Insense, JoinBrands).",
      "keyDeductions": [
        "camera_phone_section179",
        "editing_software",
        "props_staging",
        "contracts_legal",
        "internet",
        "home_studio"
      ],
      "seoKeywords": [
        "UGC creator tax calculator",
        "UGC creator 1099 taxes",
        "content creator taxes no audience"
      ]
    },
    "online_course_creator": {
      "incomeType": "1099-K or 1099-NEC depending on platform",
      "platformExamples": [
        "Teachable",
        "Thinkific",
        "Kajabi",
        "Udemy",
        "Coursera",
        "Podia",
        "Maven"
      ],
      "platformFeeRange": "0.05–0.50 depending on plan and platform",
      "keyDeductions": [
        "platform_subscription",
        "video_equipment_section179",
        "editing_software",
        "home_studio",
        "marketing_spend",
        "contractor_editors",
        "course_platform_fee"
      ],
      "note": "Udemy courses: revenue share varies (37%–97% depending on source). Kajabi: flat monthly fee, no revenue share. Platform fee structure matters for deduction calculation.",
      "seoKeywords": [
        "online course creator tax calculator",
        "Teachable income taxes",
        "Kajabi taxes",
        "digital course 1099"
      ]
    },
    "newsletter_business": {
      "incomeType": "1099-NEC (sponsorships) + 1099-K (subscriptions if threshold met)",
      "platforms": [
        "Beehiiv",
        "ConvertKit",
        "Substack (if not using Substack profile)",
        "Ghost",
        "Mailchimp"
      ],
      "revenueStreams": [
        "Paid subscriptions",
        "Sponsorships/ads",
        "Affiliate commissions"
      ],
      "keyDeductions": [
        "esp_cost",
        "copywriter_contractors",
        "home_office",
        "laptop",
        "research_subscriptions",
        "design_tools",
        "list_management_tools"
      ],
      "note": "Beehiiv charges flat fee + % on paid subscriptions. Sponsorship income on 1099-NEC above $2,000 threshold.",
      "seoKeywords": [
        "newsletter business tax calculator",
        "Beehiiv income taxes",
        "newsletter creator 1099",
        "email newsletter self employed taxes"
      ]
    },
    "sponsorship_income": {
      "incomeType": "1099-NEC",
      "threshold2026": 2000,
      "note": "Any creator receiving paid brand sponsorships. Brand issues 1099-NEC if $2,000+ paid in year. Below threshold: still taxable, just no form issued.",
      "taxableItems": [
        "Cash sponsorships",
        "Gifted products at fair market value (FMV)",
        "Travel paid by brand",
        "Free services at FMV"
      ],
      "keyDeductions": [
        "agent_manager_fees_if_applicable",
        "content_creation_costs",
        "platform_specific_costs",
        "phone",
        "internet_pct"
      ],
      "giftedProductsNote": "Gifted products from brands are taxable income at FMV even if never sold. Common mistake: creators don't report PR packages.",
      "seoKeywords": [
        "sponsorship income tax calculator",
        "brand deal taxes",
        "sponsored content 1099",
        "influencer sponsorship taxes"
      ]
    },
    "brand_deal_calculator": {
      "incomeType": "1099-NEC",
      "description": "Standalone one-page tool: user enters single brand deal amount, sees instant tax breakdown.",
      "targetUser": "Creator who just got a $5,000 or $10,000 brand deal and wants to know what to set aside.",
      "keyOutputs": [
        "SE tax on deal amount",
        "Federal income tax estimate at their bracket",
        "State income tax estimate",
        "Net take-home after taxes",
        "% to set aside"
      ],
      "keyDeductions": [
        "creation_costs_for_this_deal",
        "agent_fees",
        "equipment_used"
      ],
      "viralityNote": "Most shareable standalone tool on the site. Creators post these results on social media.",
      "seoKeywords": [
        "brand deal tax calculator",
        "how much tax on $10000 brand deal",
        "creator brand deal after tax",
        "influencer deal taxes"
      ]
    }
  },
  "sellers": {
    "etsy": {
      "fees": {
        "listing": 0.2,
        "transaction": 0.065,
        "payment_processing": 0.03
      },
      "keyDeductions": [
        "cogs",
        "platform_fees",
        "shipping_supplies",
        "photography_equipment"
      ]
    },
    "ebay": {
      "finalValueFee": "varies by category (avg 12.9%)",
      "keyDeductions": [
        "cost_basis_items",
        "ebay_fees",
        "paypal_fees",
        "shipping",
        "packing_supplies"
      ]
    },
    "amazon_fba": {
      "referralFee": 0.15,
      "keyDeductions": [
        "amazon_fees",
        "fba_fulfillment",
        "storage",
        "cogs",
        "advertising"
      ]
    },
    "shopify": {
      "subscriptionCost": "varies by plan",
      "keyDeductions": [
        "platform_fee",
        "payment_processing",
        "cogs",
        "shipping",
        "advertising"
      ]
    },
    "poshmark": {
      "fee": "20% on sales >$15, $2.95 flat under $15",
      "keyDeductions": [
        "cost_basis_items",
        "platform_fees",
        "shipping_supplies"
      ]
    },
    "mercari": {
      "sellerFee": 0.1,
      "keyDeductions": [
        "cost_basis",
        "platform_fees",
        "shipping"
      ]
    },
    "gumroad": {
      "fee": 0.1,
      "keyDeductions": [
        "platform_fee",
        "email_platform",
        "software",
        "home_office"
      ]
    },
    "stan_store": {
      "fee": 0.05,
      "keyDeductions": [
        "platform_fee",
        "email_platform",
        "content_creation_tools"
      ]
    },
    "facebook_marketplace": {
      "incomeType": "1099-K if $20,000+ / 200+ transactions; taxable regardless",
      "criticalDistinction": {
        "personalItems_soldAtLoss": "Not taxable. Loss on personal property is not deductible.",
        "personalItems_soldAtGain": "Taxable as capital gain. Short-term if owned <1 year.",
        "inventoryForResale": "Schedule C — ordinary income + SE tax.",
        "routingQuestion": "Calculator must ask: 'Are you reselling for profit (business) or selling personal belongings?'"
      },
      "keyDeductions_ifBusiness": [
        "cost_basis_items_purchased_for_resale",
        "shipping_supplies",
        "mileage_to_pickup_items",
        "marketplace_selling_fees"
      ],
      "note": "Facebook Marketplace introduced selling fees in some categories. Payments via Facebook Pay tracked for 1099-K.",
      "seoKeywords": [
        "Facebook Marketplace tax calculator",
        "selling on Facebook Marketplace taxes",
        "Facebook Marketplace 1099-K"
      ]
    },
    "stockx_goat": {
      "incomeType": "1099-K if threshold met",
      "note": "Sneaker and streetwear resale. StockX charges seller fee (~8–9.5% depending on seller level) + transaction fee. GOAT charges commission 15–25%.",
      "keyTaxQuestion": "Business vs investment activity. Frequent flippers = ordinary income (Schedule C). Occasional sellers = capital gain (Schedule D).",
      "taxTreatment": {
        "businessReseller": "Schedule C — ordinary income + SE tax. Can deduct COGS, platform fees, authentication fees, shipping.",
        "investmentActivity": "Schedule D — short or long-term capital gain. Cost basis = purchase price + shipping + fees."
      },
      "keyDeductions_ifBusiness": [
        "cost_basis_shoes",
        "stockx_seller_fee",
        "authentication_fee",
        "shipping_costs",
        "storage"
      ],
      "seoKeywords": [
        "StockX tax calculator",
        "sneaker reselling taxes",
        "GOAT seller taxes",
        "sneaker flip taxes 1099"
      ]
    },
    "printful_printify": {
      "incomeType": "1099-K (via Etsy/Shopify) or 1099-NEC",
      "description": "Print-on-demand: designs made by seller, products fulfilled by Printful/Printify. No inventory held.",
      "cogsNote": "COGS = base cost of each item fulfilled by Printful/Printify. This is the biggest and most important deduction for POD sellers.",
      "platformFee": "None — POD supplier charges base product price. Seller sets retail price above base cost.",
      "keyDeductions": [
        "printful_printify_base_cost_COGS",
        "design_software_subscription",
        "shopify_etsy_fees",
        "advertising_spend",
        "photography_mockups"
      ],
      "note": "High volume POD sellers: COGS tracking is essential. Printful/Printify monthly statements show total product cost — this is your COGS.",
      "seoKeywords": [
        "Printful tax calculator",
        "Printify seller taxes",
        "print on demand 1099 taxes",
        "POD business taxes"
      ]
    }
  },
  "rental": {
    "airbnb": {
      "incomeType": "1099-K if threshold met",
      "scheduleUsed": "Schedule C if substantial services; Schedule E if simple rent",
      "keyDeductions": [
        "mortgage_interest_pct",
        "property_taxes_pct",
        "depreciation",
        "supplies",
        "cleaning",
        "platform_fees",
        "repairs"
      ],
      "augustaRuleApplicable": true,
      "note": "Airbnb takes approx 3% host fee. Guest pays Airbnb fee separately."
    },
    "turo": {
      "incomeType": "1099-K if threshold met",
      "scheduleUsed": "Schedule C",
      "vehicleDeductionMethods": [
        "standard_mileage",
        "actual_expense",
        "special_turo_method"
      ],
      "keyDeductions": [
        "insurance",
        "depreciation_actual",
        "maintenance",
        "platform_fee"
      ],
      "note": "Cannot use standard mileage if previously used MACRS depreciation on vehicle."
    },
    "vrbo": {
      "scheduleUsed": "Same as Airbnb — services test",
      "keyDeductions": [
        "same_as_airbnb"
      ]
    },
    "getaround": {
      "incomeType": "1099-K if threshold met",
      "scheduleUsed": "Schedule C",
      "description": "Peer-to-peer car sharing. Getaround takes 40% of each trip. Owner keeps 60%.",
      "keyDeductions": [
        "insurance_pct_business_use",
        "depreciation_actual_method",
        "maintenance_pct",
        "getaround_platform_fee_already_netted",
        "car_wash"
      ],
      "note": "Getaround fee already netted from payment. Deduct actual vehicle expenses at business-use percentage.",
      "seoKeywords": [
        "Getaround tax calculator",
        "Getaround income taxes",
        "car sharing income taxes"
      ]
    },
    "rv_rental": {
      "incomeType": "1099-K (via RVshare/Outdoorsy) or self-reported",
      "scheduleUsed": "Schedule C",
      "platforms": [
        "RVshare",
        "Outdoorsy",
        "Cruise America"
      ],
      "keyDeductions": [
        "rv_depreciation_section179_or_macrs",
        "insurance_pct",
        "maintenance_repairs",
        "campground_fees_if_host_delivered",
        "platform_fee",
        "storage"
      ],
      "depreciationNote": "RVs depreciate over 5 years (MACRS) for business use. Section 179 may apply if >50% business use.",
      "seoKeywords": [
        "RV rental income taxes",
        "RVshare tax calculator",
        "Outdoorsy income 1099",
        "renting your RV taxes"
      ]
    },
    "boat_rental": {
      "incomeType": "1099-K or self-reported",
      "scheduleUsed": "Schedule C (with captain services) or Schedule E (bare boat charter)",
      "platforms": [
        "Boatsetter",
        "GetMyBoat",
        "Sailo"
      ],
      "keyDeductions": [
        "boat_depreciation_section179",
        "insurance",
        "marina_storage_fees",
        "maintenance",
        "fuel_pct",
        "platform_fee",
        "captains_wages_if_applicable"
      ],
      "note": "Bare boat charter (no captain) = more likely Schedule E. Charter with captain providing services = Schedule C.",
      "seoKeywords": [
        "boat rental income taxes",
        "Boatsetter tax calculator",
        "renting your boat taxes"
      ]
    },
    "equipment_rental": {
      "incomeType": "1099-NEC or self-reported",
      "scheduleUsed": "Schedule C",
      "examples": [
        "Tools",
        "Photography equipment",
        "Trailers",
        "Construction equipment",
        "Party supplies"
      ],
      "platforms": [
        "Fat Llama",
        "Rntr",
        "Sparkfly",
        "Rentah"
      ],
      "keyDeductions": [
        "equipment_depreciation_section179",
        "insurance",
        "maintenance_repairs",
        "storage",
        "platform_fee",
        "mileage_for_delivery"
      ],
      "seoKeywords": [
        "equipment rental income taxes",
        "renting tools tax calculator",
        "Fat Llama income taxes"
      ]
    },
    "parking_space_rental": {
      "incomeType": "1099-K or self-reported",
      "scheduleUsed": "Schedule E (passive) typically",
      "platforms": [
        "SpotHero",
        "Neighbor",
        "ParkWhiz"
      ],
      "keyDeductions": [
        "property_taxes_pct",
        "insurance_pct",
        "repairs_maintenance",
        "platform_fee",
        "advertising"
      ],
      "note": "Passive income — generally no SE tax. Losses subject to passive activity rules.",
      "seoKeywords": [
        "parking space rental taxes",
        "SpotHero income taxes",
        "renting parking space tax calculator"
      ]
    },
    "storage_rental": {
      "incomeType": "1099-K or self-reported",
      "scheduleUsed": "Schedule E (passive)",
      "platforms": [
        "Neighbor",
        "SpareFoot"
      ],
      "keyDeductions": [
        "property_taxes_pct",
        "insurance",
        "platform_fee",
        "repairs"
      ],
      "note": "Renting storage space in home, garage, or outbuilding. Generally Schedule E passive income.",
      "seoKeywords": [
        "storage rental income taxes",
        "Neighbor app income taxes",
        "renting garage storage taxes"
      ]
    },
    "short_vs_long_term_rental": {
      "description": "Comparison calculator: same property modeled as STR vs LTR",
      "shortTermRental": {
        "scheduleUsed": "Schedule C if substantial services; Schedule E if simple",
        "avgNightly": "Higher nightly rate",
        "seTaxRisk": "If Schedule C applies, SE tax on net profit",
        "vacancyRisk": "Higher",
        "deductions": "All STR expenses prorated by days rented"
      },
      "longTermRental": {
        "scheduleUsed": "Schedule E — passive",
        "seTaxRisk": "None (passive)",
        "stabilityAdvantage": "Predictable monthly income",
        "deductions": [
          "Mortgage interest",
          "Property taxes",
          "Depreciation 27.5yr",
          "Insurance",
          "Maintenance",
          "Management fees"
        ]
      },
      "keystoneQuestion": "7-day average rental period test: average rental ≤7 days = not passive (Schedule C rules). >7 days average = passive (Schedule E).",
      "seoKeywords": [
        "short term vs long term rental tax comparison",
        "Airbnb vs long term rental taxes",
        "STR vs LTR tax calculator"
      ]
    },
    "landlord": {
      "incomeType": "Rental income — Schedule E",
      "scheduleUsed": "Schedule E Part I",
      "seTaxApplies": false,
      "passiveLossRule": {
        "allowedLossIfActiveParticipation": 25000,
        "phaseoutStartMAGI": 100000,
        "phaseoutEndMAGI": 150000,
        "realEstateProfessionalException": "750+ hours AND more hours in RE than any other activity — losses become non-passive"
      },
      "keyDeductions": [
        "mortgage_interest",
        "property_taxes",
        "depreciation_27_5_years",
        "insurance",
        "repairs_maintenance",
        "property_management_fees",
        "advertising_vacancy",
        "legal_accounting_fees",
        "travel_to_property"
      ],
      "depreciationNote": "Residential property depreciates over 27.5 years. Land is NOT depreciable. Cost segregation study can accelerate depreciation for commercial.",
      "note1031Exchange": "Like-kind exchange: defer capital gain taxes by reinvesting sale proceeds into a new property within 45/180 day deadlines.",
      "seoKeywords": [
        "landlord tax calculator",
        "rental property tax calculator",
        "Schedule E rental income taxes",
        "how much tax on rental income"
      ]
    },
    "real_estate_agent_rental": {
      "note": "Real estate agents who also own rental properties have a unique advantage: if they qualify as real estate professionals (750+ hours, majority of work time in RE), passive loss rules don't apply — rental losses can offset all income.",
      "scheduleUsed": "Schedule C for agent commissions. Schedule E for rental income.",
      "seoKeywords": [
        "real estate agent rental income taxes",
        "realtor rental property taxes",
        "real estate professional tax status"
      ]
    }
  }
};

/** Flattened, page-ready list. NOTE: worked-example incomes are NOT in the legacy
 *  dataset and must be supplied (owner) before Tier-3 platform pages are built. */
export const platformList: PlatformSummary[] = [
  {
    "slug": "uber",
    "name": "Uber",
    "category": "gig_rideshare",
    "key": "uber",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "dashcam",
      "car_washes",
      "tolls",
      "parking",
      "insurance_pct"
    ]
  },
  {
    "slug": "lyft",
    "name": "Lyft",
    "category": "gig_rideshare",
    "key": "lyft",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "tolls",
      "parking",
      "car_washes"
    ]
  },
  {
    "slug": "doordash",
    "name": "Doordash",
    "category": "gig_delivery",
    "key": "doordash",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "insulated_bag",
      "parking",
      "tolls"
    ]
  },
  {
    "slug": "instacart",
    "name": "Instacart",
    "category": "gig_delivery",
    "key": "instacart",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "insulated_bag",
      "phone",
      "parking"
    ]
  },
  {
    "slug": "grubhub",
    "name": "Grubhub",
    "category": "gig_delivery",
    "key": "grubhub",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "insulated_bag",
      "parking"
    ]
  },
  {
    "slug": "amazon-flex",
    "name": "Amazon Flex",
    "category": "gig_delivery",
    "key": "amazon_flex",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "dolly",
      "vehicle_equipment"
    ]
  },
  {
    "slug": "spark-walmart",
    "name": "Spark (Walmart)",
    "category": "gig_delivery",
    "key": "spark_walmart",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "phone",
      "insulated_bag"
    ]
  },
  {
    "slug": "shipt",
    "name": "Shipt",
    "category": "gig_delivery",
    "key": "shipt",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "mileage",
      "insulated_bag",
      "phone"
    ]
  },
  {
    "slug": "taskrabbit",
    "name": "Taskrabbit",
    "category": "gig_services",
    "key": "taskrabbit",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "tools",
      "mileage",
      "phone",
      "protective_clothing",
      "liability_insurance"
    ]
  },
  {
    "slug": "rover",
    "name": "Rover",
    "category": "gig_services",
    "key": "rover",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "pet_supplies",
      "mileage",
      "phone",
      "first_aid_cert"
    ]
  },
  {
    "slug": "thumbtack",
    "name": "Thumbtack",
    "category": "gig_services",
    "key": "thumbtack",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "lead_fees",
      "mileage",
      "tools",
      "phone",
      "liability_insurance"
    ]
  },
  {
    "slug": "handyman-1099",
    "name": "Handyman",
    "category": "gig_services",
    "key": "handyman_1099",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "tools_section179",
      "vehicle_actual",
      "materials",
      "mileage",
      "liability_insurance",
      "licensing"
    ]
  },
  {
    "slug": "cleaning",
    "name": "Cleaning",
    "category": "gig_services",
    "key": "cleaning",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "supplies",
      "equipment",
      "mileage",
      "uniform",
      "liability_insurance"
    ]
  },
  {
    "slug": "lawn-care",
    "name": "Lawn Care",
    "category": "gig_services",
    "key": "lawn_care",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "mower_section179",
      "truck",
      "fuel",
      "trailer",
      "maintenance"
    ]
  },
  {
    "slug": "babysitter-nanny-1099",
    "name": "Babysitter / Nanny",
    "category": "gig_services",
    "key": "babysitter_nanny_1099",
    "incomeType": "1099-NEC",
    "keyDeductions": []
  },
  {
    "slug": "onlyfans",
    "name": "OnlyFans",
    "category": "creators",
    "key": "onlyfans",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "camera_lighting_section179",
      "phone",
      "internet",
      "props_costumes",
      "platform_fee_auto"
    ]
  },
  {
    "slug": "tiktok",
    "name": "TikTok",
    "category": "creators",
    "key": "tiktok",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "phone",
      "ring_light",
      "props",
      "editing_software",
      "platform_fee"
    ]
  },
  {
    "slug": "youtube",
    "name": "YouTube",
    "category": "creators",
    "key": "youtube",
    "incomeType": "1099-MISC",
    "keyDeductions": [
      "camera",
      "microphone",
      "editing_software",
      "home_studio",
      "travel_for_content"
    ]
  },
  {
    "slug": "twitch",
    "name": "Twitch",
    "category": "creators",
    "key": "twitch",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "pc_console_section179",
      "internet",
      "microphone",
      "webcam",
      "streaming_software"
    ]
  },
  {
    "slug": "substack",
    "name": "Substack",
    "category": "creators",
    "key": "substack",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "laptop",
      "home_office",
      "internet",
      "research_subscriptions"
    ]
  },
  {
    "slug": "patreon",
    "name": "Patreon",
    "category": "creators",
    "key": "patreon",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "creation_costs",
      "platform_fee",
      "fulfillment"
    ]
  },
  {
    "slug": "instagram",
    "name": "Instagram",
    "category": "creators",
    "key": "instagram",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "camera",
      "phone",
      "props",
      "editing_apps",
      "travel",
      "agency_fees"
    ]
  },
  {
    "slug": "podcast",
    "name": "Podcast",
    "category": "creators",
    "key": "podcast",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "microphone",
      "recording_software_section179",
      "hosting_fees",
      "home_studio",
      "travel"
    ]
  },
  {
    "slug": "affiliate",
    "name": "Affiliate",
    "category": "creators",
    "key": "affiliate",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "hosting",
      "domains",
      "email_platform",
      "ad_spend",
      "content_creation"
    ]
  },
  {
    "slug": "ugc-creator",
    "name": "UGC Creator",
    "category": "creators",
    "key": "ugc_creator",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "camera_phone_section179",
      "editing_software",
      "props_staging",
      "contracts_legal",
      "internet",
      "home_studio"
    ]
  },
  {
    "slug": "online-course-creator",
    "name": "Online Course Creator",
    "category": "creators",
    "key": "online_course_creator",
    "incomeType": "1099-K or 1099-NEC depending on platform",
    "keyDeductions": [
      "platform_subscription",
      "video_equipment_section179",
      "editing_software",
      "home_studio",
      "marketing_spend",
      "contractor_editors",
      "course_platform_fee"
    ]
  },
  {
    "slug": "newsletter-business",
    "name": "Newsletter Business",
    "category": "creators",
    "key": "newsletter_business",
    "incomeType": "1099-NEC (sponsorships) + 1099-K (subscriptions if threshold met)",
    "keyDeductions": [
      "esp_cost",
      "copywriter_contractors",
      "home_office",
      "laptop",
      "research_subscriptions",
      "design_tools",
      "list_management_tools"
    ]
  },
  {
    "slug": "sponsorship-income",
    "name": "Sponsorship Income",
    "category": "creators",
    "key": "sponsorship_income",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "agent_manager_fees_if_applicable",
      "content_creation_costs",
      "platform_specific_costs",
      "phone",
      "internet_pct"
    ]
  },
  {
    "slug": "brand-deal-calculator",
    "name": "Brand Deal Calculator",
    "category": "creators",
    "key": "brand_deal_calculator",
    "incomeType": "1099-NEC",
    "keyDeductions": [
      "creation_costs_for_this_deal",
      "agent_fees",
      "equipment_used"
    ]
  },
  {
    "slug": "etsy",
    "name": "Etsy",
    "category": "sellers",
    "key": "etsy",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "cogs",
      "platform_fees",
      "shipping_supplies",
      "photography_equipment"
    ]
  },
  {
    "slug": "ebay",
    "name": "eBay",
    "category": "sellers",
    "key": "ebay",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "cost_basis_items",
      "ebay_fees",
      "paypal_fees",
      "shipping",
      "packing_supplies"
    ]
  },
  {
    "slug": "amazon-fba",
    "name": "Amazon FBA",
    "category": "sellers",
    "key": "amazon_fba",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "amazon_fees",
      "fba_fulfillment",
      "storage",
      "cogs",
      "advertising"
    ]
  },
  {
    "slug": "shopify",
    "name": "Shopify",
    "category": "sellers",
    "key": "shopify",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "platform_fee",
      "payment_processing",
      "cogs",
      "shipping",
      "advertising"
    ]
  },
  {
    "slug": "poshmark",
    "name": "Poshmark",
    "category": "sellers",
    "key": "poshmark",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "cost_basis_items",
      "platform_fees",
      "shipping_supplies"
    ]
  },
  {
    "slug": "mercari",
    "name": "Mercari",
    "category": "sellers",
    "key": "mercari",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "cost_basis",
      "platform_fees",
      "shipping"
    ]
  },
  {
    "slug": "gumroad",
    "name": "Gumroad",
    "category": "sellers",
    "key": "gumroad",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "platform_fee",
      "email_platform",
      "software",
      "home_office"
    ]
  },
  {
    "slug": "stan-store",
    "name": "Stan Store",
    "category": "sellers",
    "key": "stan_store",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "platform_fee",
      "email_platform",
      "content_creation_tools"
    ]
  },
  {
    "slug": "facebook-marketplace",
    "name": "Facebook Marketplace",
    "category": "sellers",
    "key": "facebook_marketplace",
    "incomeType": "1099-K if $20,000+ / 200+ transactions; taxable regardless",
    "keyDeductions": []
  },
  {
    "slug": "stockx-goat",
    "name": "StockX / GOAT",
    "category": "sellers",
    "key": "stockx_goat",
    "incomeType": "1099-K if threshold met",
    "keyDeductions": []
  },
  {
    "slug": "printful-printify",
    "name": "Printful / Printify",
    "category": "sellers",
    "key": "printful_printify",
    "incomeType": "1099-K (via Etsy/Shopify) or 1099-NEC",
    "keyDeductions": [
      "printful_printify_base_cost_COGS",
      "design_software_subscription",
      "shopify_etsy_fees",
      "advertising_spend",
      "photography_mockups"
    ]
  },
  {
    "slug": "airbnb",
    "name": "Airbnb",
    "category": "rental",
    "key": "airbnb",
    "incomeType": "1099-K if threshold met",
    "keyDeductions": [
      "mortgage_interest_pct",
      "property_taxes_pct",
      "depreciation",
      "supplies",
      "cleaning",
      "platform_fees",
      "repairs"
    ]
  },
  {
    "slug": "turo",
    "name": "Turo",
    "category": "rental",
    "key": "turo",
    "incomeType": "1099-K if threshold met",
    "keyDeductions": [
      "insurance",
      "depreciation_actual",
      "maintenance",
      "platform_fee"
    ]
  },
  {
    "slug": "vrbo",
    "name": "Vrbo",
    "category": "rental",
    "key": "vrbo",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": [
      "same_as_airbnb"
    ]
  },
  {
    "slug": "getaround",
    "name": "Getaround",
    "category": "rental",
    "key": "getaround",
    "incomeType": "1099-K if threshold met",
    "keyDeductions": [
      "insurance_pct_business_use",
      "depreciation_actual_method",
      "maintenance_pct",
      "getaround_platform_fee_already_netted",
      "car_wash"
    ]
  },
  {
    "slug": "rv-rental",
    "name": "RV Rental",
    "category": "rental",
    "key": "rv_rental",
    "incomeType": "1099-K (via RVshare/Outdoorsy) or self-reported",
    "keyDeductions": [
      "rv_depreciation_section179_or_macrs",
      "insurance_pct",
      "maintenance_repairs",
      "campground_fees_if_host_delivered",
      "platform_fee",
      "storage"
    ]
  },
  {
    "slug": "boat-rental",
    "name": "Boat Rental",
    "category": "rental",
    "key": "boat_rental",
    "incomeType": "1099-K or self-reported",
    "keyDeductions": [
      "boat_depreciation_section179",
      "insurance",
      "marina_storage_fees",
      "maintenance",
      "fuel_pct",
      "platform_fee",
      "captains_wages_if_applicable"
    ]
  },
  {
    "slug": "equipment-rental",
    "name": "Equipment Rental",
    "category": "rental",
    "key": "equipment_rental",
    "incomeType": "1099-NEC or self-reported",
    "keyDeductions": [
      "equipment_depreciation_section179",
      "insurance",
      "maintenance_repairs",
      "storage",
      "platform_fee",
      "mileage_for_delivery"
    ]
  },
  {
    "slug": "parking-space-rental",
    "name": "Parking Space Rental",
    "category": "rental",
    "key": "parking_space_rental",
    "incomeType": "1099-K or self-reported",
    "keyDeductions": [
      "property_taxes_pct",
      "insurance_pct",
      "repairs_maintenance",
      "platform_fee",
      "advertising"
    ]
  },
  {
    "slug": "storage-rental",
    "name": "Storage Rental",
    "category": "rental",
    "key": "storage_rental",
    "incomeType": "1099-K or self-reported",
    "keyDeductions": [
      "property_taxes_pct",
      "insurance",
      "platform_fee",
      "repairs"
    ]
  },
  {
    "slug": "short-vs-long-term-rental",
    "name": "Short vs Long-Term Rental",
    "category": "rental",
    "key": "short_vs_long_term_rental",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": []
  },
  {
    "slug": "landlord",
    "name": "Landlord",
    "category": "rental",
    "key": "landlord",
    "incomeType": "Rental income — Schedule E",
    "keyDeductions": [
      "mortgage_interest",
      "property_taxes",
      "depreciation_27_5_years",
      "insurance",
      "repairs_maintenance",
      "property_management_fees",
      "advertising_vacancy",
      "legal_accounting_fees",
      "travel_to_property"
    ]
  },
  {
    "slug": "real-estate-agent-rental",
    "name": "Real Estate Agent",
    "category": "rental",
    "key": "real_estate_agent_rental",
    "incomeType": "Self-reported (report even without a 1099)",
    "keyDeductions": []
  }
];
