/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * Legacy deduction slugs, notes and unique rules copied verbatim, MERGED with the authored trades in overrides/professions-trades.json. Labels are applied in lib/professions.ts.
 */
export const VERIFIED = "2026-v3.3" as const;

export const professionals = {
  "software_dev": {
    "keyDeductions": [
      "home_office",
      "computer_monitors",
      "cloud_services",
      "pro_development",
      "internet",
      "phone"
    ]
  },
  "ai_consultant": {
    "keyDeductions": [
      "compute_costs",
      "ai_software_subscriptions",
      "home_office",
      "conferences",
      "research"
    ]
  },
  "designer": {
    "keyDeductions": [
      "adobe_cc",
      "figma",
      "monitor_ipad_section179",
      "home_office",
      "stock_assets"
    ]
  },
  "copywriter": {
    "keyDeductions": [
      "grammarly",
      "research_subscriptions",
      "home_office",
      "internet",
      "pro_development"
    ]
  },
  "realtor": {
    "keyDeductions": [
      "mls_fees",
      "eo_insurance",
      "client_gifts_limit_25",
      "marketing",
      "vehicle",
      "staging_costs"
    ],
    "sources": [
      {
        "claim": "Real estate agents and brokers are excluded from 'brokerage services'",
        "authority": "Reg. 1.199A-5(b)(2)(x)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "travel_nurse": {
    "keyDeductions": [
      "licensing_fees",
      "per_diem",
      "travel",
      "scrubs",
      "ceus",
      "malpractice_insurance"
    ]
  },
  "truck_driver_otr": {
    "keyDeductions": [
      "per_diem_80_per_day",
      "truck_depreciation",
      "fuel",
      "dot_fees",
      "maintenance"
    ],
    "sources": [
      {
        "claim": "Meal expenses of individuals subject to DOT hours-of-service limits are 80% deductible",
        "authority": "IRC 274(n)(3)",
        "url": "https://www.law.cornell.edu/uscode/text/26/274",
        "confidence": "high"
      },
      {
        "claim": "Employee drivers cannot deduct it: the bar on miscellaneous itemised deductions was made permanent",
        "authority": "IRC 67(g), as amended by P.L. 119-21 sec. 70110",
        "url": "https://www.law.cornell.edu/uscode/text/26/67",
        "confidence": "high"
      }
    ]
  },
  "photographer": {
    "keyDeductions": [
      "camera_lenses_section179",
      "lighting",
      "editing_software",
      "travel",
      "studio_rent"
    ]
  },
  "hair_stylist": {
    "keyDeductions": [
      "booth_rent",
      "tools",
      "supplies",
      "continuing_education",
      "liability_insurance"
    ],
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      },
      {
        "claim": "The employer credit for FICA on tips now covers beauty services, using the current $7.25 minimum rather than the frozen $5.15",
        "authority": "IRC 45B(b)(1)(B), 45B(b)(2)(B)",
        "url": "https://www.law.cornell.edu/uscode/text/26/45B",
        "confidence": "high"
      }
    ]
  },
  "personal_trainer": {
    "keyDeductions": [
      "certification_fees",
      "equipment",
      "liability_insurance",
      "marketing",
      "gym_membership_business_pct"
    ],
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      }
    ]
  },
  "therapist": {
    "keyDeductions": [
      "malpractice_insurance",
      "ceus",
      "ehr_software",
      "office_rent_or_home_office",
      "supervision_costs"
    ]
  },
  "nurse_contractor": {
    "keyDeductions": [
      "malpractice_insurance",
      "licensing_fees",
      "scrubs",
      "ceus",
      "mileage_or_travel"
    ]
  },
  "massage_therapist": {
    "keyDeductions": [
      "massage_table_section179",
      "oils_supplies",
      "liability_insurance",
      "ce_credits",
      "booth_rent"
    ],
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      }
    ]
  },
  "bookkeeper_accountant": {
    "keyDeductions": [
      "quickbooks_xero_software",
      "continuing_education_cpe",
      "eo_insurance",
      "home_office",
      "professional_memberships_aicpa",
      "phone",
      "internet_pct"
    ],
    "note": "CPAs and EAs (Enrolled Agents) have additional licensing fees deductible as professional expenses.",
    "seoKeywords": [
      "bookkeeper 1099 tax calculator",
      "self employed accountant taxes",
      "CPA freelance taxes"
    ]
  },
  "virtual_assistant": {
    "keyDeductions": [
      "home_office",
      "computer",
      "internet_pct",
      "software_subscriptions",
      "phone",
      "professional_development",
      "contractor_subcontractors"
    ],
    "note": "VA services are highly deductible-friendly — almost all expenses are home-office and tech based. High S Corp potential at $80K+.",
    "seoKeywords": [
      "virtual assistant tax calculator",
      "VA 1099 taxes",
      "freelance VA taxes"
    ]
  },
  "coach": {
    "types": [
      "Business coach",
      "Life coach",
      "Health coach",
      "Executive coach",
      "Relationship coach"
    ],
    "keyDeductions": [
      "coaching_certification_fees",
      "zoom_video_platform",
      "home_office",
      "professional_development",
      "website",
      "crm_software",
      "marketing"
    ],
    "note": "Coaching certification costs are deductible as professional development (must be maintaining/improving current skills, not qualifying for new career).",
    "seoKeywords": [
      "life coach tax calculator",
      "business coach 1099 taxes",
      "executive coach self employed taxes"
    ]
  },
  "insurance_agent": {
    "types": [
      "Independent agent (1099)",
      "Captive agent (W-2 or 1099)"
    ],
    "keyDeductions": [
      "licensing_fees_state",
      "eo_insurance",
      "crm_software",
      "lead_generation_costs",
      "vehicle",
      "professional_development_ce_credits",
      "office_rent_or_home_office"
    ],
    "note": "Captive agents may be W-2. Independent agents are typically 1099. Commissions are SE income.",
    "seoKeywords": [
      "insurance agent tax calculator",
      "independent insurance agent 1099 taxes",
      "insurance broker self employed taxes"
    ],
    "sources": [
      {
        "claim": "Insurance agents are excluded from 'brokerage services', but wealth or retirement advice is financial services",
        "authority": "Reg. 1.199A-5(b)(2)(ix)-(x)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "notary_signing_agent": {
    "keyDeductions": [
      "notary_bond",
      "notary_commission_fees",
      "supplies_stamps_seals",
      "mileage_to_signings",
      "errors_omissions_insurance",
      "background_check_fees",
      "notary_software"
    ],
    "note": "Mobile notary and loan signing agents: mileage between appointments is the largest deduction. Track every signing trip.",
    "seoKeywords": [
      "notary signing agent tax calculator",
      "mobile notary 1099 taxes",
      "loan signing agent taxes"
    ]
  },
  "tutor": {
    "keyDeductions": [
      "home_office_or_tutoring_space",
      "educational_materials_books",
      "laptop",
      "zoom_subscription",
      "marketing",
      "mileage_if_in_person"
    ],
    "note": "Online tutors: home office is key deduction. In-person tutors: mileage between student locations is #1 deduction.",
    "seoKeywords": [
      "tutor tax calculator",
      "online tutor 1099 taxes",
      "self employed tutor taxes"
    ]
  },
  "wedding_event_planner": {
    "keyDeductions": [
      "vendor_deposits_if_direct_billed",
      "event_software_honeybook_aisle",
      "vehicle_mileage",
      "marketing_photography",
      "professional_attire_if_required",
      "liability_insurance",
      "phone",
      "home_office"
    ],
    "note": "Deposits collected on behalf of clients are not income until earned. Vendor payments passed through to client are not deductible if reimbursed.",
    "seoKeywords": [
      "wedding planner tax calculator",
      "event planner 1099 taxes",
      "wedding coordinator self employed taxes"
    ]
  },
  "qa_tester_contractor": {
    "keyDeductions": [
      "device_testing_setup_section179",
      "home_office",
      "software_tools",
      "vpn_subscriptions",
      "professional_development",
      "internet_pct"
    ],
    "note": "Common in tech as contract workers. Devices used for testing (phones, tablets) qualify for Section 179 deduction at business-use percentage.",
    "seoKeywords": [
      "QA tester contractor taxes",
      "software tester 1099 tax calculator",
      "QA engineer freelance taxes"
    ]
  },
  "clergy_minister": {
    "uniqueRules": {
      "housingAllowance": {
        "taxTreatment": "Excludable from federal income tax if designated in advance by church. Amount limited to: lesser of (a) designated amount, (b) actual housing expenses, (c) fair rental value of home furnished + utilities.",
        "seTaxNote": "Housing allowance IS included in SE tax base even though excluded from income tax. This surprises many ministers.",
        "form": "No separate form — designated in church board minutes before year begins"
      },
      "seOptOut": {
        "form": "Form 4361",
        "note": "Irrevocable election to opt out of SE tax on ministerial earnings if conscientiously opposed on religious grounds. Cannot opt back in.",
        "deadline": "Due date of return for second year with net ministerial earnings of $400+"
      },
      "dualStatus": "Ministers are employees for income tax purposes but self-employed for SE tax on ministerial income. Unique in US tax code."
    },
    "keyDeductions": [
      "ministry_expenses",
      "vehicle_for_ministry",
      "books_religious_materials",
      "continuing_education_seminary",
      "home_office_for_study"
    ],
    "seoKeywords": [
      "clergy tax calculator",
      "minister self employment tax",
      "pastor housing allowance calculator",
      "Form 4361 clergy"
    ]
  },
  "farm_schedule_f": {
    "taxForm": "Schedule F (Form 1040)",
    "seTaxApplies": true,
    "uniqueDeductions": [
      {
        "name": "Feed",
        "deductible": 1,
        "note": "Livestock feed purchased and consumed in tax year. Cannot deduct feed purchased but not yet used (inventory rules apply for some farms)."
      },
      {
        "name": "Seeds and plants",
        "deductible": 1,
        "note": "Purchased for planting, not for consumption. Ornamental seeds for personal use are not deductible."
      },
      {
        "name": "Fertilizers and lime",
        "deductible": 1,
        "note": "Soil conditioners and crop nutrients applied in the tax year. Purchased but unused inventory may need to be deducted in future year."
      },
      {
        "name": "Livestock purchased for resale",
        "deductible": 1,
        "note": "Cost of animals purchased during the year and sold in the same year. Treated as COGS on Schedule F. Livestock raised on farm has $0 basis."
      },
      {
        "name": "Breeding livestock depreciation",
        "deductible": 1,
        "note": "Breeding animals are depreciable assets (not expensed as feed). Cattle and horses: 5–7 years MACRS. Section 179 or bonus depreciation may apply."
      },
      {
        "name": "Farm equipment",
        "deductible": 1,
        "note": "Tractors, combines, irrigation systems, planting/harvesting equipment. Section 179 up to $2,560,000 (2026). 100% bonus depreciation available under OBBBA."
      },
      {
        "name": "Crop insurance proceeds deferral",
        "deductible": 0,
        "note": "Crop insurance is income, not a deduction. However, farmers can elect to defer crop insurance proceeds to the following tax year if the crop would normally be sold in a different year. Elective deferral, not automatic."
      },
      {
        "name": "Fuel for farm equipment",
        "deductible": 1,
        "note": "100% deductible for off-highway business use. Also qualifies for federal fuel tax credit (Form 4136) — separate from the deduction."
      },
      {
        "name": "Repairs and maintenance of farm buildings",
        "deductible": 1,
        "note": "Routine repairs are an operating expense. Improvements that add value or extend useful life must be capitalized and depreciated. Tangible property regulations (Repair Regs) govern the distinction."
      }
    ],
    "specialProvisions": {
      "farmingLossCarryback": "Net farming losses can be carried back 2 years (vs 0 years for most businesses).",
      "incomeAveraging": "Schedule J — farmers can average income over 3 years to reduce tax on boom years.",
      "soilConservation": "Deductible up to 25% of gross farming income",
      "fuelTaxCredit": "Form 4136 — credit for non-highway fuel used in farming operations"
    },
    "seoKeywords": [
      "farm income tax calculator",
      "Schedule F tax calculator",
      "farmer self employment tax",
      "agricultural income taxes"
    ],
    "_deductionSchema": "name:string, deductible:number (0–1 or dollar cap), note:string — matches selfEmploymentDeductions.otherCommonDeductions schema"
  },
  "general_contractor": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "subcontractors_1099",
      "liability_insurance",
      "permits_and_licences",
      "materials_and_supplies",
      "equipment_rental",
      "workers_comp",
      "jobsite_travel",
      "safety_gear"
    ],
    "note": "The line that decides a contractor's return is subcontractors. Pay anyone $600 or more in a year and you must issue a 1099-NEC, and misclassifying a worker who should have been an employee is the most expensive mistake in the trade. Materials you buy and bill on are both income and a deduction — never one without the other."
  },
  "electrician": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "continuing_education",
      "liability_insurance",
      "materials_and_supplies",
      "safety_gear",
      "equipment",
      "phone"
    ],
    "note": "Hand tools and testers are deductible in the year you buy them; a van fit-out is a vehicle improvement and is depreciated. State licensing and the continuing education hours that renew it are both deductible, because they maintain a licence you already hold."
  },
  "plumber": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "continuing_education",
      "liability_insurance",
      "materials_and_supplies",
      "equipment",
      "safety_gear",
      "phone"
    ],
    "note": "Emergency call-outs make mileage the largest single deduction for most plumbers, and it is the one least often logged properly. Specialist equipment — drain cameras, jetters, press tools — is Section 179 property and can be written off in full the year it goes into service."
  },
  "hvac_technician": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "epa_certification",
      "continuing_education",
      "liability_insurance",
      "equipment",
      "materials_and_supplies",
      "safety_gear"
    ],
    "note": "EPA Section 608 certification and the state licence behind it are deductible professional costs. Refrigerant and parts inventory bought for a job are deductible when used; stock held at year end is inventory rather than an expense."
  },
  "landscaper": {
    "keyDeductions": [
      "equipment",
      "vehicle",
      "trailer",
      "fuel",
      "materials_and_supplies",
      "liability_insurance",
      "seasonal_labour",
      "storage_yard_rent"
    ],
    "note": "Mowers, trimmers and trailers are Section 179 property. Seasonal crews are usually employees rather than contractors — being paid weekly, using your equipment and working your schedule are all signs of employment, and the penalty for getting it wrong is back payroll tax."
  },
  "cleaner": {
    "keyDeductions": [
      "supplies",
      "equipment",
      "vehicle",
      "liability_insurance",
      "bonding",
      "uniforms",
      "marketing",
      "subcontractors_1099"
    ],
    "note": "Cleaning supplies and equipment are straightforward; bonding and liability cover are what clients ask for and both are deductible. Mileage between client properties counts, but the first trip from home to your first job of the day is commuting and does not."
  },
  "handyman": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "materials_and_supplies",
      "liability_insurance",
      "permits_and_licences",
      "equipment",
      "marketing",
      "phone"
    ],
    "note": "Most handyman work sits below the licensing threshold, but the threshold is set by each state and by the value of the job — exceed it without a licence and the work may be unenforceable as well as uninsured. Materials billed to the customer are income and a deduction both."
  },
  "painter": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment",
      "vehicle",
      "liability_insurance",
      "safety_gear",
      "subcontractors_1099",
      "equipment_rental",
      "certification_fees"
    ],
    "note": "Sprayers, scaffolding and lifts are usually cheaper to hire than to own, and hire costs are deductible in full in the year you pay them with no depreciation to track."
  },
  "roofer": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment_rental",
      "vehicle",
      "liability_insurance",
      "workers_comp",
      "safety_gear",
      "subcontractors_1099",
      "waste_disposal"
    ],
    "note": "Workers' compensation is the dominant insurance cost in roofing and is fully deductible. Fall-protection equipment is both a legal requirement and an ordinary business expense."
  },
  "welder": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "vehicle",
      "safety_gear",
      "certification_fees",
      "liability_insurance",
      "equipment_rental"
    ],
    "note": "Welding certifications have to be renewed and the renewal is deductible. Gas, rod and consumables are ordinary supplies; the machine itself is Section 179 property."
  },
  "auto_mechanic": {
    "keyDeductions": [
      "tools",
      "equipment",
      "shop_rent",
      "materials_and_supplies",
      "liability_insurance",
      "certification_fees",
      "uniforms",
      "waste_disposal"
    ],
    "note": "Tool debt is the defining feature of this trade. Tools bought on a truck account are deductible when you buy them, not when you finish paying for them, and the interest on the account is deductible separately."
  },
  "teacher_tutor": {
    "keyDeductions": [
      "educational_materials_books",
      "home_office_or_tutoring_space",
      "laptop",
      "software_subscriptions",
      "professional_development",
      "marketing",
      "mileage_if_in_person",
      "professional_memberships"
    ],
    "note": "The $300 educator expense deduction is for employed teachers in a school. If you teach for yourself — private tuition, online courses, music lessons — you are not limited to $300; you deduct the actual cost as a business expense, which is almost always more."
  },
  "musician": {
    "keyDeductions": [
      "instruments_section179",
      "equipment",
      "vehicle",
      "studio_rent",
      "marketing",
      "professional_development",
      "union_dues",
      "travel"
    ],
    "note": "Instruments are Section 179 property, and a professional instrument that also gets played at home is deductible at the business-use percentage. Touring costs are business travel; the meals within them are only half deductible."
  },
  "translator": {
    "keyDeductions": [
      "software_subscriptions",
      "computer",
      "home_office",
      "professional_development",
      "professional_memberships",
      "internet_pct",
      "reference_materials"
    ],
    "note": "Translation memory and terminology software are ordinary subscriptions. Certification through a professional body is deductible as maintaining an existing skill, provided you are already working in the field."
  },
  "videographer": {
    "keyDeductions": [
      "camera_lenses_section179",
      "lighting",
      "editing_software",
      "equipment",
      "vehicle",
      "studio_rent",
      "travel",
      "equipment_rental"
    ],
    "note": "Cameras, lenses, drones and lighting are Section 179 property at the business-use percentage. Hiring gear for a single shoot is deductible in full and avoids the business-use argument entirely."
  },
  "dog_groomer": {
    "keyDeductions": [
      "equipment",
      "supplies",
      "vehicle",
      "liability_insurance",
      "shop_rent",
      "certification_fees",
      "uniforms",
      "marketing"
    ],
    "note": "Mobile groomers deduct the van conversion as a vehicle improvement and depreciate it, while the grooming equipment inside is Section 179 property in its own right — two different treatments in the same vehicle."
  },
  "caterer": {
    "keyDeductions": [
      "food_and_ingredients",
      "equipment",
      "vehicle",
      "liability_insurance",
      "permits_and_licences",
      "staff_wages",
      "equipment_rental",
      "uniforms"
    ],
    "note": "Food bought for a job is cost of goods sold rather than a general expense, which matters for how it appears on your return. The 50% limit on business meals does not apply to it — that limit is about meals you eat, not food you sell."
  },
  "physician_practice": {
    "keyDeductions": [
      "malpractice_insurance",
      "medical_equipment",
      "office_rent_or_home_office",
      "staff_wages",
      "ehr_software",
      "licensing_fees_state",
      "continuing_education_cpe",
      "professional_memberships",
      "billing_service"
    ],
    "note": "Medicine is a specified service trade, so the qualified business income deduction is withdrawn above an income threshold rather than continuing. That single rule is worth more than most of the equipment on this list.",
    "sources": [
      {
        "claim": "Health is a specified service trade, so the deduction is withdrawn above the income threshold",
        "authority": "Reg. 1.199A-5(b)(2)(ii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "2026 thresholds: $201,750 single, $403,500 joint, phasing out over $75,000 and $150,000",
        "authority": "Rev. Proc. 2025-32 sec. 4.26",
        "url": "https://www.irs.gov/pub/irs-irbs/irb25-45.pdf",
        "confidence": "high"
      }
    ]
  },
  "dentist": {
    "keyDeductions": [
      "medical_equipment",
      "office_rent_or_home_office",
      "staff_wages",
      "malpractice_insurance",
      "lab_fees",
      "materials_and_supplies",
      "licensing_fees_state",
      "continuing_education_cpe",
      "practice_software"
    ],
    "note": "Dentistry is capital-heavy in a way most professional practices are not — chairs, imaging and a fit-out run to hundreds of thousands, and nearly all of it can be expensed rather than depreciated.",
    "sources": [
      {
        "claim": "Health is a specified service trade, so the deduction is withdrawn above the income threshold",
        "authority": "Reg. 1.199A-5(b)(2)(ii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "2026 thresholds: $201,750 single, $403,500 joint, phasing out over $75,000 and $150,000",
        "authority": "Rev. Proc. 2025-32 sec. 4.26",
        "url": "https://www.irs.gov/pub/irs-irbs/irb25-45.pdf",
        "confidence": "high"
      }
    ]
  },
  "veterinarian": {
    "keyDeductions": [
      "medical_equipment",
      "office_rent_or_home_office",
      "staff_wages",
      "malpractice_insurance",
      "drugs_and_supplies",
      "licensing_fees_state",
      "continuing_education_cpe",
      "practice_software",
      "waste_disposal"
    ],
    "note": "A veterinary practice sells goods as well as services — drugs, food and products are inventory with cost of goods sold against them, and that is a different calculation from an overhead.",
    "sources": [
      {
        "claim": "Veterinarians are within the health field for the qualified business income deduction",
        "authority": "Reg. 1.199A-5(b)(2)(ii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "chiropractor": {
    "keyDeductions": [
      "medical_equipment",
      "office_rent_or_home_office",
      "malpractice_insurance",
      "staff_wages",
      "licensing_fees_state",
      "continuing_education_cpe",
      "practice_software",
      "marketing"
    ],
    "note": "Small premises, expensive tables and a large marketing spend — chiropractic has a different cost shape from other health practices and the marketing is usually the biggest controllable line."
  },
  "aba_provider": {
    "keyDeductions": [
      "staff_wages",
      "malpractice_insurance",
      "office_rent_or_home_office",
      "ehr_software",
      "credentialing_fees",
      "materials_and_supplies",
      "mileage_or_travel",
      "continuing_education_cpe"
    ],
    "note": "Insurance credentialing and staff are the whole cost base, and clinicians who work in clients' homes make mileage a much larger deduction than in a clinic-based practice."
  },
  "home_health_agency": {
    "keyDeductions": [
      "staff_wages",
      "payroll_taxes",
      "liability_insurance",
      "workers_comp",
      "mileage_or_travel",
      "scheduling_software",
      "licensing_fees_state",
      "background_check_fees",
      "training_costs"
    ],
    "note": "Caregiver payroll is nearly the whole cost base, and home care has overtime rules of its own that decide what that payroll actually costs.",
    "sources": [
      {
        "claim": "The rule barring agencies from the companionship exemption is in force but unenforced pending a proposed rescission",
        "authority": "29 CFR 552.109; DOL FAB 2025-4; 90 FR 28976",
        "url": "https://www.federalregister.gov/documents/2025/07/02/2025-12316/application-of-the-fair-labor-standards-act-to-domestic-service",
        "confidence": "medium"
      }
    ]
  },
  "staffing_agency": {
    "keyDeductions": [
      "staff_wages",
      "payroll_taxes",
      "workers_comp",
      "liability_insurance",
      "recruitment_costs",
      "ats_software",
      "marketing",
      "background_check_fees",
      "professional_fees"
    ],
    "note": "You are the employer of record for people who work somewhere else entirely, which puts payroll, unemployment and workers' compensation on your return rather than the client's.",
    "sources": [
      {
        "claim": "A staffing firm that sources and refers candidates is not in the field of consulting",
        "authority": "Reg. 1.199A-5(b)(3) Example 9",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "medium"
      }
    ]
  },
  "attorney": {
    "keyDeductions": [
      "malpractice_insurance",
      "office_rent_or_home_office",
      "staff_wages",
      "research_subscriptions",
      "bar_dues",
      "continuing_education_cpe",
      "practice_software",
      "professional_memberships",
      "filing_fees"
    ],
    "note": "Client trust money is the line that matters most, and it is not income. Everything else on a law firm return is ordinary.",
    "sources": [
      {
        "claim": "Law is a specified service trade",
        "authority": "Reg. 1.199A-5(b)(2)(iii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "2026 thresholds: $201,750 single, $403,500 joint, phasing out over $75,000 and $150,000",
        "authority": "Rev. Proc. 2025-32 sec. 4.26",
        "url": "https://www.irs.gov/pub/irs-irbs/irb25-45.pdf",
        "confidence": "high"
      }
    ]
  },
  "tax_preparer": {
    "keyDeductions": [
      "practice_software",
      "professional_memberships",
      "continuing_education_cpe",
      "eo_insurance",
      "home_office",
      "licensing_fees_state",
      "marketing",
      "phone"
    ],
    "note": "Income arrives in four months and the costs run for twelve, which makes quarterly estimates awkward in a way that catches out the people who prepare them for everyone else.",
    "sources": [
      {
        "claim": "Accounting is a specified service trade",
        "authority": "Reg. 1.199A-5(b)(2)(iv)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "2026 thresholds: $201,750 single, $403,500 joint, phasing out over $75,000 and $150,000",
        "authority": "Rev. Proc. 2025-32 sec. 4.26",
        "url": "https://www.irs.gov/pub/irs-irbs/irb25-45.pdf",
        "confidence": "high"
      }
    ]
  },
  "financial_advisor": {
    "keyDeductions": [
      "compliance_costs",
      "eo_insurance",
      "crm_software",
      "research_subscriptions",
      "office_rent_or_home_office",
      "licensing_fees_state",
      "marketing",
      "professional_memberships",
      "staff_wages"
    ],
    "note": "Compliance is the cost that has no equivalent in other professions — registration, audits, archiving and supervision are all deductible and none of them are optional.",
    "sources": [
      {
        "claim": "Financial services, including wealth and retirement advice, is a specified service trade",
        "authority": "Reg. 1.199A-5(b)(2)(ix)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "2026 thresholds: $201,750 single, $403,500 joint, phasing out over $75,000 and $150,000",
        "authority": "Rev. Proc. 2025-32 sec. 4.26",
        "url": "https://www.irs.gov/pub/irs-irbs/irb25-45.pdf",
        "confidence": "high"
      }
    ]
  },
  "medical_billing": {
    "keyDeductions": [
      "practice_software",
      "staff_wages",
      "eo_insurance",
      "cyber_insurance",
      "home_office",
      "compliance_costs",
      "phone",
      "internet_pct"
    ],
    "note": "You handle protected health information for other people's patients, which brings security obligations that are both mandatory and deductible.",
    "sources": [
      {
        "claim": "Health excludes services not directly related to a medical field, naming payment processing",
        "authority": "Reg. 1.199A-5(b)(2)(ii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "medium"
      }
    ]
  },
  "architect": {
    "keyDeductions": [
      "professional_liability_insurance",
      "cad_software",
      "office_rent_or_home_office",
      "staff_wages",
      "licensing_fees_state",
      "continuing_education_cpe",
      "professional_memberships",
      "site_travel"
    ],
    "note": "Architecture is specifically excluded from the trades that lose the 20% business profit deduction at higher incomes — unlike law, accounting or medicine, it keeps it.",
    "sources": [
      {
        "claim": "Architecture is excluded from the specified service trades that lose the deduction at higher incomes",
        "authority": "IRC 199A(d)(2)(A); Reg. 1.199A-5(b)(1)",
        "url": "https://www.law.cornell.edu/uscode/text/26/199A",
        "confidence": "high"
      }
    ]
  },
  "engineer": {
    "keyDeductions": [
      "professional_liability_insurance",
      "cad_software",
      "equipment",
      "office_rent_or_home_office",
      "staff_wages",
      "licensing_fees_state",
      "continuing_education_cpe",
      "site_travel"
    ],
    "note": "Engineering shares architecture's statutory exception: it keeps the 20% business profit deduction at incomes where most professional practices lose it.",
    "sources": [
      {
        "claim": "Engineering is excluded from the specified service trades that lose the deduction at higher incomes",
        "authority": "IRC 199A(d)(2)(A); Reg. 1.199A-5(b)(1)",
        "url": "https://www.law.cornell.edu/uscode/text/26/199A",
        "confidence": "high"
      }
    ]
  },
  "interior_designer": {
    "keyDeductions": [
      "design_software",
      "materials_and_supplies",
      "vehicle",
      "marketing_photography",
      "liability_insurance",
      "home_office",
      "trade_show_travel",
      "staff_wages"
    ],
    "note": "Whether you buy furnishings and resell them or take a commission changes the whole shape of the return, and most designers do both without separating them."
  },
  "home_stager": {
    "keyDeductions": [
      "furniture_inventory",
      "storage_yard_rent",
      "vehicle",
      "liability_insurance",
      "marketing_photography",
      "staff_wages",
      "equipment_rental",
      "insurance"
    ],
    "note": "The furniture is the business, and whether it is inventory or a depreciable asset depends on whether you rent it out or sell it."
  },
  "marketing_agency": {
    "keyDeductions": [
      "advertising_spend_passthrough",
      "software_subscriptions",
      "staff_wages",
      "contractor_subcontractors",
      "office_rent_or_home_office",
      "professional_development",
      "marketing"
    ],
    "note": "Client ad spend passing through your account is the number that makes an agency look ten times its size, and it is both income and a deduction.",
    "sources": [
      {
        "claim": "Consulting means providing professional advice and counsel; the reputation catch-all is narrow",
        "authority": "Reg. 1.199A-5(b)(2)(vii), (b)(2)(xiv)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "medium"
      }
    ]
  },
  "seo_consultant": {
    "keyDeductions": [
      "software_subscriptions",
      "research_subscriptions",
      "home_office",
      "computer",
      "professional_development",
      "internet_pct",
      "marketing",
      "contractor_subcontractors"
    ],
    "note": "Tooling is the whole overhead, and it is unusually expensive — enterprise SEO platforms cost more per month than most consultants' rent.",
    "sources": [
      {
        "claim": "Consulting means providing professional advice and counsel",
        "authority": "Reg. 1.199A-5(b)(2)(vii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "medium"
      }
    ]
  },
  "podcaster": {
    "keyDeductions": [
      "recording_equipment",
      "editing_software",
      "studio_rent",
      "hosting_fees",
      "marketing",
      "contractor_subcontractors",
      "travel",
      "home_office"
    ],
    "note": "Sponsorship income arrives before the episodes run, and the equipment is Section 179 property at the business-use percentage."
  },
  "writer_author": {
    "keyDeductions": [
      "research_subscriptions",
      "home_office",
      "computer",
      "professional_memberships",
      "travel",
      "marketing",
      "professional_fees",
      "software_subscriptions"
    ],
    "note": "Royalties and advances are taxed differently from a fee for work, and an advance is income when you receive it rather than when the book earns out.",
    "sources": [
      {
        "claim": "Qualified creative expenses of an individual are exempt from uniform capitalisation, but printing, plates and film are not",
        "authority": "IRC 263A(h)",
        "url": "https://www.law.cornell.edu/uscode/text/26/263A",
        "confidence": "high"
      }
    ]
  },
  "actor_performer": {
    "keyDeductions": [
      "agent_commission",
      "headshots",
      "training_classes",
      "union_dues",
      "travel",
      "wardrobe_if_required",
      "professional_memberships",
      "marketing"
    ],
    "note": "Agent and manager commissions come off the top and are fully deductible, and classes are deductible once you are working rather than training to start.",
    "sources": [
      {
        "claim": "The qualified performing artist deduction is above the line, with a $16,000 AGI limit that is not indexed",
        "authority": "IRC 62(a)(2)(B), 62(b)",
        "url": "https://www.irs.gov/instructions/i2106",
        "confidence": "medium"
      }
    ]
  },
  "professional_speaker": {
    "keyDeductions": [
      "travel",
      "marketing_photography",
      "website",
      "professional_memberships",
      "home_office",
      "equipment",
      "professional_development",
      "contractor_subcontractors"
    ],
    "note": "Speaking in many states creates tax obligations in many states, and some withhold from the fee before it reaches you.",
    "sources": [
      {
        "claim": "The reputation-or-skill rule reaches endorsement fees, appearance fees and licensing your name or likeness — not fees generally",
        "authority": "Reg. 1.199A-5(b)(2)(xiv)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "conference_organizer": {
    "keyDeductions": [
      "venue_costs",
      "vendor_deposits_if_direct_billed",
      "marketing",
      "staff_wages",
      "equipment_rental",
      "insurance",
      "software_subscriptions",
      "travel"
    ],
    "note": "Tickets sell a year ahead and costs land in one week, so the money and the event routinely fall in different tax years."
  },
  "travel_agent": {
    "keyDeductions": [
      "host_agency_fees",
      "crm_software",
      "marketing",
      "professional_memberships",
      "travel",
      "home_office",
      "errors_omissions_insurance",
      "phone"
    ],
    "note": "Client money for trips is not your income — only the commission is, and it is often paid long after the booking."
  },
  "tour_operator": {
    "keyDeductions": [
      "vendor_deposits_if_direct_billed",
      "liability_insurance",
      "guides_and_staff",
      "equipment",
      "vehicle",
      "permits_and_licences",
      "marketing",
      "training_costs"
    ],
    "note": "You carry the liability and the deposits, which makes insurance the defining cost and deferred money the defining trap."
  },
  "restaurant_owner": {
    "keyDeductions": [
      "food_and_ingredients",
      "staff_wages",
      "payroll_taxes",
      "rent",
      "equipment",
      "liability_insurance",
      "permits_and_licences",
      "utilities",
      "marketing"
    ],
    "note": "Tips create a payroll tax credit most owners never claim, and food is cost of goods rather than an ordinary expense.",
    "sources": [
      {
        "claim": "Employers may claim a credit for FICA paid on reported tips, on Form 8846",
        "authority": "IRC 45B",
        "url": "https://www.law.cornell.edu/uscode/text/26/45B",
        "confidence": "high"
      },
      {
        "claim": "Meals furnished to employees for the employer's convenience are not deductible from 2026",
        "authority": "IRC 274(o)",
        "url": "https://www.law.cornell.edu/uscode/text/26/274",
        "confidence": "high"
      }
    ]
  },
  "food_truck": {
    "keyDeductions": [
      "food_and_ingredients",
      "fuel",
      "vehicle",
      "permits_and_licences",
      "equipment",
      "commissary_rent",
      "liability_insurance",
      "staff_wages"
    ],
    "note": "The truck is both your vehicle and your kitchen, and the two halves are deducted in completely different ways.",
    "sources": [
      {
        "claim": "Meals furnished to employees for the employer's convenience are not deductible from 2026",
        "authority": "IRC 274(o)",
        "url": "https://www.law.cornell.edu/uscode/text/26/274",
        "confidence": "high"
      }
    ]
  },
  "hotel_owner": {
    "keyDeductions": [
      "staff_wages",
      "utilities",
      "property_insurance",
      "repairs_and_maintenance",
      "furnishings",
      "property_tax",
      "marketing",
      "software_subscriptions",
      "supplies"
    ],
    "note": "The building is the asset, and a cost segregation study can move millions of its cost into far shorter depreciation lives.",
    "sources": [
      {
        "claim": "Bonus depreciation is 100% for property placed in service in 2026, on components with recovery periods of 20 years or less",
        "authority": "IRC 168(k), as amended by P.L. 119-21 sec. 70301",
        "url": "https://www.law.cornell.edu/uscode/text/26/168",
        "confidence": "high"
      },
      {
        "claim": "Nonresidential real property depreciates over 39 years",
        "authority": "IRC 168(c)",
        "url": "https://www.law.cornell.edu/uscode/text/26/168",
        "confidence": "high"
      }
    ]
  },
  "str_host_business": {
    "keyDeductions": [
      "mortgage_interest",
      "property_tax",
      "cleaning_and_turnover",
      "furnishings",
      "property_insurance",
      "utilities",
      "platform_fees",
      "repairs_and_maintenance",
      "software_subscriptions"
    ],
    "note": "Average stays of seven days or less take a rental outside the passive rules, which is the difference between losses you can use now and losses you cannot.",
    "sources": [
      {
        "claim": "Average guest stays of seven days or fewer take the activity outside the passive rental rules",
        "authority": "Reg. 1.469-1T(e)(3)(ii)(A)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.469-1T",
        "confidence": "high"
      },
      {
        "claim": "Being non-passive does not by itself make the income subject to self-employment tax",
        "authority": "IRC 1402(a)(1); Reg. 1.1402(a)-4(c)(2)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1402",
        "confidence": "high"
      }
    ]
  },
  "ecommerce_seller": {
    "keyDeductions": [
      "inventory_cogs",
      "platform_fees",
      "shipping_costs",
      "advertising_spend_passthrough",
      "software_subscriptions",
      "storage_warehousing",
      "packaging",
      "returns_and_refunds"
    ],
    "note": "Your 1099-K reports what came in, not what you made, and the gap between the two is most of the return."
  },
  "import_export": {
    "keyDeductions": [
      "inventory_cogs",
      "customs_duties",
      "freight_costs",
      "warehousing",
      "liability_insurance",
      "customs_broker_fees",
      "currency_costs",
      "travel"
    ],
    "note": "Duties and freight are part of what the goods cost you, not a separate expense, and that changes when you get relief for them."
  },
  "freight_broker": {
    "keyDeductions": [
      "carrier_payments",
      "bond_costs",
      "liability_insurance",
      "tms_software",
      "staff_wages",
      "marketing",
      "factoring_fees",
      "licensing_fees_state"
    ],
    "note": "Carrier payments run through your books at close to the value of the freight, so gross receipts look nothing like the margin."
  },
  "courier_service": {
    "keyDeductions": [
      "vehicle",
      "fuel",
      "liability_insurance",
      "driver_wages",
      "maintenance",
      "phone",
      "routing_software",
      "permits_and_licences"
    ],
    "note": "Once you have more than one van the drivers are almost certainly employees, and that decides most of the return."
  },
  "limo_service": {
    "keyDeductions": [
      "vehicle",
      "fuel",
      "driver_wages",
      "liability_insurance",
      "maintenance",
      "permits_and_licences",
      "booking_software",
      "detailing"
    ],
    "note": "Passenger vehicles carry heavier insurance and licensing than freight, and the annual depreciation caps that hobble ordinary cars do not apply to the larger vehicles.",
    "sources": [
      {
        "claim": "The passenger-automobile depreciation caps apply only to vehicles rated at 6,000 lb or less, and not to vehicles used in the business of transporting people for hire",
        "authority": "IRC 280F(d)(5)",
        "url": "https://www.law.cornell.edu/uscode/text/26/280F",
        "confidence": "high"
      }
    ]
  },
  "property_flipper": {
    "keyDeductions": [
      "purchase_cogs",
      "renovation_costs",
      "holding_costs",
      "loan_interest",
      "liability_insurance",
      "contractor_payments",
      "permits_and_licences",
      "marketing"
    ],
    "note": "Flipping is a trade, not an investment: the profit is ordinary income with self-employment tax on it, and none of the capital gains treatment applies.",
    "sources": [
      {
        "claim": "Property held for sale to customers is not a capital asset, so no long-term rates and no like-kind exchange",
        "authority": "IRC 1221(a)(1); IRC 1031(a)(2)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1221",
        "confidence": "high"
      },
      {
        "claim": "Dealer status is decided property by property on the facts",
        "authority": "Malat v. Riddell, 383 U.S. 569 (1966)",
        "url": "https://www.law.cornell.edu/supremecourt/text/383/569",
        "confidence": "high"
      }
    ]
  },
  "car_dealership": {
    "keyDeductions": [
      "inventory_cogs",
      "floor_plan_interest",
      "lot_rent",
      "staff_wages",
      "liability_insurance",
      "reconditioning",
      "advertising",
      "licensing_fees_state"
    ],
    "note": "Floor plan interest has a statutory carve-out from the limit on deducting business interest, which no other inventory-financed business gets.",
    "sources": [
      {
        "claim": "Floor plan financing interest is added to the business interest limitation, but taking it denies bonus depreciation",
        "authority": "IRC 163(j)(1)(C), 163(j)(9); IRC 168(k)(9)(B)",
        "url": "https://www.law.cornell.edu/uscode/text/26/163",
        "confidence": "high"
      }
    ]
  },
  "body_shop": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "shop_rent",
      "staff_wages",
      "liability_insurance",
      "waste_disposal",
      "certification_fees",
      "paint_and_consumables"
    ],
    "note": "Insurance pays most of your invoices, and equipment certification is what keeps you on the approved lists that generate the work."
  },
  "security_company": {
    "keyDeductions": [
      "guard_wages",
      "payroll_taxes",
      "workers_comp",
      "liability_insurance",
      "uniforms",
      "vehicle",
      "licensing_fees_state",
      "training_costs",
      "equipment"
    ],
    "note": "Guard payroll is the business, and armed work carries insurance and licensing costs that unarmed work does not."
  },
  "private_investigator": {
    "keyDeductions": [
      "licensing_fees_state",
      "liability_insurance",
      "surveillance_equipment",
      "vehicle",
      "database_subscriptions",
      "home_office",
      "phone",
      "professional_development"
    ],
    "note": "Database subscriptions and a surveillance vehicle are the two costs that have no equivalent in other service businesses."
  },
  "winery_brewery": {
    "keyDeductions": [
      "equipment",
      "inventory_cogs",
      "excise_tax",
      "licensing_fees_state",
      "staff_wages",
      "packaging",
      "utilities",
      "tasting_room_costs",
      "marketing"
    ],
    "note": "Federal excise tax is owed on what you produce, separately from income tax, and a reduced rate applies to smaller producers.",
    "sources": [
      {
        "claim": "Excise tax is determined on removal from bonded premises, not on production",
        "authority": "IRC 5054(a)",
        "url": "https://www.law.cornell.edu/uscode/text/26/5054",
        "confidence": "medium"
      },
      {
        "claim": "Reduced beer rates and wine tax credits by production volume",
        "authority": "IRC 5051(a); IRC 5041(b)-(c)",
        "url": "https://www.law.cornell.edu/uscode/text/26/5051",
        "confidence": "medium"
      }
    ]
  },
  "cannabis_business": {
    "keyDeductions": [
      "inventory_cogs",
      "staff_wages",
      "licensing_fees_state",
      "security_costs",
      "compliance_costs",
      "rent",
      "utilities",
      "equipment"
    ],
    "note": "Section 280E denies every ordinary business deduction to a cannabis business. Only cost of goods sold survives, which makes this the most punitive tax position in the code.",
    "sources": [
      {
        "claim": "Marijuana under a state medical licence, and in FDA-approved products, moved to Schedule III on 28 April 2026",
        "authority": "21 CFR 1308.13(g); 91 FR 22714",
        "url": "https://www.federalregister.gov/documents/full_text/text/2026/04/28/2026-08176.txt",
        "confidence": "high"
      },
      {
        "claim": "Section 280E denies deductions and credits, but not cost of goods sold, and reaches Schedule I and II only",
        "authority": "IRC 280E",
        "url": "https://www.law.cornell.edu/uscode/text/26/280E",
        "confidence": "high"
      },
      {
        "claim": "New York, California and Colorado decouple from 280E on the state return",
        "authority": "NY Tax Law 612(c)(46); Cal. Rev. & Tax. Code 17209; Colo. Rev. Stat. 39-22-104(4)(t)",
        "url": "https://www.tax.ny.gov/forms/html-instructions/2025/ct/ct225-225ai-2025.htm",
        "confidence": "high"
      }
    ]
  },
  "mining_operator": {
    "keyDeductions": [
      "equipment",
      "depletion",
      "permits_and_licences",
      "staff_wages",
      "fuel",
      "reclamation_costs",
      "liability_insurance",
      "exploration_costs"
    ],
    "note": "Depletion has no equivalent in any other industry: you deduct a share of revenue for the resource itself, sometimes beyond what you paid for it.",
    "sources": [
      {
        "claim": "Percentage depletion is computed on gross income from the property, capped at 50% of taxable income from it",
        "authority": "IRC 613(a), 613(b)",
        "url": "https://www.law.cornell.edu/uscode/text/26/613",
        "confidence": "high"
      },
      {
        "claim": "The exploration election cannot be revoked without IRS consent, and is recaptured when the mine reaches producing stage",
        "authority": "IRC 617(a)-(d)",
        "url": "https://www.law.cornell.edu/uscode/text/26/617",
        "confidence": "high"
      }
    ]
  },
  "print_shop": {
    "keyDeductions": [
      "equipment",
      "inventory_cogs",
      "materials_and_supplies",
      "staff_wages",
      "shop_rent",
      "software_subscriptions",
      "waste_disposal",
      "vehicle"
    ],
    "note": "Presses and wide-format machines are the capital, and the substrate stock behind them is inventory rather than an expense."
  },
  "event_rental": {
    "keyDeductions": [
      "equipment",
      "storage_yard_rent",
      "vehicle",
      "liability_insurance",
      "staff_wages",
      "maintenance",
      "repairs_and_maintenance",
      "software_subscriptions"
    ],
    "note": "Your stock is not sold, it is hired out repeatedly — so it is depreciable equipment rather than inventory."
  },
  "mobile_mechanic": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "materials_and_supplies",
      "liability_insurance",
      "phone",
      "equipment",
      "certification_fees",
      "fuel"
    ],
    "note": "The van is a workshop that drives, which makes both the vehicle rules and Section 179 apply to the same asset in different parts."
  },
  "nursing_agency": {
    "keyDeductions": [
      "staff_wages",
      "payroll_taxes",
      "workers_comp",
      "malpractice_insurance",
      "credentialing_fees",
      "background_check_fees",
      "scheduling_software",
      "recruitment_costs"
    ],
    "note": "You carry the payroll and the malpractice exposure for clinicians working in someone else's facility."
  },
  "locksmith": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "materials_and_supplies",
      "licensing_fees_state",
      "liability_insurance",
      "equipment",
      "phone",
      "background_check_fees"
    ],
    "note": "Key stock and blanks are inventory rather than an expense, and licensing plus a background check is a condition of trading in most states."
  },
  "pest_control": {
    "keyDeductions": [
      "materials_and_supplies",
      "vehicle",
      "licensing_fees_state",
      "liability_insurance",
      "equipment",
      "continuing_education",
      "uniforms",
      "waste_disposal"
    ],
    "note": "Chemicals are regulated and so is the applicator, so licensing and continuing education are recurring deductible costs rather than one-offs."
  },
  "pool_service": {
    "keyDeductions": [
      "materials_and_supplies",
      "vehicle",
      "equipment",
      "liability_insurance",
      "licensing_fees_state",
      "phone",
      "routing_software",
      "uniforms"
    ],
    "note": "Chemicals are supplies, route density decides profitability, and in most of the country the work is seasonal enough to distort quarterly estimates."
  },
  "tree_service": {
    "keyDeductions": [
      "equipment",
      "vehicle",
      "liability_insurance",
      "workers_comp",
      "safety_gear",
      "certification_fees",
      "equipment_rental",
      "waste_disposal"
    ],
    "note": "Insurance is the dominant cost and the barrier to entry, and the equipment is expensive enough that Section 179 changes the tax on a good year."
  },
  "snow_removal": {
    "keyDeductions": [
      "equipment",
      "vehicle",
      "fuel",
      "liability_insurance",
      "materials_and_supplies",
      "seasonal_labour",
      "storage_yard_rent",
      "maintenance"
    ],
    "note": "Seasonal contracts are often paid before it snows, which puts the income and the work in different tax years."
  },
  "junk_removal": {
    "keyDeductions": [
      "vehicle",
      "fuel",
      "waste_disposal",
      "staff_wages",
      "liability_insurance",
      "equipment",
      "marketing",
      "permits_and_licences"
    ],
    "note": "Tipping fees are the largest variable cost and are deductible in full; anything you resell instead of dumping is income."
  },
  "moving_company": {
    "keyDeductions": [
      "vehicle",
      "fuel",
      "staff_wages",
      "liability_insurance",
      "workers_comp",
      "equipment",
      "permits_and_licences",
      "packing_materials"
    ],
    "note": "Interstate moving is federally regulated, and valuation coverage you sell to customers is income rather than a pass-through."
  },
  "tow_truck": {
    "keyDeductions": [
      "vehicle",
      "fuel",
      "liability_insurance",
      "maintenance",
      "permits_and_licences",
      "storage_yard_rent",
      "staff_wages",
      "equipment"
    ],
    "note": "Storage fees on impounded vehicles accrue as income before anyone pays them, and the truck is heavy enough to escape the passenger-car depreciation caps."
  },
  "auto_detailer": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment",
      "vehicle",
      "liability_insurance",
      "marketing",
      "water_and_utilities",
      "booking_software",
      "uniforms"
    ],
    "note": "Mobile and shop detailing have different cost shapes, and the chemicals are supplies rather than inventory in most operations."
  },
  "marine_mechanic": {
    "keyDeductions": [
      "tools",
      "equipment",
      "vehicle",
      "materials_and_supplies",
      "liability_insurance",
      "certification_fees",
      "shop_rent",
      "waste_disposal"
    ],
    "note": "Seasonality is extreme in most of the country, and marine environmental rules make waste handling a real cost."
  },
  "rv_repair": {
    "keyDeductions": [
      "tools",
      "equipment",
      "vehicle",
      "materials_and_supplies",
      "liability_insurance",
      "certification_fees",
      "shop_rent",
      "training_costs"
    ],
    "note": "An RV is a vehicle, a building and a set of appliances at once, which means certifications in several trades and parts inventory across all of them."
  },
  "small_engine_repair": {
    "keyDeductions": [
      "tools",
      "equipment",
      "materials_and_supplies",
      "shop_rent",
      "liability_insurance",
      "vehicle",
      "waste_disposal",
      "marketing"
    ],
    "note": "Parts inventory across many manufacturers is the working capital, and it is not deductible until it is fitted."
  },
  "bike_shop": {
    "keyDeductions": [
      "inventory_cogs",
      "shop_rent",
      "staff_wages",
      "tools",
      "liability_insurance",
      "marketing",
      "software_subscriptions",
      "utilities"
    ],
    "note": "Bikes are inventory with a long shelf life and model-year obsolescence, and the service side is a different business from the sales side."
  },
  "motorcycle_repair": {
    "keyDeductions": [
      "tools",
      "equipment",
      "materials_and_supplies",
      "shop_rent",
      "liability_insurance",
      "certification_fees",
      "waste_disposal",
      "marketing"
    ],
    "note": "Specialist tooling per manufacturer is expensive and deductible in the year bought, and the season is short in most states."
  },
  "upholsterer": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment",
      "shop_rent",
      "tools",
      "vehicle",
      "liability_insurance",
      "marketing",
      "inventory_cogs"
    ],
    "note": "Fabric bought for a specific job is cost of goods; fabric bought for stock is inventory until used."
  },
  "tailor": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment",
      "shop_rent",
      "home_office",
      "marketing",
      "inventory_cogs",
      "software_subscriptions",
      "professional_development"
    ],
    "note": "Alterations are almost pure service with negligible stock; making garments makes you a manufacturer with inventory."
  },
  "dry_cleaner": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "shop_rent",
      "staff_wages",
      "utilities",
      "liability_insurance",
      "waste_disposal",
      "environmental_compliance"
    ],
    "note": "Solvent handling is an environmental compliance cost with its own permits, and the machines are the capital."
  },
  "laundromat": {
    "keyDeductions": [
      "equipment",
      "utilities",
      "shop_rent",
      "maintenance",
      "liability_insurance",
      "staff_wages",
      "marketing",
      "software_subscriptions"
    ],
    "note": "It is an equipment business with almost no stock — the washers are the asset and the utilities are the cost."
  },
  "car_wash": {
    "keyDeductions": [
      "equipment",
      "utilities",
      "materials_and_supplies",
      "staff_wages",
      "shop_rent",
      "maintenance",
      "liability_insurance",
      "marketing"
    ],
    "note": "The tunnel and the water reclamation plant are the capital, and a great deal of it depreciates much faster than the building."
  },
  "home_inspector": {
    "keyDeductions": [
      "eo_insurance",
      "equipment",
      "vehicle",
      "licensing_fees_state",
      "software_subscriptions",
      "continuing_education",
      "marketing",
      "professional_memberships"
    ],
    "note": "Professional indemnity cover is effectively mandatory and the tail on it matters, because claims arrive years after the inspection."
  },
  "land_surveyor": {
    "keyDeductions": [
      "equipment",
      "professional_liability_insurance",
      "vehicle",
      "cad_software",
      "licensing_fees_state",
      "staff_wages",
      "continuing_education",
      "site_travel"
    ],
    "note": "Instruments are extremely expensive and are Section 179 property, and licensing is per state for anyone working near a border."
  },
  "appraiser": {
    "keyDeductions": [
      "eo_insurance",
      "software_subscriptions",
      "vehicle",
      "licensing_fees_state",
      "continuing_education",
      "home_office",
      "marketing",
      "research_subscriptions"
    ],
    "note": "Almost pure service with a home office and a car, and licensing that runs per state with continuing education attached."
  },
  "mortgage_broker": {
    "keyDeductions": [
      "crm_software",
      "marketing",
      "licensing_fees_state",
      "eo_insurance",
      "home_office",
      "lead_generation_costs",
      "continuing_education",
      "professional_memberships"
    ],
    "note": "Commission arrives at closing rather than at application, and lead spend is the largest thing you control."
  },
  "title_agent": {
    "keyDeductions": [
      "eo_insurance",
      "software_subscriptions",
      "staff_wages",
      "office_rent_or_home_office",
      "licensing_fees_state",
      "research_subscriptions",
      "marketing",
      "bond_costs"
    ],
    "note": "Escrow money is never yours and never touches your return, and the underwriter's share of the premium is not your income either."
  },
  "property_manager": {
    "keyDeductions": [
      "software_subscriptions",
      "staff_wages",
      "eo_insurance",
      "vehicle",
      "licensing_fees_state",
      "marketing",
      "office_rent_or_home_office",
      "professional_memberships"
    ],
    "note": "Rent you collect is the owner's money, not yours — only the management fee is income, and mixing the two is both a tax and a licensing problem."
  },
  "grant_writer": {
    "keyDeductions": [
      "research_subscriptions",
      "home_office",
      "computer",
      "professional_development",
      "professional_memberships",
      "software_subscriptions",
      "marketing",
      "internet_pct"
    ],
    "note": "Success fees on grant applications are prohibited by most funders, which shapes how you can be paid and therefore when you are taxed."
  },
  "technical_writer": {
    "keyDeductions": [
      "software_subscriptions",
      "computer",
      "home_office",
      "professional_development",
      "professional_memberships",
      "internet_pct",
      "research_subscriptions",
      "marketing"
    ],
    "note": "Nearly all overhead is software and a home office, and long contracts make the employee-or-contractor question live."
  },
  "college_consultant": {
    "keyDeductions": [
      "software_subscriptions",
      "home_office",
      "professional_development",
      "professional_memberships",
      "marketing",
      "travel",
      "research_subscriptions",
      "phone"
    ],
    "note": "Packages sold for a whole application cycle are income when paid, even though the work runs across two tax years."
  },
  "music_teacher": {
    "keyDeductions": [
      "instruments_section179",
      "home_office_or_tutoring_space",
      "educational_materials_books",
      "marketing",
      "professional_memberships",
      "software_subscriptions",
      "mileage_if_in_person",
      "equipment"
    ],
    "note": "Teaching from home makes the studio the largest deduction; travelling to students makes it mileage instead."
  },
  "dj": {
    "keyDeductions": [
      "equipment",
      "music_subscriptions",
      "vehicle",
      "liability_insurance",
      "marketing",
      "software_subscriptions",
      "travel",
      "insurance"
    ],
    "note": "Equipment is Section 179 property and music licensing is an ongoing subscription rather than a purchase."
  },
  "wedding_officiant": {
    "keyDeductions": [
      "travel",
      "marketing",
      "professional_development",
      "home_office",
      "licensing_fees_state",
      "professional_memberships",
      "phone",
      "software_subscriptions"
    ],
    "note": "A small, high-margin business with almost no overhead, where travel and registration are most of the deduction."
  },
  "personal_chef": {
    "keyDeductions": [
      "food_and_ingredients",
      "equipment",
      "vehicle",
      "liability_insurance",
      "permits_and_licences",
      "marketing",
      "uniforms",
      "software_subscriptions"
    ],
    "note": "Groceries bought for a client are cost of goods, not the 50% meals limit — that limit is about meals you eat."
  },
  "drone_operator": {
    "keyDeductions": [
      "equipment",
      "software_subscriptions",
      "liability_insurance",
      "licensing_fees_state",
      "training_costs",
      "vehicle",
      "marketing",
      "computer"
    ],
    "note": "The aircraft is Section 179 property and commercial flight requires a federal certificate that is deductible to obtain and renew."
  },
  "it_consultant": {
    "keyDeductions": [
      "software_subscriptions",
      "equipment",
      "staff_wages",
      "cyber_insurance",
      "home_office",
      "professional_development",
      "marketing",
      "contractor_subcontractors"
    ],
    "note": "Software you resell to clients is income before it is a deduction, and it can make a small business look several times its size."
  },
  "cybersecurity_consultant": {
    "keyDeductions": [
      "software_subscriptions",
      "equipment",
      "professional_development",
      "certification_fees",
      "eo_insurance",
      "home_office",
      "travel",
      "research_subscriptions"
    ],
    "note": "Certifications are the credential and they expire, so renewal and the education behind it is a recurring deductible cost."
  },
  "court_reporter": {
    "keyDeductions": [
      "equipment",
      "software_subscriptions",
      "certification_fees",
      "home_office",
      "continuing_education",
      "vehicle",
      "professional_memberships",
      "materials_and_supplies"
    ],
    "note": "The stenotype and CAT software are the capital, and transcript income arrives long after the proceeding."
  },
  "sign_language_interpreter": {
    "keyDeductions": [
      "certification_fees",
      "continuing_education",
      "vehicle",
      "professional_memberships",
      "home_office",
      "software_subscriptions",
      "phone",
      "professional_development"
    ],
    "note": "Assignments are scattered, so mileage is a much larger deduction than the low overhead suggests."
  },
  "process_server": {
    "keyDeductions": [
      "vehicle",
      "licensing_fees_state",
      "liability_insurance",
      "database_subscriptions",
      "equipment",
      "phone",
      "software_subscriptions",
      "bond_costs"
    ],
    "note": "Mileage is the business, and skip-trace databases are the overhead nobody outside the trade expects."
  },
  "bail_bondsman": {
    "keyDeductions": [
      "licensing_fees_state",
      "liability_insurance",
      "staff_wages",
      "software_subscriptions",
      "vehicle",
      "marketing",
      "professional_fees",
      "database_subscriptions"
    ],
    "note": "Collateral held is not income, and forfeitures are deductible when paid rather than when the defendant fails to appear."
  },
  "auctioneer": {
    "keyDeductions": [
      "licensing_fees_state",
      "marketing",
      "staff_wages",
      "venue_costs",
      "software_subscriptions",
      "liability_insurance",
      "vehicle",
      "equipment"
    ],
    "note": "Hammer price collected for a consignor is not your income — only commission and buyer's premium are."
  },
  "jeweler": {
    "keyDeductions": [
      "inventory_cogs",
      "equipment",
      "shop_rent",
      "liability_insurance",
      "materials_and_supplies",
      "marketing",
      "staff_wages",
      "security_costs"
    ],
    "note": "Stock is capital tied up in metal and stones, and none of it is deductible until it sells."
  },
  "printing_3d": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "software_subscriptions",
      "shop_rent",
      "utilities",
      "marketing",
      "computer",
      "waste_disposal"
    ],
    "note": "Printers are Section 179 property and resin and filament are supplies, but a print that fails is a cost with nothing to show for it."
  },
  "landlord_residential": {
    "keyDeductions": [
      "mortgage_interest",
      "property_tax",
      "repairs_and_maintenance",
      "property_insurance",
      "depreciation",
      "property_manager_fees",
      "utilities",
      "legal_and_professional"
    ],
    "note": "Rental losses are passive by default and cannot offset wages, with two exits: a $25,000 allowance that phases out, and real estate professional status.",
    "sources": [
      {
        "claim": "Passive losses: the $25,000 allowance, active participation, and the $100,000 to $150,000 phase-out",
        "authority": "IRC 469(i)(1)-(3)",
        "url": "https://www.law.cornell.edu/uscode/text/26/469",
        "confidence": "high"
      },
      {
        "claim": "Real estate professional status: over half your personal services and more than 750 hours, with material participation still tested per property",
        "authority": "IRC 469(c)(7); Reg. 1.469-9(e), (g)",
        "url": "https://www.law.cornell.edu/uscode/text/26/469",
        "confidence": "high"
      },
      {
        "claim": "Residential rental property depreciates over 27.5 years",
        "authority": "IRC 168(c)",
        "url": "https://www.law.cornell.edu/uscode/text/26/168",
        "confidence": "high"
      }
    ]
  },
  "daycare_provider": {
    "keyDeductions": [
      "home_office_or_tutoring_space",
      "food_and_ingredients",
      "materials_and_supplies",
      "licensing_fees_state",
      "liability_insurance",
      "training_costs",
      "equipment",
      "background_check_fees"
    ],
    "note": "Daycare is the one business exempted from the exclusive-use rule for a home office, and it can use standard meal rates instead of food receipts.",
    "sources": [
      {
        "claim": "Daycare is exempt from the exclusive-use requirement, computed on space and hours, and conditional on state licensing",
        "authority": "IRC 280A(c)(4)",
        "url": "https://www.law.cornell.edu/uscode/text/26/280A",
        "confidence": "high"
      },
      {
        "claim": "Standard meal and snack rates may replace actual food costs",
        "authority": "Rev. Proc. 2003-22; IRS Pub. 587",
        "url": "https://www.irs.gov/publications/p587",
        "confidence": "medium"
      }
    ]
  },
  "household_employer": {
    "keyDeductions": [
      "staff_wages",
      "payroll_taxes",
      "payroll_service",
      "workers_comp",
      "background_check_fees",
      "recruitment_costs",
      "insurance",
      "professional_fees"
    ],
    "note": "Paying someone to work in your home makes you an employer with payroll obligations, filed on your own tax return rather than a business one.",
    "sources": [
      {
        "claim": "Household employment: the 2026 cash wage threshold, the rates and Schedule H",
        "authority": "IRC 3121(a)(7)(B), (x); IRS Pub. 926",
        "url": "https://www.irs.gov/publications/p926",
        "confidence": "high"
      }
    ]
  },
  "horse_business": {
    "keyDeductions": [
      "feed_and_bedding",
      "veterinary_costs",
      "equipment",
      "facility_rent",
      "staff_wages",
      "liability_insurance",
      "vehicle",
      "training_costs"
    ],
    "note": "Horses get their own hobby-loss test — two profitable years in seven rather than three in five — because the tax code expects them to lose money for longer.",
    "sources": [
      {
        "claim": "The profit presumption is 3 years in 5, and 2 in 7 for breeding, training, showing or racing horses",
        "authority": "IRC 183(d)",
        "url": "https://www.law.cornell.edu/uscode/text/26/183",
        "confidence": "high"
      }
    ]
  },
  "oil_gas_operator": {
    "keyDeductions": [
      "idc_costs",
      "depletion",
      "equipment",
      "liability_insurance",
      "operating_costs",
      "professional_fees",
      "permits_and_licences",
      "reclamation_costs"
    ],
    "note": "A working interest is excluded from the passive loss rules entirely, which no other investment of comparable passivity is.",
    "sources": [
      {
        "claim": "A working interest is not a passive activity where the form of ownership does not limit liability",
        "authority": "IRC 469(c)(3)",
        "url": "https://www.law.cornell.edu/uscode/text/26/469",
        "confidence": "high"
      },
      {
        "claim": "Intangible drilling costs may be expensed by election, made on the first return and binding thereafter",
        "authority": "IRC 263(c); Reg. 1.612-4",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.612-4",
        "confidence": "high"
      },
      {
        "claim": "Percentage depletion is computed on gross income from the property",
        "authority": "IRC 613",
        "url": "https://www.law.cornell.edu/uscode/text/26/613",
        "confidence": "high"
      }
    ]
  },
  "day_trader": {
    "keyDeductions": [
      "software_subscriptions",
      "data_feeds",
      "computer",
      "home_office",
      "research_subscriptions",
      "professional_development",
      "internet_pct",
      "professional_fees"
    ],
    "note": "Trading is the rare business whose profits escape self-employment tax entirely, and the mark-to-market election has to be made a year in advance.",
    "sources": [
      {
        "claim": "Mark-to-market election: year-end positions treated as sold, gains and losses become ordinary",
        "authority": "IRC 475(f)(1)",
        "url": "https://www.law.cornell.edu/uscode/text/26/475",
        "confidence": "high"
      },
      {
        "claim": "Trading gains are excluded from net earnings from self-employment even with the election in force",
        "authority": "IRC 1402(a)(3)(A); IRC 475(f)(1)(D)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1402",
        "confidence": "high"
      }
    ]
  },
  "professional_gambler": {
    "keyDeductions": [
      "travel",
      "data_feeds",
      "research_subscriptions",
      "home_office",
      "professional_development",
      "software_subscriptions",
      "phone",
      "professional_fees"
    ],
    "note": "From 2026 only 90% of wagering losses are deductible, which can leave a break-even gambler owing tax on money they never made.",
    "sources": [
      {
        "claim": "Only 90% of wagering losses are deductible for tax years beginning after 2025, and losses still cannot exceed winnings",
        "authority": "IRC 165(d), as amended by P.L. 119-21 sec. 70114",
        "url": "https://www.law.cornell.edu/uscode/text/26/165",
        "confidence": "high"
      },
      {
        "claim": "Full-time gambling pursued for a livelihood is a trade or business",
        "authority": "Commissioner v. Groetzinger, 480 U.S. 23 (1987)",
        "url": "https://www.law.cornell.edu/supremecourt/text/480/23",
        "confidence": "high"
      }
    ]
  },
  "antiques_dealer": {
    "keyDeductions": [
      "inventory_cogs",
      "shop_rent",
      "liability_insurance",
      "marketing",
      "travel",
      "software_subscriptions",
      "staff_wages",
      "security_costs"
    ],
    "note": "Dealers pay ordinary rates plus self-employment tax; the 28% collectibles ceiling belongs to investors and never applies to stock.",
    "sources": [
      {
        "claim": "Property held primarily for sale to customers is not a capital asset, so no collectibles rate",
        "authority": "IRC 1221(a)(1)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1221",
        "confidence": "high"
      },
      {
        "claim": "The 28% maximum rate on collectibles applies to long-term capital gain, and is a ceiling rather than a flat rate",
        "authority": "IRC 1(h)(4)-(5)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1",
        "confidence": "high"
      }
    ]
  },
  "franchise_owner": {
    "keyDeductions": [
      "franchise_fee",
      "royalties",
      "rent",
      "staff_wages",
      "marketing",
      "equipment",
      "inventory_cogs",
      "liability_insurance"
    ],
    "note": "The initial franchise fee is amortised over fifteen years however long the agreement runs, while ongoing royalties are deducted as paid.",
    "sources": [
      {
        "claim": "A franchise is a section 197 intangible amortised ratably over 15 years from acquisition",
        "authority": "IRC 197(a), 197(d)(1)(F)",
        "url": "https://www.law.cornell.edu/uscode/text/26/197",
        "confidence": "high"
      },
      {
        "claim": "Contingent serial payments are deducted currently rather than amortised",
        "authority": "IRC 1253(d)(1)",
        "url": "https://www.law.cornell.edu/uscode/text/26/1253",
        "confidence": "high"
      }
    ]
  },
  "game_developer": {
    "keyDeductions": [
      "software_subscriptions",
      "computer",
      "equipment",
      "contractor_subcontractors",
      "home_office",
      "professional_development",
      "marketing",
      "platform_fees"
    ],
    "note": "Development costs are deductible again in the year you incur them, provided the work is done in the United States.",
    "sources": [
      {
        "claim": "Domestic research and experimental expenditures are deductible when paid or incurred, with an election to amortise over at least 60 months",
        "authority": "IRC 174A",
        "url": "https://www.law.cornell.edu/uscode/text/26/174A",
        "confidence": "high"
      },
      {
        "claim": "Foreign research and experimental expenditures remain capitalised over 15 years",
        "authority": "IRC 174, as amended by P.L. 119-21 sec. 70302",
        "url": "https://www.law.cornell.edu/uscode/text/26/174",
        "confidence": "high"
      }
    ]
  },
  "barber": {
    "keyDeductions": [
      "booth_rent",
      "tools",
      "supplies",
      "liability_insurance",
      "licensing_fees_state",
      "continuing_education",
      "marketing",
      "uniforms"
    ],
    "note": "Two 2026 changes land directly on this trade: tips became partly deductible, and the employer tip credit was extended to beauty services.",
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      },
      {
        "claim": "The employer credit for FICA on tips now covers beauty services, using the current $7.25 minimum rather than the frozen $5.15 used for food and drink",
        "authority": "IRC 45B(b)(1)(B), 45B(b)(2)(B)",
        "url": "https://www.law.cornell.edu/uscode/text/26/45B",
        "confidence": "high"
      }
    ]
  },
  "nail_technician": {
    "keyDeductions": [
      "booth_rent",
      "supplies",
      "tools",
      "liability_insurance",
      "licensing_fees_state",
      "continuing_education",
      "marketing",
      "equipment"
    ],
    "note": "Nail care is named in the 2026 extension of the employer tip credit and in Treasury's list of tipped occupations.",
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      },
      {
        "claim": "The employer credit for FICA on tips now covers beauty services, using the current $7.25 minimum rather than the frozen $5.15 used for food and drink",
        "authority": "IRC 45B(b)(1)(B), 45B(b)(2)(B)",
        "url": "https://www.law.cornell.edu/uscode/text/26/45B",
        "confidence": "high"
      }
    ]
  },
  "esthetician": {
    "keyDeductions": [
      "supplies",
      "equipment",
      "booth_rent",
      "liability_insurance",
      "licensing_fees_state",
      "continuing_education",
      "marketing",
      "inventory_cogs"
    ],
    "note": "Esthetics is inside the 2026 tip changes, and devices are Section 179 property with training attached that is deductible separately.",
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      },
      {
        "claim": "The employer credit for FICA on tips now covers beauty services, using the current $7.25 minimum rather than the frozen $5.15 used for food and drink",
        "authority": "IRC 45B(b)(1)(B), 45B(b)(2)(B)",
        "url": "https://www.law.cornell.edu/uscode/text/26/45B",
        "confidence": "high"
      }
    ]
  },
  "tattoo_artist": {
    "keyDeductions": [
      "booth_rent",
      "supplies",
      "equipment",
      "liability_insurance",
      "licensing_fees_state",
      "marketing",
      "training_costs",
      "waste_disposal"
    ],
    "note": "Tattooing is on Treasury's list of tipped occupations, and sharps and bloodborne-pathogen compliance are recurring deductible costs.",
    "sources": [
      {
        "claim": "Up to $25,000 of qualified tips is deductible for 2026, self-employed included, capped at the business's net income and barred for specified service trades",
        "authority": "IRC 224; 26 CFR 1.224-1",
        "url": "https://www.law.cornell.edu/uscode/text/26/224",
        "confidence": "high"
      },
      {
        "claim": "Treasury's list of tipped occupations is exhaustive; personal appearance and wellness roles are category 6",
        "authority": "26 CFR 1.224-1; IRS list of tipped occupations",
        "url": "https://www.irs.gov/forms-pubs/occupations-that-customarily-and-regularly-received-tips-on-or-before-dec-31-2024",
        "confidence": "high"
      }
    ]
  },
  "gym_owner": {
    "keyDeductions": [
      "equipment",
      "rent",
      "staff_wages",
      "utilities",
      "liability_insurance",
      "marketing",
      "software_subscriptions",
      "maintenance"
    ],
    "note": "A gym is not a specified service business, so it keeps the 20% deduction at incomes where a coaching practice loses it.",
    "sources": [
      {
        "claim": "Athletics as a specified service field covers competitors and coaches, not operating equipment or facilities",
        "authority": "Reg. 1.199A-5(b)(2)(viii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      },
      {
        "claim": "Health clubs and spas providing exercise or conditioning are not within the health field",
        "authority": "Reg. 1.199A-5(b)(2)(ii)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "streamer": {
    "keyDeductions": [
      "equipment",
      "software_subscriptions",
      "home_office",
      "internet_pct",
      "marketing",
      "computer",
      "professional_development",
      "platform_fees"
    ],
    "note": "Viewer donations are almost never gifts, and broadcasting is expressly outside the performing arts category for the 20% deduction.",
    "sources": [
      {
        "claim": "Viewer payments made in exchange for content are income, not gifts",
        "authority": "IRC 61(a); IRC 102(a); Commissioner v. Duberstein, 363 U.S. 278 (1960)",
        "url": "https://www.law.cornell.edu/supremecourt/text/363/278",
        "confidence": "high"
      },
      {
        "claim": "Performing arts expressly excludes persons who broadcast or disseminate video or audio to the public",
        "authority": "Reg. 1.199A-5(b)(2)(vi)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  },
  "commercial_fisherman": {
    "keyDeductions": [
      "vessel_costs",
      "fuel",
      "gear_and_equipment",
      "permits_and_licences",
      "insurance",
      "crew_shares",
      "maintenance",
      "moorage"
    ],
    "note": "A crew share on a small boat is self-employment income rather than wages, and fishing income can be averaged back three years.",
    "sources": [
      {
        "claim": "A crew share on a boat with a normal operating crew of fewer than 10 is not FICA employment and is self-employment income",
        "authority": "IRC 3121(b)(20); IRC 1402(c)(2)(F)",
        "url": "https://www.law.cornell.edu/uscode/text/26/3121",
        "confidence": "high"
      },
      {
        "claim": "Farm and fishing income may be averaged back over three base years on Schedule J",
        "authority": "IRC 1301",
        "url": "https://www.law.cornell.edu/uscode/text/26/1301",
        "confidence": "high"
      }
    ]
  },
  "logger_timber": {
    "keyDeductions": [
      "equipment",
      "fuel",
      "staff_wages",
      "liability_insurance",
      "permits_and_licences",
      "maintenance",
      "depletion",
      "site_travel"
    ],
    "note": "Standing timber can be taken at capital gain rates rather than as ordinary income, through one of two routes with different consequences.",
    "sources": [
      {
        "claim": "Two routes to capital treatment: electing to treat cutting as a sale, or disposal with a retained economic interest",
        "authority": "IRC 631(a), 631(b)",
        "url": "https://www.law.cornell.edu/uscode/text/26/631",
        "confidence": "high"
      },
      {
        "claim": "Timber uses cost depletion computed as a unit rate against volume cut",
        "authority": "IRC 611, 612; Reg. 1.611-3",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.611-3",
        "confidence": "high"
      }
    ]
  },
  "beekeeper": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "vehicle",
      "liability_insurance",
      "staff_wages",
      "permits_and_licences",
      "inventory_cogs",
      "training_costs"
    ],
    "note": "Beekeeping is farming, so it goes on Schedule F with the farm rules — including income averaging and the fuel credit.",
    "sources": [
      {
        "claim": "Care and management of bees is within the definition of farming purposes",
        "authority": "IRC 6420(c)(3)",
        "url": "https://www.law.cornell.edu/uscode/text/26/6420",
        "confidence": "medium"
      },
      {
        "claim": "Farm income may be averaged back over three base years on Schedule J",
        "authority": "IRC 1301",
        "url": "https://www.law.cornell.edu/uscode/text/26/1301",
        "confidence": "high"
      },
      {
        "claim": "The profit presumption is three profitable years in five",
        "authority": "IRC 183(d)",
        "url": "https://www.law.cornell.edu/uscode/text/26/183",
        "confidence": "high"
      }
    ]
  },
  "voice_actor": {
    "keyDeductions": [
      "recording_equipment",
      "studio_rent",
      "editing_software",
      "agent_commission",
      "professional_development",
      "home_office",
      "marketing",
      "equipment"
    ],
    "note": "Voice work generally sits inside performing arts for the 20% deduction, and licensing your voice is its own separate category.",
    "sources": [
      {
        "claim": "Performing arts covers actors, entertainers and similar professionals performing in that capacity",
        "authority": "Reg. 1.199A-5(b)(2)(vi)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "medium"
      },
      {
        "claim": "Licensing an individual's voice, image or likeness for a fee is a specified service in its own right",
        "authority": "Reg. 1.199A-5(b)(2)(xiv)",
        "url": "https://www.law.cornell.edu/cfr/text/26/1.199A-5",
        "confidence": "high"
      }
    ]
  }
};

export default professionals;
