/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * Legacy deduction slugs, notes and unique rules copied verbatim, MERGED with the authored trades in overrides/professions-trades.json. Labels are applied in lib/professions.ts.
 */
export const VERIFIED = "2026-v3.3" as const;

export const professionals = {
  "software_dev": {
    "keyDeductions": [
      "home_office",
      "computer_monitors",
      "cloud_services",
      "pro_development",
      "internet",
      "phone"
    ]
  },
  "ai_consultant": {
    "keyDeductions": [
      "compute_costs",
      "ai_software_subscriptions",
      "home_office",
      "conferences",
      "research"
    ]
  },
  "designer": {
    "keyDeductions": [
      "adobe_cc",
      "figma",
      "monitor_ipad_section179",
      "home_office",
      "stock_assets"
    ]
  },
  "copywriter": {
    "keyDeductions": [
      "grammarly",
      "research_subscriptions",
      "home_office",
      "internet",
      "pro_development"
    ]
  },
  "realtor": {
    "keyDeductions": [
      "mls_fees",
      "eo_insurance",
      "client_gifts_limit_25",
      "marketing",
      "vehicle",
      "staging_costs"
    ]
  },
  "travel_nurse": {
    "keyDeductions": [
      "licensing_fees",
      "per_diem",
      "travel",
      "scrubs",
      "ceus",
      "malpractice_insurance"
    ]
  },
  "truck_driver_otr": {
    "keyDeductions": [
      "per_diem_80_per_day",
      "truck_depreciation",
      "fuel",
      "dot_fees",
      "maintenance"
    ]
  },
  "photographer": {
    "keyDeductions": [
      "camera_lenses_section179",
      "lighting",
      "editing_software",
      "travel",
      "studio_rent"
    ]
  },
  "hair_stylist": {
    "keyDeductions": [
      "booth_rent",
      "tools",
      "supplies",
      "continuing_education",
      "liability_insurance"
    ]
  },
  "personal_trainer": {
    "keyDeductions": [
      "certification_fees",
      "equipment",
      "liability_insurance",
      "marketing",
      "gym_membership_business_pct"
    ]
  },
  "therapist": {
    "keyDeductions": [
      "malpractice_insurance",
      "ceus",
      "ehr_software",
      "office_rent_or_home_office",
      "supervision_costs"
    ]
  },
  "nurse_contractor": {
    "keyDeductions": [
      "malpractice_insurance",
      "licensing_fees",
      "scrubs",
      "ceus",
      "mileage_or_travel"
    ]
  },
  "massage_therapist": {
    "keyDeductions": [
      "massage_table_section179",
      "oils_supplies",
      "liability_insurance",
      "ce_credits",
      "booth_rent"
    ]
  },
  "bookkeeper_accountant": {
    "keyDeductions": [
      "quickbooks_xero_software",
      "continuing_education_cpe",
      "eo_insurance",
      "home_office",
      "professional_memberships_aicpa",
      "phone",
      "internet_pct"
    ],
    "note": "CPAs and EAs (Enrolled Agents) have additional licensing fees deductible as professional expenses.",
    "seoKeywords": [
      "bookkeeper 1099 tax calculator",
      "self employed accountant taxes",
      "CPA freelance taxes"
    ]
  },
  "virtual_assistant": {
    "keyDeductions": [
      "home_office",
      "computer",
      "internet_pct",
      "software_subscriptions",
      "phone",
      "professional_development",
      "contractor_subcontractors"
    ],
    "note": "VA services are highly deductible-friendly — almost all expenses are home-office and tech based. High S Corp potential at $80K+.",
    "seoKeywords": [
      "virtual assistant tax calculator",
      "VA 1099 taxes",
      "freelance VA taxes"
    ]
  },
  "coach": {
    "types": [
      "Business coach",
      "Life coach",
      "Health coach",
      "Executive coach",
      "Relationship coach"
    ],
    "keyDeductions": [
      "coaching_certification_fees",
      "zoom_video_platform",
      "home_office",
      "professional_development",
      "website",
      "crm_software",
      "marketing"
    ],
    "note": "Coaching certification costs are deductible as professional development (must be maintaining/improving current skills, not qualifying for new career).",
    "seoKeywords": [
      "life coach tax calculator",
      "business coach 1099 taxes",
      "executive coach self employed taxes"
    ]
  },
  "insurance_agent": {
    "types": [
      "Independent agent (1099)",
      "Captive agent (W-2 or 1099)"
    ],
    "keyDeductions": [
      "licensing_fees_state",
      "eo_insurance",
      "crm_software",
      "lead_generation_costs",
      "vehicle",
      "professional_development_ce_credits",
      "office_rent_or_home_office"
    ],
    "note": "Captive agents may be W-2. Independent agents are typically 1099. Commissions are SE income.",
    "seoKeywords": [
      "insurance agent tax calculator",
      "independent insurance agent 1099 taxes",
      "insurance broker self employed taxes"
    ]
  },
  "notary_signing_agent": {
    "keyDeductions": [
      "notary_bond",
      "notary_commission_fees",
      "supplies_stamps_seals",
      "mileage_to_signings",
      "errors_omissions_insurance",
      "background_check_fees",
      "notary_software"
    ],
    "note": "Mobile notary and loan signing agents: mileage between appointments is the largest deduction. Track every signing trip.",
    "seoKeywords": [
      "notary signing agent tax calculator",
      "mobile notary 1099 taxes",
      "loan signing agent taxes"
    ]
  },
  "tutor": {
    "keyDeductions": [
      "home_office_or_tutoring_space",
      "educational_materials_books",
      "laptop",
      "zoom_subscription",
      "marketing",
      "mileage_if_in_person"
    ],
    "note": "Online tutors: home office is key deduction. In-person tutors: mileage between student locations is #1 deduction.",
    "seoKeywords": [
      "tutor tax calculator",
      "online tutor 1099 taxes",
      "self employed tutor taxes"
    ]
  },
  "wedding_event_planner": {
    "keyDeductions": [
      "vendor_deposits_if_direct_billed",
      "event_software_honeybook_aisle",
      "vehicle_mileage",
      "marketing_photography",
      "professional_attire_if_required",
      "liability_insurance",
      "phone",
      "home_office"
    ],
    "note": "Deposits collected on behalf of clients are not income until earned. Vendor payments passed through to client are not deductible if reimbursed.",
    "seoKeywords": [
      "wedding planner tax calculator",
      "event planner 1099 taxes",
      "wedding coordinator self employed taxes"
    ]
  },
  "qa_tester_contractor": {
    "keyDeductions": [
      "device_testing_setup_section179",
      "home_office",
      "software_tools",
      "vpn_subscriptions",
      "professional_development",
      "internet_pct"
    ],
    "note": "Common in tech as contract workers. Devices used for testing (phones, tablets) qualify for Section 179 deduction at business-use percentage.",
    "seoKeywords": [
      "QA tester contractor taxes",
      "software tester 1099 tax calculator",
      "QA engineer freelance taxes"
    ]
  },
  "clergy_minister": {
    "uniqueRules": {
      "housingAllowance": {
        "taxTreatment": "Excludable from federal income tax if designated in advance by church. Amount limited to: lesser of (a) designated amount, (b) actual housing expenses, (c) fair rental value of home furnished + utilities.",
        "seTaxNote": "Housing allowance IS included in SE tax base even though excluded from income tax. This surprises many ministers.",
        "form": "No separate form — designated in church board minutes before year begins"
      },
      "seOptOut": {
        "form": "Form 4361",
        "note": "Irrevocable election to opt out of SE tax on ministerial earnings if conscientiously opposed on religious grounds. Cannot opt back in.",
        "deadline": "Due date of return for second year with net ministerial earnings of $400+"
      },
      "dualStatus": "Ministers are employees for income tax purposes but self-employed for SE tax on ministerial income. Unique in US tax code."
    },
    "keyDeductions": [
      "ministry_expenses",
      "vehicle_for_ministry",
      "books_religious_materials",
      "continuing_education_seminary",
      "home_office_for_study"
    ],
    "seoKeywords": [
      "clergy tax calculator",
      "minister self employment tax",
      "pastor housing allowance calculator",
      "Form 4361 clergy"
    ]
  },
  "farm_schedule_f": {
    "taxForm": "Schedule F (Form 1040)",
    "seTaxApplies": true,
    "uniqueDeductions": [
      {
        "name": "Feed",
        "deductible": 1,
        "note": "Livestock feed purchased and consumed in tax year. Cannot deduct feed purchased but not yet used (inventory rules apply for some farms)."
      },
      {
        "name": "Seeds and plants",
        "deductible": 1,
        "note": "Purchased for planting, not for consumption. Ornamental seeds for personal use are not deductible."
      },
      {
        "name": "Fertilizers and lime",
        "deductible": 1,
        "note": "Soil conditioners and crop nutrients applied in the tax year. Purchased but unused inventory may need to be deducted in future year."
      },
      {
        "name": "Livestock purchased for resale",
        "deductible": 1,
        "note": "Cost of animals purchased during the year and sold in the same year. Treated as COGS on Schedule F. Livestock raised on farm has $0 basis."
      },
      {
        "name": "Breeding livestock depreciation",
        "deductible": 1,
        "note": "Breeding animals are depreciable assets (not expensed as feed). Cattle and horses: 5–7 years MACRS. Section 179 or bonus depreciation may apply."
      },
      {
        "name": "Farm equipment",
        "deductible": 1,
        "note": "Tractors, combines, irrigation systems, planting/harvesting equipment. Section 179 up to $2,560,000 (2026). 100% bonus depreciation available under OBBBA."
      },
      {
        "name": "Crop insurance proceeds deferral",
        "deductible": 0,
        "note": "Crop insurance is income, not a deduction. However, farmers can elect to defer crop insurance proceeds to the following tax year if the crop would normally be sold in a different year. Elective deferral, not automatic."
      },
      {
        "name": "Fuel for farm equipment",
        "deductible": 1,
        "note": "100% deductible for off-highway business use. Also qualifies for federal fuel tax credit (Form 4136) — separate from the deduction."
      },
      {
        "name": "Repairs and maintenance of farm buildings",
        "deductible": 1,
        "note": "Routine repairs are an operating expense. Improvements that add value or extend useful life must be capitalized and depreciated. Tangible property regulations (Repair Regs) govern the distinction."
      }
    ],
    "specialProvisions": {
      "farmingLossCarryback": "Net farming losses can be carried back 2 years (vs 0 years for most businesses).",
      "incomeAveraging": "Schedule J — farmers can average income over 3 years to reduce tax on boom years.",
      "soilConservation": "Deductible up to 25% of gross farming income",
      "fuelTaxCredit": "Form 4136 — credit for non-highway fuel used in farming operations"
    },
    "seoKeywords": [
      "farm income tax calculator",
      "Schedule F tax calculator",
      "farmer self employment tax",
      "agricultural income taxes"
    ],
    "_deductionSchema": "name:string, deductible:number (0–1 or dollar cap), note:string — matches selfEmploymentDeductions.otherCommonDeductions schema"
  },
  "general_contractor": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "subcontractors_1099",
      "liability_insurance",
      "permits_and_licences",
      "materials_and_supplies",
      "equipment_rental",
      "workers_comp",
      "jobsite_travel",
      "safety_gear"
    ],
    "note": "The line that decides a contractor's return is subcontractors. Pay anyone $600 or more in a year and you must issue a 1099-NEC, and misclassifying a worker who should have been an employee is the most expensive mistake in the trade. Materials you buy and bill on are both income and a deduction — never one without the other."
  },
  "electrician": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "continuing_education",
      "liability_insurance",
      "materials_and_supplies",
      "safety_gear",
      "equipment",
      "phone"
    ],
    "note": "Hand tools and testers are deductible in the year you buy them; a van fit-out is a vehicle improvement and is depreciated. State licensing and the continuing education hours that renew it are both deductible, because they maintain a licence you already hold."
  },
  "plumber": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "continuing_education",
      "liability_insurance",
      "materials_and_supplies",
      "equipment",
      "safety_gear",
      "phone"
    ],
    "note": "Emergency call-outs make mileage the largest single deduction for most plumbers, and it is the one least often logged properly. Specialist equipment — drain cameras, jetters, press tools — is Section 179 property and can be written off in full the year it goes into service."
  },
  "hvac_technician": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "licensing_fees_state",
      "epa_certification",
      "continuing_education",
      "liability_insurance",
      "equipment",
      "materials_and_supplies",
      "safety_gear"
    ],
    "note": "EPA Section 608 certification and the state licence behind it are deductible professional costs. Refrigerant and parts inventory bought for a job are deductible when used; stock held at year end is inventory rather than an expense."
  },
  "landscaper": {
    "keyDeductions": [
      "equipment",
      "vehicle",
      "trailer",
      "fuel",
      "materials_and_supplies",
      "liability_insurance",
      "seasonal_labour",
      "storage_yard_rent"
    ],
    "note": "Mowers, trimmers and trailers are Section 179 property. Seasonal crews are usually employees rather than contractors — being paid weekly, using your equipment and working your schedule are all signs of employment, and the penalty for getting it wrong is back payroll tax."
  },
  "cleaner": {
    "keyDeductions": [
      "supplies",
      "equipment",
      "vehicle",
      "liability_insurance",
      "bonding",
      "uniforms",
      "marketing",
      "subcontractors_1099"
    ],
    "note": "Cleaning supplies and equipment are straightforward; bonding and liability cover are what clients ask for and both are deductible. Mileage between client properties counts, but the first trip from home to your first job of the day is commuting and does not."
  },
  "handyman": {
    "keyDeductions": [
      "tools",
      "vehicle",
      "materials_and_supplies",
      "liability_insurance",
      "permits_and_licences",
      "equipment",
      "marketing",
      "phone"
    ],
    "note": "Most handyman work sits below the licensing threshold, but the threshold is set by each state and by the value of the job — exceed it without a licence and the work may be unenforceable as well as uninsured. Materials billed to the customer are income and a deduction both."
  },
  "painter": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment",
      "vehicle",
      "liability_insurance",
      "safety_gear",
      "subcontractors_1099",
      "equipment_rental",
      "certification_fees"
    ],
    "note": "Sprayers, scaffolding and lifts are usually cheaper to hire than to own, and hire costs are deductible in full in the year you pay them with no depreciation to track."
  },
  "roofer": {
    "keyDeductions": [
      "materials_and_supplies",
      "equipment_rental",
      "vehicle",
      "liability_insurance",
      "workers_comp",
      "safety_gear",
      "subcontractors_1099",
      "waste_disposal"
    ],
    "note": "Workers' compensation is the dominant insurance cost in roofing and is fully deductible. Fall-protection equipment is both a legal requirement and an ordinary business expense."
  },
  "welder": {
    "keyDeductions": [
      "equipment",
      "materials_and_supplies",
      "vehicle",
      "safety_gear",
      "certification_fees",
      "liability_insurance",
      "equipment_rental"
    ],
    "note": "Welding certifications have to be renewed and the renewal is deductible. Gas, rod and consumables are ordinary supplies; the machine itself is Section 179 property."
  },
  "auto_mechanic": {
    "keyDeductions": [
      "tools",
      "equipment",
      "shop_rent",
      "materials_and_supplies",
      "liability_insurance",
      "certification_fees",
      "uniforms",
      "waste_disposal"
    ],
    "note": "Tool debt is the defining feature of this trade. Tools bought on a truck account are deductible when you buy them, not when you finish paying for them, and the interest on the account is deductible separately."
  },
  "teacher_tutor": {
    "keyDeductions": [
      "educational_materials_books",
      "home_office_or_tutoring_space",
      "laptop",
      "software_subscriptions",
      "professional_development",
      "marketing",
      "mileage_if_in_person",
      "professional_memberships"
    ],
    "note": "The $300 educator expense deduction is for employed teachers in a school. If you teach for yourself — private tuition, online courses, music lessons — you are not limited to $300; you deduct the actual cost as a business expense, which is almost always more."
  },
  "musician": {
    "keyDeductions": [
      "instruments_section179",
      "equipment",
      "vehicle",
      "studio_rent",
      "marketing",
      "professional_development",
      "union_dues",
      "travel"
    ],
    "note": "Instruments are Section 179 property, and a professional instrument that also gets played at home is deductible at the business-use percentage. Touring costs are business travel; the meals within them are only half deductible."
  },
  "translator": {
    "keyDeductions": [
      "software_subscriptions",
      "computer",
      "home_office",
      "professional_development",
      "professional_memberships",
      "internet_pct",
      "reference_materials"
    ],
    "note": "Translation memory and terminology software are ordinary subscriptions. Certification through a professional body is deductible as maintaining an existing skill, provided you are already working in the field."
  },
  "videographer": {
    "keyDeductions": [
      "camera_lenses_section179",
      "lighting",
      "editing_software",
      "equipment",
      "vehicle",
      "studio_rent",
      "travel",
      "equipment_rental"
    ],
    "note": "Cameras, lenses, drones and lighting are Section 179 property at the business-use percentage. Hiring gear for a single shoot is deductible in full and avoids the business-use argument entirely."
  },
  "dog_groomer": {
    "keyDeductions": [
      "equipment",
      "supplies",
      "vehicle",
      "liability_insurance",
      "shop_rent",
      "certification_fees",
      "uniforms",
      "marketing"
    ],
    "note": "Mobile groomers deduct the van conversion as a vehicle improvement and depreciate it, while the grooming equipment inside is Section 179 property in its own right — two different treatments in the same vehicle."
  },
  "caterer": {
    "keyDeductions": [
      "food_and_ingredients",
      "equipment",
      "vehicle",
      "liability_insurance",
      "permits_and_licences",
      "staff_wages",
      "equipment_rental",
      "uniforms"
    ],
    "note": "Food bought for a job is cost of goods sold rather than a general expense, which matters for how it appears on your return. The 50% limit on business meals does not apply to it — that limit is about meals you eat, not food you sell."
  }
};

export default professionals;
