/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * Bracket overrides from src/data/overrides/state-brackets-2026.json applied to: MD, NE, SC, WV, IN.
 */
import type { StateData } from './types';

export const VERIFIED = "2026-v3.3" as const;

export const states: Record<string, StateData> = {
  "AL": {
    "name": "Alabama",
    "type": "graduated",
    "topRate": 0.05,
    "brackets_single": [
      [
        0,
        500,
        0.02
      ],
      [
        500,
        3000,
        0.04
      ],
      [
        3000,
        null,
        0.05
      ]
    ],
    "localTaxNote": "Some cities have local taxes (Birmingham 1%)"
  },
  "AK": {
    "name": "Alaska",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "AZ": {
    "name": "Arizona",
    "type": "flat",
    "topRate": 0.025,
    "rate": 0.025
  },
  "AR": {
    "name": "Arkansas",
    "type": "graduated",
    "topRate": 0.039,
    "brackets_single": [
      [
        0,
        4300,
        0.02
      ],
      [
        4300,
        8500,
        0.04
      ],
      [
        8500,
        null,
        0.039
      ]
    ]
  },
  "CA": {
    "name": "California",
    "type": "graduated",
    "topRate": 0.133,
    "mentalHealthSurcharge": 0.01,
    "mentalHealthThreshold": 1000000,
    "brackets_single": [
      [
        0,
        10099,
        0.01
      ],
      [
        10099,
        23942,
        0.02
      ],
      [
        23942,
        37788,
        0.04
      ],
      [
        37788,
        52455,
        0.06
      ],
      [
        52455,
        66295,
        0.08
      ],
      [
        66295,
        338639,
        0.093
      ],
      [
        338639,
        406364,
        0.103
      ],
      [
        406364,
        677275,
        0.113
      ],
      [
        677275,
        1000000,
        0.123
      ],
      [
        1000000,
        null,
        0.133
      ]
    ],
    "standardDeduction": {
      "single": 5363,
      "mfj": 10726,
      "mfs": 5363,
      "hoh": 10726
    },
    "sdiRate": 0.009,
    "note": "CA SDI applies to SE income. 9 income tax brackets. Highest top rate in US."
  },
  "CO": {
    "name": "Colorado",
    "type": "flat",
    "topRate": 0.04,
    "rate": 0.04
  },
  "CT": {
    "name": "Connecticut",
    "type": "graduated",
    "topRate": 0.069,
    "brackets_single": [
      [
        0,
        10000,
        0.02
      ],
      [
        10000,
        50000,
        0.045
      ],
      [
        50000,
        100000,
        0.055
      ],
      [
        100000,
        200000,
        0.06
      ],
      [
        200000,
        250000,
        0.065
      ],
      [
        250000,
        500000,
        0.069
      ],
      [
        500000,
        null,
        0.069
      ]
    ]
  },
  "DE": {
    "name": "Delaware",
    "type": "graduated",
    "topRate": 0.066,
    "brackets_single": [
      [
        0,
        2000,
        0
      ],
      [
        2000,
        5000,
        0.022
      ],
      [
        5000,
        10000,
        0.039
      ],
      [
        10000,
        20000,
        0.048
      ],
      [
        20000,
        25000,
        0.052
      ],
      [
        25000,
        60000,
        0.055
      ],
      [
        60000,
        null,
        0.066
      ]
    ]
  },
  "FL": {
    "name": "Florida",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "GA": {
    "name": "Georgia",
    "type": "flat",
    "topRate": 0.0519,
    "rate": 0.0519,
    "note": "Rate was 5.39%, reduced to 5.19% mid-2025. Further phasedowns planned."
  },
  "HI": {
    "name": "Hawaii",
    "type": "graduated",
    "topRate": 0.11,
    "brackets_single": [
      [
        0,
        2400,
        0.014
      ],
      [
        2400,
        4800,
        0.032
      ],
      [
        4800,
        9600,
        0.055
      ],
      [
        9600,
        14400,
        0.064
      ],
      [
        14400,
        19200,
        0.068
      ],
      [
        19200,
        24000,
        0.072
      ],
      [
        24000,
        36000,
        0.076
      ],
      [
        36000,
        48000,
        0.079
      ],
      [
        48000,
        150000,
        0.0825
      ],
      [
        150000,
        175000,
        0.09
      ],
      [
        175000,
        200000,
        0.1
      ],
      [
        200000,
        null,
        0.11
      ]
    ]
  },
  "ID": {
    "name": "Idaho",
    "type": "flat",
    "topRate": 0.053,
    "rate": 0.053
  },
  "IL": {
    "name": "Illinois",
    "type": "flat",
    "topRate": 0.0495,
    "rate": 0.0495
  },
  "IN": {
    "name": "Indiana",
    "type": "flat",
    "topRate": 0.0295,
    "rate": 0.0295,
    "note": "Rate has been decreasing. Some counties add local income tax.",
    "sources": [
      "in.gov/dor Departmental Notice #1 (R46/01-26), effective January 1, 2026",
      "in.gov/dor Rates, Fees and Penalties — 2026 individual AGI rate 2.95%, 2027 2.90%"
    ],
    "bracketSource": "overrides/state-brackets-2026.json (2026-07)"
  },
  "IA": {
    "name": "Iowa",
    "type": "flat",
    "topRate": 0.038,
    "rate": 0.038
  },
  "KS": {
    "name": "Kansas",
    "type": "graduated",
    "topRate": 0.057,
    "brackets_single": [
      [
        0,
        15000,
        0.031
      ],
      [
        15000,
        null,
        0.057
      ]
    ]
  },
  "KY": {
    "name": "Kentucky",
    "type": "flat",
    "topRate": 0.035,
    "rate": 0.035,
    "note": "Reduced from 4% to 3.5% on Jan 1, 2026."
  },
  "LA": {
    "name": "Louisiana",
    "type": "graduated",
    "topRate": 0.03,
    "brackets_single": [
      [
        0,
        12500,
        0.01
      ],
      [
        12500,
        50000,
        0.02
      ],
      [
        50000,
        null,
        0.03
      ]
    ]
  },
  "ME": {
    "name": "Maine",
    "type": "graduated",
    "topRate": 0.075,
    "brackets_single": [
      [
        0,
        24500,
        0.058
      ],
      [
        24500,
        58050,
        0.0675
      ],
      [
        58050,
        null,
        0.075
      ]
    ]
  },
  "MD": {
    "name": "Maryland",
    "type": "graduated",
    "topRate": 0.065,
    "localTaxRequired": true,
    "localTaxRange": "0.0250–0.0320",
    "note": "New 6.25% and 6.5% high-income brackets added in 2025 BRF Act, effective retroactively.",
    "brackets_single": [
      [
        0,
        1000,
        0.02
      ],
      [
        1000,
        2000,
        0.03
      ],
      [
        2000,
        3000,
        0.04
      ],
      [
        3000,
        100000,
        0.0475
      ],
      [
        100000,
        125000,
        0.05
      ],
      [
        125000,
        150000,
        0.0525
      ],
      [
        150000,
        250000,
        0.055
      ],
      [
        250000,
        500000,
        0.0575
      ],
      [
        500000,
        1000000,
        0.0625
      ],
      [
        1000000,
        null,
        0.065
      ]
    ],
    "brackets_mfj": [
      [
        0,
        1000,
        0.02
      ],
      [
        1000,
        2000,
        0.03
      ],
      [
        2000,
        3000,
        0.04
      ],
      [
        3000,
        150000,
        0.0475
      ],
      [
        150000,
        175000,
        0.05
      ],
      [
        175000,
        225000,
        0.0525
      ],
      [
        225000,
        300000,
        0.055
      ],
      [
        300000,
        600000,
        0.0575
      ],
      [
        600000,
        1200000,
        0.0625
      ],
      [
        1200000,
        null,
        0.065
      ]
    ],
    "dataCaveat": "Maryland's standard deduction is a percentage of adjusted gross income with a floor and a cap, which this calculator cannot express, so it is not applied. Maryland tax shown here is computed on full income and is therefore slightly overstated.",
    "bracketSource": "overrides/state-brackets-2026.json (2026-07)"
  },
  "MA": {
    "name": "Massachusetts",
    "type": "flat",
    "topRate": 0.05,
    "rate": 0.05,
    "millionairesSurtax": 0.04,
    "millionairesThreshold": 1000000
  },
  "MI": {
    "name": "Michigan",
    "type": "flat",
    "topRate": 0.0425,
    "rate": 0.0425
  },
  "MN": {
    "name": "Minnesota",
    "type": "graduated",
    "topRate": 0.0985,
    "brackets_single": [
      [
        0,
        32260,
        0.0535
      ],
      [
        32260,
        106070,
        0.068
      ],
      [
        106070,
        196880,
        0.0785
      ],
      [
        196880,
        null,
        0.0985
      ]
    ]
  },
  "MS": {
    "name": "Mississippi",
    "type": "flat",
    "topRate": 0.04,
    "rate": 0.04,
    "note": "Phasing down toward 0% if revenue triggers met."
  },
  "MO": {
    "name": "Missouri",
    "type": "graduated",
    "topRate": 0.048,
    "brackets_single": [
      [
        0,
        1207,
        0
      ],
      [
        1207,
        2414,
        0.02
      ],
      [
        2414,
        3621,
        0.025
      ],
      [
        3621,
        4828,
        0.03
      ],
      [
        4828,
        6035,
        0.035
      ],
      [
        6035,
        7242,
        0.04
      ],
      [
        7242,
        8432,
        0.045
      ],
      [
        8432,
        null,
        0.048
      ]
    ]
  },
  "MT": {
    "name": "Montana",
    "type": "graduated",
    "topRate": 0.0565,
    "note": "Top rate reduced from 5.9% in 2025. Essentially a flat tax with small lower bracket.",
    "brackets_single": [
      [
        0,
        25000,
        0.047
      ],
      [
        25000,
        null,
        0.0565
      ]
    ],
    "brackets_mfj": [
      [
        0,
        50000,
        0.047
      ],
      [
        50000,
        null,
        0.0565
      ]
    ],
    "standardDeduction": {
      "single": 14000,
      "mfj": 28000,
      "mfs": 14000,
      "hoh": 21000
    }
  },
  "NE": {
    "name": "Nebraska",
    "type": "graduated",
    "topRate": 0.0455,
    "note": "Top rate reduced from 5.2% to 4.55% in 2026. Further reductions to 3.99% by 2027.",
    "brackets_single": [
      [
        0,
        4130,
        0.0246
      ],
      [
        4130,
        24760,
        0.0351
      ],
      [
        24760,
        null,
        0.0455
      ]
    ],
    "brackets_mfj": [
      [
        0,
        8250,
        0.0246
      ],
      [
        8250,
        49530,
        0.0351
      ],
      [
        49530,
        null,
        0.0455
      ]
    ],
    "bracketSource": "overrides/state-brackets-2026.json (2026-07)"
  },
  "NV": {
    "name": "Nevada",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "NH": {
    "name": "New Hampshire",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true,
    "note": "Dividend/interest tax fully eliminated effective Jan 1, 2025."
  },
  "NJ": {
    "name": "New Jersey",
    "type": "graduated",
    "topRate": 0.1075,
    "brackets_single": [
      [
        0,
        20000,
        0.014
      ],
      [
        20000,
        35000,
        0.0175
      ],
      [
        35000,
        40000,
        0.035
      ],
      [
        40000,
        75000,
        0.0553
      ],
      [
        75000,
        500000,
        0.0637
      ],
      [
        500000,
        1000000,
        0.0897
      ],
      [
        1000000,
        null,
        0.1075
      ]
    ]
  },
  "NM": {
    "name": "New Mexico",
    "type": "graduated",
    "topRate": 0.059,
    "brackets_single": [
      [
        0,
        5500,
        0.015
      ],
      [
        5500,
        11000,
        0.032
      ],
      [
        11000,
        16000,
        0.047
      ],
      [
        16000,
        210000,
        0.049
      ],
      [
        210000,
        null,
        0.059
      ]
    ]
  },
  "NY": {
    "name": "New York",
    "type": "graduated",
    "topRate": 0.109,
    "nycLocalTax": 0.03876,
    "yonkersLocalTax": 0.01477,
    "brackets_single": [
      [
        0,
        17150,
        0.04
      ],
      [
        17150,
        23600,
        0.045
      ],
      [
        23600,
        27900,
        0.0525
      ],
      [
        27900,
        161550,
        0.0585
      ],
      [
        161550,
        323200,
        0.0625
      ],
      [
        323200,
        2155350,
        0.0685
      ],
      [
        2155350,
        5000000,
        0.0965
      ],
      [
        5000000,
        25000000,
        0.103
      ],
      [
        25000000,
        null,
        0.109
      ]
    ]
  },
  "NC": {
    "name": "North Carolina",
    "type": "flat",
    "topRate": 0.0399,
    "rate": 0.0399,
    "note": "Final reduction in phased plan. Rate was 4.25% in 2025."
  },
  "ND": {
    "name": "North Dakota",
    "type": "graduated",
    "topRate": 0.02,
    "brackets_single": [
      [
        0,
        44725,
        0
      ],
      [
        44725,
        225975,
        0.0185
      ],
      [
        225975,
        null,
        0.02
      ]
    ]
  },
  "OH": {
    "name": "Ohio",
    "type": "flat",
    "topRate": 0.0275,
    "rate": 0.0275,
    "exemptBelow": 26050,
    "note": "Converted to flat tax in 2026. Income at or below $26,050 is exempt."
  },
  "OK": {
    "name": "Oklahoma",
    "type": "graduated",
    "topRate": 0.045,
    "brackets_single": [
      [
        0,
        1000,
        0.025
      ],
      [
        1000,
        2500,
        0.035
      ],
      [
        2500,
        null,
        0.045
      ]
    ],
    "note": "Simplified to 3 brackets in 2026, top rate reduced from 4.75% to 4.5%."
  },
  "OR": {
    "name": "Oregon",
    "type": "graduated",
    "topRate": 0.099,
    "brackets_single": [
      [
        0,
        18400,
        0.0475
      ],
      [
        18400,
        46200,
        0.0675
      ],
      [
        46200,
        250000,
        0.0875
      ],
      [
        250000,
        null,
        0.099
      ]
    ]
  },
  "PA": {
    "name": "Pennsylvania",
    "type": "flat",
    "topRate": 0.0307,
    "rate": 0.0307
  },
  "RI": {
    "name": "Rhode Island",
    "type": "graduated",
    "topRate": 0.0599,
    "brackets_single": [
      [
        0,
        73450,
        0.0375
      ],
      [
        73450,
        166950,
        0.0475
      ],
      [
        166950,
        null,
        0.0599
      ]
    ]
  },
  "SC": {
    "name": "South Carolina",
    "type": "graduated",
    "topRate": 0.0521,
    "note": "Two-bracket system starting 2026: 1.99% and 5.21%.",
    "brackets_single": [
      [
        0,
        30000,
        0.0199
      ],
      [
        30000,
        null,
        0.0521
      ]
    ],
    "brackets_mfj": [
      [
        0,
        30000,
        0.0199
      ],
      [
        30000,
        null,
        0.0521
      ]
    ],
    "bracketSource": "overrides/state-brackets-2026.json (2026-07)"
  },
  "SD": {
    "name": "South Dakota",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "TN": {
    "name": "Tennessee",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "TX": {
    "name": "Texas",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "UT": {
    "name": "Utah",
    "type": "flat",
    "topRate": 0.045,
    "rate": 0.045
  },
  "VT": {
    "name": "Vermont",
    "type": "graduated",
    "topRate": 0.0875,
    "brackets_single": [
      [
        0,
        45400,
        0.0335
      ],
      [
        45400,
        110050,
        0.066
      ],
      [
        110050,
        229550,
        0.076
      ],
      [
        229550,
        null,
        0.0875
      ]
    ]
  },
  "VA": {
    "name": "Virginia",
    "type": "graduated",
    "topRate": 0.0575,
    "brackets_single": [
      [
        0,
        3000,
        0.02
      ],
      [
        3000,
        5000,
        0.03
      ],
      [
        5000,
        17000,
        0.05
      ],
      [
        17000,
        null,
        0.0575
      ]
    ]
  },
  "WA": {
    "name": "Washington",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true,
    "note": "No general income tax. Capital gains tax 7% on gains >$262,000 (2026), 9.9% on gains >$1M."
  },
  "WV": {
    "name": "West Virginia",
    "type": "graduated",
    "topRate": 0.0458,
    "note": "Phased rate reductions in progress.",
    "brackets_single": [
      [
        0,
        10000,
        0.0211
      ],
      [
        10000,
        25000,
        0.0281
      ],
      [
        25000,
        40000,
        0.0316
      ],
      [
        40000,
        60000,
        0.0422
      ],
      [
        60000,
        null,
        0.0458
      ]
    ],
    "brackets_mfj": [
      [
        0,
        10000,
        0.0211
      ],
      [
        10000,
        25000,
        0.0281
      ],
      [
        25000,
        40000,
        0.0316
      ],
      [
        40000,
        60000,
        0.0422
      ],
      [
        60000,
        null,
        0.0458
      ]
    ],
    "bracketSource": "overrides/state-brackets-2026.json (2026-07)"
  },
  "WI": {
    "name": "Wisconsin",
    "type": "graduated",
    "topRate": 0.0765,
    "brackets_single": [
      [
        0,
        14320,
        0.035
      ],
      [
        14320,
        28640,
        0.044
      ],
      [
        28640,
        315310,
        0.053
      ],
      [
        315310,
        null,
        0.0765
      ]
    ]
  },
  "WY": {
    "name": "Wyoming",
    "type": "none",
    "topRate": 0,
    "noIncomeTax": true
  },
  "DC": {
    "name": "Washington DC",
    "type": "graduated",
    "topRate": 0.1075,
    "brackets_single": [
      [
        0,
        10000,
        0.04
      ],
      [
        10000,
        40000,
        0.06
      ],
      [
        40000,
        60000,
        0.065
      ],
      [
        60000,
        350000,
        0.085
      ],
      [
        350000,
        1000000,
        0.0925
      ],
      [
        1000000,
        null,
        0.1075
      ]
    ]
  }
};

export const stateMetadata = {
  "communityPropertyStates": [
    "AZ",
    "CA",
    "ID",
    "LA",
    "NM",
    "NV",
    "TX",
    "WA",
    "WI"
  ],
  "communityPropertyNote": "In community property states, income earned during marriage is generally owned equally by both spouses. This affects QJV eligibility, MFS filing strategies, and retirement account contribution rules.",
  "noIncomeTaxStates": [
    "AK",
    "FL",
    "NV",
    "NH",
    "SD",
    "TN",
    "TX",
    "WA",
    "WY"
  ],
  "statesThatTaxSocialSecurity": [
    "CO",
    "CT",
    "KS",
    "MN",
    "MO",
    "MT",
    "NE",
    "NM",
    "RI",
    "UT",
    "VT",
    "WV"
  ],
  "statesWithLocalIncomeTax": {
    "NY": [
      "New York City (3.876%)",
      "Yonkers (1.477% resident, 0.50% non-resident)"
    ],
    "MD": [
      "All counties require local tax filing (2.25%–3.20% depending on county)"
    ],
    "OH": [
      "Many municipalities levy local income tax (0%–3%). RITA and CCA administer most."
    ],
    "PA": [
      "Many municipalities levy earned income tax. Philadelphia: 3.75% resident."
    ],
    "IN": [
      "All 92 counties levy local income tax (0.50%–2.90%)."
    ],
    "KY": [
      "Many cities/counties levy occupational tax."
    ],
    "AL": [
      "Some cities: Birmingham 1%, etc."
    ]
  },
  "statesWithNoSalesTax": [
    "AK",
    "DE",
    "MT",
    "NH",
    "OR"
  ],
  "statesWithSDI": {
    "CA": {
      "rate": 0.009,
      "wageBase": "unlimited",
      "note": "CA SDI applies to self-employed who voluntarily elect coverage. Mandatory for W-2 employees."
    },
    "NJ": {
      "rate": 0.006,
      "wageBase": 161400,
      "note": "NJ SDI mandatory for employees. SE may not be subject."
    },
    "NY": {
      "rate": "varies",
      "note": "NY DBL (statutory disability) mandatory for employees. SE not required."
    },
    "HI": {
      "rate": "varies",
      "note": "Hawaii TDI mandatory for employees."
    },
    "RI": {
      "rate": 0.013,
      "wageBase": 84000,
      "note": "RI TDI mandatory for employees."
    }
  },
  "passthroughEntityTaxStates": {
    "note": "Many states now allow pass-through entities (partnerships, S corps) to pay state income tax at the entity level, providing a workaround to the federal SALT cap. Known as PTET or SALT workaround.",
    "statesWithPTET": [
      "AL",
      "AZ",
      "AR",
      "CA",
      "CO",
      "CT",
      "GA",
      "ID",
      "IL",
      "IN",
      "KS",
      "LA",
      "MD",
      "MA",
      "MI",
      "MN",
      "MO",
      "MT",
      "NJ",
      "NM",
      "NY",
      "NC",
      "OH",
      "OK",
      "OR",
      "PA",
      "RI",
      "SC",
      "UT",
      "VA",
      "WI"
    ],
    "howItWorks": "Entity pays state tax on behalf of owners. Owners get state tax credit on their personal return. The entity-level payment is deductible as a business expense, bypassing the $40,400 SALT cap."
  }
};

/** Alphabetical [code, StateData] pairs — convenient for getStaticPaths. */
export const stateList = Object.entries(states).sort((a, b) => a[1].name.localeCompare(b[1].name));
