/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * UI-facing projection of overrides/state-capital-gains-2026.json (owner-signed-off). Sources, confidence and notes are stripped; only the compute fields ship.
 */
export interface StateCapGains {
  treatment: 'ordinary' | 'excluded' | 'special' | 'reduced_rate' | 'none';
  ordinaryRateApplies: boolean;
  ltcgExclusionPct: number | null;
  specialRate: number | null;
  specialRateThreshold: number | null;
  shortTermTreatment: 'ordinary' | 'same_as_long' | null;
}

export const stateCapGains: Record<string, StateCapGains> = {
  "AL": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "AK": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "AZ": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "AR": {
    "treatment": "excluded",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": 0.5,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "CA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "CO": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "CT": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "DE": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "FL": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "GA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "HI": {
    "treatment": "reduced_rate",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": 0.0725,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "ID": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "IL": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "IN": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "IA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "KS": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "KY": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "LA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "ME": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MD": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MI": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MN": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MS": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MO": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "MT": {
    "treatment": "reduced_rate",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": 0.041,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "NE": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "NV": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "NH": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "NJ": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "NM": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "NY": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "NC": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "ND": {
    "treatment": "excluded",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": 0.4,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "OH": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "OK": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "OR": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "PA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "RI": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "SC": {
    "treatment": "excluded",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": 0.44,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "SD": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "TN": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "TX": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "UT": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "VT": {
    "treatment": "excluded",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": 0.4,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "VA": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "WA": {
    "treatment": "special",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": 0.07,
    "specialRateThreshold": 278000,
    "shortTermTreatment": null
  },
  "WV": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "WI": {
    "treatment": "excluded",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": 0.3,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": "ordinary"
  },
  "WY": {
    "treatment": "none",
    "ordinaryRateApplies": false,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  },
  "DC": {
    "treatment": "ordinary",
    "ordinaryRateApplies": true,
    "ltcgExclusionPct": null,
    "specialRate": null,
    "specialRateThreshold": null,
    "shortTermTreatment": null
  }
};

export default stateCapGains;
