/**
 * GENERATED by scripts/gen-data.mjs from legacy/data/config.json — do not edit by hand.
 * Verified 2026 dataset. Figures copied verbatim from the legacy source.
 * UI-facing projection of overrides/state-inheritance-2026.json. Sources and confidence stripped; compute fields only.
 */
export interface StateDeathTax {
  hasEstateTax: boolean; estateExemption: number | null; estateTopRate: number | null; estateNote: string | null;
  hasInheritanceTax: boolean;
  inheritance: { spouse: number; lineal: number; sibling: number; other: number } | null;
  inheritanceNote: string | null;
}

export const stateDeathTax: Record<string, StateDeathTax> = {
  "CT": {
    "hasEstateTax": true,
    "estateExemption": 15000000,
    "estateTopRate": 0.12,
    "estateNote": "Exemption tied to the federal $15M; flat 12% above it. CT also has a state gift tax.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "HI": {
    "hasEstateTax": true,
    "estateExemption": 5490000,
    "estateTopRate": 0.2,
    "estateNote": "Graduated 10-20%; 20% (highest state rate) above $10M. Exemption fixed, not indexed.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "IL": {
    "hasEstateTax": true,
    "estateExemption": 4000000,
    "estateTopRate": 0.16,
    "estateNote": "Graduated to ~16%; exemption $4M, not indexed. Administered by the Illinois Attorney General.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "ME": {
    "hasEstateTax": true,
    "estateExemption": 7160000,
    "estateTopRate": 0.12,
    "estateNote": "Graduated 8/10/12%; exemption indexed ($7,160,000 for 2026).",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MN": {
    "hasEstateTax": true,
    "estateExemption": 3000000,
    "estateTopRate": 0.16,
    "estateNote": "Graduated 13-16%; exemption $3M fixed. 3-year gift claw-back.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MA": {
    "hasEstateTax": true,
    "estateExemption": 2000000,
    "estateTopRate": 0.16,
    "estateNote": "$2M threshold with a credit so estates at/below $2M owe nothing; graduated to 16%.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "NY": {
    "hasEstateTax": true,
    "estateExemption": 7350000,
    "estateTopRate": 0.16,
    "estateNote": "Exemption indexed ($7,350,000 for 2026), graduated to 16%. CLIFF: an estate over 105% of the exemption (~$7,717,500) is taxed from the first dollar — not modeled here.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "OR": {
    "hasEstateTax": true,
    "estateExemption": 1000000,
    "estateTopRate": 0.16,
    "estateNote": "Lowest exemption in the US ($1M, fixed); graduated 10-16%. A natural-resource credit can exempt qualifying farm/forest property.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "RI": {
    "hasEstateTax": true,
    "estateExemption": 1838056,
    "estateTopRate": 0.16,
    "estateNote": "Threshold $1,838,056 for 2026 (via a $87,940 credit), indexed; graduated to 16%.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "VT": {
    "hasEstateTax": true,
    "estateExemption": 5000000,
    "estateTopRate": 0.16,
    "estateNote": "Flat 16% above a $5M exemption (fixed). No portability.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "WA": {
    "hasEstateTax": true,
    "estateExemption": 3076000,
    "estateTopRate": 0.35,
    "estateNote": "SPLIT-YEAR 2026: deaths Jan 1-Jun 30 use the 35% top-rate schedule (SB 5813); deaths Jul 1 onward revert to a 20% top rate (SB 6347). Exemption ~$3,076,000 (H1). The stored 0.35 is the H1 rate.",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "DC": {
    "hasEstateTax": true,
    "estateExemption": 4988400,
    "estateTopRate": 0.16,
    "estateNote": "Graduated ~11.2-16%; exemption indexed ($4,988,400 for 2026).",
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "KY": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": true,
    "inheritance": {
      "spouse": 0,
      "lineal": 0,
      "sibling": 0,
      "other": 0.16
    },
    "inheritanceNote": "Class A (spouse, parents, children, siblings, grandchildren) fully exempt. Class B (nieces/nephews/aunts/uncles) 4-16%; Class C (others) 6-16%. Top 16%."
  },
  "NE": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": true,
    "inheritance": {
      "spouse": 0,
      "lineal": 0.01,
      "sibling": 0.11,
      "other": 0.15
    },
    "inheritanceNote": "County-levied. Spouse and anyone under 22 exempt. Immediate relatives 1% over $100k; remote relatives 11% over $40k; all others 15% over $25k."
  },
  "NJ": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": true,
    "inheritance": {
      "spouse": 0,
      "lineal": 0,
      "sibling": 0.16,
      "other": 0.16
    },
    "inheritanceNote": "Class A (spouse, children, parents, grandchildren) exempt. Class C (siblings, in-laws) first $25k exempt then 11-16%. Class D (others) 15% to $700k, 16% above. NJ repealed its estate tax in 2018."
  },
  "PA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": true,
    "inheritance": {
      "spouse": 0,
      "lineal": 0.045,
      "sibling": 0.12,
      "other": 0.15
    },
    "inheritanceNote": "Spouse 0%; lineal descendants/heirs 4.5%; siblings 12%; all others 15%. Applied from the first dollar. 5% discount if paid within 3 months."
  },
  "MD": {
    "hasEstateTax": true,
    "estateExemption": 5000000,
    "estateTopRate": 0.16,
    "estateNote": "Estate tax: $5M exemption (fixed), graduated to 16%. Portability allowed. Estate tax is reduced by inheritance tax paid.",
    "hasInheritanceTax": true,
    "inheritance": {
      "spouse": 0,
      "lineal": 0,
      "sibling": 0,
      "other": 0.1
    },
    "inheritanceNote": "Inheritance tax: 10% flat to heirs who are NOT spouse/lineal/sibling (those are exempt)."
  },
  "AL": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "AK": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "AZ": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "AR": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "CA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "CO": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "DE": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "FL": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "GA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "ID": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "IN": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "IA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "KS": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "LA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MI": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MS": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MO": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "MT": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "NV": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "NH": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "NM": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "NC": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "ND": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "OH": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "OK": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "SC": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "SD": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "TN": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "TX": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "UT": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "VA": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "WV": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "WI": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  },
  "WY": {
    "hasEstateTax": false,
    "estateExemption": null,
    "estateTopRate": null,
    "estateNote": null,
    "hasInheritanceTax": false,
    "inheritance": null,
    "inheritanceNote": null
  }
};

export default stateDeathTax;
